[default]
[install]
is_configured = 0

[launcher]
author = Bryan Pluta
description = An app to share alert data between Enterprise Security and ITSI. Sends ES notables to ITSI and ITSI episodes to ES.
version = 1.0.1

[id]
name = DA-ITSI-CP-CUST-shared-alerting
version = 1.0.1

[package]
id = DA-ITSI-CP-CUST-shared-alerting

[ui]
is_visible = 0
label = Splunk App for Shared Alerting

[triggers]
reload.analyticstories = simple
reload.content_pack_settings = simple

