
[expose:TA_trendmicrocloudappsecurity_settings]
pattern = TA_trendmicrocloudappsecurity_settings
methods = POST, GET

[expose:TA_trendmicrocloudappsecurity_settings_specified]
pattern = TA_trendmicrocloudappsecurity_settings/*
methods = POST, GET, DELETE

[expose:TA_trendmicrocloudappsecurity_tmcas_detection_logs]
pattern = TA_trendmicrocloudappsecurity_tmcas_detection_logs
methods = POST, GET

[expose:TA_trendmicrocloudappsecurity_tmcas_detection_logs_specified]
pattern = TA_trendmicrocloudappsecurity_tmcas_detection_logs/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
