
[admin:TA_national_grid_carbon_intensity]
match = /
members = TA_national_grid_carbon_intensity_settings, TA_national_grid_carbon_intensity_national_grid_carbon_intensity_forecast, TA_national_grid_carbon_intensity_national_grid_carbon_intensity_forecast_by_region, TA_national_grid_carbon_intensity_national_grid_carbon_intensity, TA_national_grid_carbon_intensity_national_grid_carbon_intensity_by_region

[admin_external:TA_national_grid_carbon_intensity_settings]
handlertype = python
python.version = python3
handlerfile = TA_national_grid_carbon_intensity_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_national_grid_carbon_intensity_national_grid_carbon_intensity_forecast]
handlertype = python
python.version = python3
handlerfile = TA_national_grid_carbon_intensity_rh_national_grid_carbon_intensity_forecast.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_national_grid_carbon_intensity_national_grid_carbon_intensity_forecast_by_region]
handlertype = python
python.version = python3
handlerfile = TA_national_grid_carbon_intensity_rh_national_grid_carbon_intensity_forecast_by_region.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_national_grid_carbon_intensity_national_grid_carbon_intensity]
handlertype = python
python.version = python3
handlerfile = TA_national_grid_carbon_intensity_rh_national_grid_carbon_intensity.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_national_grid_carbon_intensity_national_grid_carbon_intensity_by_region]
handlertype = python
python.version = python3
handlerfile = TA_national_grid_carbon_intensity_rh_national_grid_carbon_intensity_by_region.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
