
[admin:TA_cofense_triage_add_on_for_splunk]
match = /
members = TA_cofense_triage_add_on_for_splunk_account, TA_cofense_triage_add_on_for_splunk_settings, TA_cofense_triage_add_on_for_splunk_cofense_triage

[admin_external:TA_cofense_triage_add_on_for_splunk_account]
handlertype = python
handlerfile = TA_cofense_triage_add_on_for_splunk_rh_account.py
handleractions = edit, list, remove, create
python.version = python3

[admin_external:TA_cofense_triage_add_on_for_splunk_settings]
handlertype = python
handlerfile = TA_cofense_triage_add_on_for_splunk_rh_settings.py
handleractions = edit, list
python.version = python3

[admin_external:TA_cofense_triage_add_on_for_splunk_cofense_triage]
handlertype = python
handlerfile = TA_cofense_triage_add_on_for_splunk_rh_cofense_triage.py
handleractions = edit, list, remove, create
python.version = python3
