[admin:alert_gotify_configuration]
match = /
members = alert_gotify_settings

[admin_external:alert_gotify_settings]
handlertype = python
python.version = python3
handlerfile = alert_gotify_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true
