#
# Sysdig App for Splunk
#

[install]
is_configured = 0
build = 2

[ui]
is_visible = 1
label = Sysdig App for Splunk

[launcher]
author = Sysdig, Inc.
description = The Sysdig App for Splunk integrates with the Sysdig service to provide value and insight into your data.
version = 1.1.2

[package]
id = SysdigAppForSplunk