[omega_ca_nt]
coldPath = $SPLUNK_DB/omega_ca_nt/colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB/omega_ca_nt/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/omega_ca_nt/thaweddb
