[getinfo]
enableheader = true
filename = acs_server_helper.py
python.version = python3
local = true
passauth = true
requires_srinfo = true
run_in_preview = false
stderr_dest = message
supports_getinfo = false