[syslog]
TRANSFORMS-A0_extractSyslogPriority = t_extractSyslogPriority
TRANSFORMS-z1_extractSyslogFacilit_Severity = t_extractSyslogFacility,t_extractSyslogSeverity
## Uncomment TRANSFORMS- below and corresponding stanza in transforms.conf if i
## you want to strip syslog priority tag (e.g. <15>... ) from _raw
#TRANSFORMS-z2_stripSyslogPriority = t_stripSyslogPriority 
LOOKUP-syslogFacility = syslogFacility syslogFacilityNumber OUTPUTNEW syslogFacility
LOOKUP-syslogSeverity = syslogSeverity syslogSeverityNumber OUTPUTNEW syslogSeverity

