[correlate_bad_ip(4)]
args = sourceIndex, threatIndex, mysourcetype, myfield
definition = index=$sourceIndex$ sourcetype="$mysourcetype$" [search index=$threatIndex$ sourcetype=ip_watchlist earliest=-1d|dedup offending_ip | eval $myfield$=offending_ip| fields + $myfield$]|table sourcetype $myfield$
iseval = 0
