[audit_input]
index = default
start_by_shell = false
python.version = python3
sourcetype = safebreach:audit:api
interval = 3600
disabled = 0

[simulation_input]
index = default
start_by_shell = false
python.version = python3
sourcetype = safebreach:simulation:api
interval = 3600
offset = 20
disabled = 0
extra_fields_to_parse = []

[insights_input]
index = default
start_by_shell = false
python.version = python3
sourcetype = safebreach:insights:api
interval = 3600
disabled = 0

