[eventtype=safebreach_dataleak]
ids = enabled
attack = enabled        
network = enabled
communicate = enabled   
dlp = enabled
incident = enabled      

[eventtype=safebreach_web]
ids = enabled
attack = enabled        
network = enabled
communicate = enabled   
web = enabled           

[eventtype=safebreach_endpoint]
endpoint = enabled
filesystem = enabled    
malware = enabled
attack = enabled
    
[eventtype=safebreach_email]
email = enabled        
ids = enabled
attack = enabled        

[eventtype=safebreach_networkinspection]
ids = enabled
attack = enabled        
network = enabled
communicate = enabled   
web = enabled           
malware = enabled
    
[eventtype=safebreach_networkaccess]
network = enabled
communicate = enabled   

[eventtype=safebreach_container]
endpoint = enabled
filesystem = enabled    
malware = enabled
attack = enabled
    
[eventtype=safebreach_cloud]
ids = enabled
attack = enabled        
network = enabled
communicate = enabled   

[eventtype=safebreach_insights_port]
network = enabled
communicate = enabled

[eventtype=safebreach_insights_protocol]
network = enabled
communicate = enabled

[eventtype=safebreach_insights_command]
process = enabled
report = enabled

[eventtype=safebreach_insights_sha256]
malware = enabled
attack = enabled

[eventtype=safebreach_insights_fqdn_ip]
network =enabled
resolution = enabled
dns = enabled

[eventtype=safebreach_insights_uri]
web = enabled
