[source::...send_to_soc_toolkit_modalert.log*]
SHOULD_LINEMERGE = true
sourcetype = soctoolkit:log

[source::...soctoolkit_connector_ta_nxtp*.log*]
sourcetype = soctoolkit:log


[soc-toolkit:audit]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
