# this add-on is powered by splunk Add-on builder
[install]
is_configured = false
state = enabled
build = 4

[launcher]
author = SecurityScorecard
version = 2.3.2
description = The SecurityScorecard addon for Splunk offers customers the ability to monitor SecurityScorecard’s overall letter-grade security ratings, underlying factor data in key risk categories & issue-related data.

[ui]
is_visible = 1
label = SecurityScorecard Add-on for Splunk
docs_section_override = AddOns:released

[package]
id = TA-securityscorecard

[triggers]
reload.addon_builder = simple
reload.ta_securityscorecard_account = simple
reload.ta_securityscorecard_settings = simple
