[parse_ansible_results_queue]
start_by_shell = false
python.version = python3
sourcetype = Ansible:Results
interval = 30
queue_handler = thisServer
disabled = 0

[parse_ansible_collection_queue]
start_by_shell = false
python.version = python3
sourcetype = Ansible:Queue
interval = 60
batch_size = 10
queue_handler = thisServer
disabled = 0

