[repcap]
## Configuration options for the ReportCapture app
## See the documentation for more information

# Logging level (info/warn/error/debug)
# Note: Unless really required, leave at debug
loglevel = debug

# Path to the CasperJS binary
casperjs_bin = /opt/casperjs/bin/casperjs
#casperjs_bin = C:\CasperJS\bin\casperjs.exe

# Path to the ImageMagick convert binary
convert_bin = /usr/bin/convert
#convert_bin = C:\ImageMagick\convert.exe

# Path to the PhantomJS binary
phantomjs_bin = /opt/phantomjs/bin/phantomjs
#phantomjs_bin = C:\PhantomJS\bin\phantomjs.exe

# Connection host (of SplunkWeb)
conn_host = 127.0.0.1

# Connection port (of SplunkWeb)
conn_port = 8000

# Connection protocol (http or https)
# Note: This should match your Splunk server mode, or expect failures
conn_proto = http

# Ingore SSL errors for HTTPS (i.e. self-signed certificates)
conn_ssl_ignore = true

# Email allowed-domains (separate each entry with a ;, or use ALL)
email_allow_domains = ALL

# Email enabled (set to false to forbid email)
email_enabled = true

# Email from (use an email address or 'friendly_name <user@host>'
email_from = Splunk <splunk@local>

# Email server hostname/ip
email_srv_host = 127.0.0.1

# Email server port
email_srv_port = 25

# Email server username
email_srv_user = anonymous

# Email server password (must be base64-encoded)
email_srv_pass = YW5vbnltb3Vz

# Email server flag - use authentication
email_srv_useauth = false

# Email server flag - use TLS
email_srv_usetls = false

# Email subject
email_sub = New report from __SUB_USER__ (__SUB_REPORT_NAME__)

# Default filename (less extension)
file_name = report

# Default file-type
file_type = pdf

# Page orientation (landscape or portrait)
# Note: The requester can override this (within the two values)
page_orient = landscape

# Page size (see the readme for supported sizes)
# Note: The requester can override this (within the supported values)
page_size = A4

# How long to let a page load before capture (seconds)
# Note: The requester can override this (within the min/max values)
page_wait = 10

# Page-load minimum and maximums (seconds)
page_wait_max = 120
page_wait_min = 5

# Enable REST scripting
# WARNING: Enabling this means that a different authentication route is taken, which may
#          open the environment up to security issues.
#          Enabling this option is done at your own risk!
rest_scripted_enabled = false

# Screen dimensions minimum and maximum
# Note: The minimum is 1024x768 VGA, the max is 8K UHD
screen_res_min = 768
screen_res_max = 7680

# Enable HiDPI support in PhantomJS (for sharper output)
# Note: The requester can override this
screen_hidpi = true

# Screen zoom (use with caution)
# Note: The default is 1.0, meaning 100% zoom on the page
screen_zoom = 1.0
