##Palo Alto Networks IoT Security##

[ccx_paloalto_iot_extended_kv_capture]
FORMAT = $1::$3
REGEX = \"label\"\: ?"((?:[^"\\]|\\.)+)"\, \"value\"\: (\"|\[\"|)((?:[^"\\|\}]|\\.)+)

[ccx_palo_alto_firewall_authentication]
REGEX = .+(?:failed\s+authentication\s+for\s+)?(?:U|u)ser\s\'?(?<vendor_user>\S+)\s+(?:(?:auth\s+profile)|(?:logged\s+in))?.+

[ccx_paloalto_firewall_network_ip]
CLEAN_KEYS = 0
REGEX = .+(?:\"EventDescription\"\:\").+\s(?<srcip>(?:\d{1,3}\.){3}\d{1,3})\:(?<srcport>\d+)\s(?=->)\-\>\s(?<destip>(?:\d{1,3}\.){3}\d{1,3})\:(?<destport>\d+)\s.+

[ccx_palo_alto_firewall_cloud_config]
batch_index_query = 0
case_sensitive_match = 1
filename = ccx_palo_alto_firewall_cloud_config.csv

[ccx_palo_alto_firewall_cloud_system]
batch_index_query = 0
case_sensitive_match = 1
filename = ccx_palo_alto_firewall_cloud_system.csv
