[newrelic_applications]
search = (sourcetype=newrelic:applications)

[newrelic_applications_eum]
search = (sourcetype=newrelic:applications) (eum_apdex_score=* OR eum_response_time=* OR eum_thruput=* OR eum_error_rate=*)

[newrelic_transactions]
search = (sourcetype=newrelic:transactions)

