#   Version 6.4.0
#########
#
#	Monitor stoQ internal operation logs
#########

[monitor:///usr/local/stoq/logs/*.log]
sourcetype = stoq
index = stoq

[monitor:///usr/local/stoq/plugins/worker/.../*.yar]
index = stoq
sourcetype = stoq:signatures:yara
source = /usr/local/stoq/plugins/worker/yara
crcSalt = <SOURCE>

[monitor:///usr/local/stoq/results/exif/*.stoq]
index = stoq
sourcetype = stoq:exif
source = /usr/local/stoq/results/exif
crcSalt = <SOURCE>

[monitor:///usr/local/stoq/results/clamav/*.stoq]
index = stoq
sourcetype = stoq:clamav
source = /usr/local/stoq/results/clamav
crcSalt = <SOURCE>

[monitor:///usr/local/stoq/results/peinfo/*.stoq]
index = stoq
sourcetype = stoq:peinfo
source = /usr/local/stoq/results/peinfo
crcSalt = <SOURCE>

[monitor:///usr/local/stoq/results/smtp/*.stoq]
index = stoq
sourcetype = stoq:smtp
source = /usr/local/stoq/results/smtp
crcSalt = <SOURCE>

[monitor:///usr/local/stoq/results/trid/*.stoq]
index = stoq
sourcetype = stoq:trid
source = /usr/local/stoq/results/trid
crcSalt = <SOURCE>

[monitor:///usr/local/stoq/results/yara/*.stoq]
index = stoq
sourcetype = stoq:yara
source = /usr/local/stoq/results/yara
crcSalt = <SOURCE>

[monitor:///usr/local/stoq/results/vtmis/*.stoq]
index = stoq
sourcetype = stoq:vtmis
source = /usr/local/stoq/results/vtmis
crcSalt = <SOURCE>

[monitor:///usr/local/stoq/results/totalhash/*.stoq]
index = stoq
sourcetype = stoq:totalhash
source = /usr/local/stoq/results/totalhash
crcSalt = <SOURCE>
