[acti_threatindicator_ip]
collection = acti_threatindicator_ip
external_type = kvstore
fields_list = _key, type, threat_types, severity, last_seen_as, confidence, last_published, last_modified, last_seen, uuid, files, malware_family, threat_campaigns, threat_campaigns.type, mentioned_by, seen_at, asns, files.display_text, files.confidence, files.key, files.last_seen, files.malware_family, files.relationship, files.uuid, files.sha1, files.sha256, files.href, files.relationship_created_on, files.relationship_last_published

[acti_threatindicator_domain]
collection = acti_threatindicator_domain
external_type = kvstore
fields_list = _key, type, threat_types, severity, last_seen_as, confidence, last_published, last_modified, last_seen, uuid, files, malware_family, threat_campaigns, threat_campaigns.type, mentioned_by, seen_at, idn, files.display_text, files.confidence, files.key, files.last_seen, files.malware_family, files.relationship, files.uuid, files.sha1, files.sha256, files.href, files.relationship_created_on, files.relationship_last_published

[acti_threatindicator_url]
collection = acti_threatindicator_url
external_type = kvstore
fields_list = _key, type, threat_types, severity, last_seen_as, confidence, last_published, last_modified, last_seen, uuid, files, malware_family, threat_campaigns, threat_campaigns.type, mentioned_by, seen_at, arguments, files.display_text, files.confidence, files.key, files.last_seen, files.malware_family, files.relationship, files.uuid, files.sha1, files.sha256, files.href, files.relationship_created_on, files.relationship_last_published

[acti_threatindicator_file]
collection = acti_threatindicator_file
external_type = kvstore
fields_list = _key, type, threat_types, severity, last_seen_as, confidence, last_published, last_seen, uuid, malware_family, threat_campaigns, threat_campaigns.type, mentioned_by, seen_at, sha1, sha256, md5, parent_relationship, parent_key, parent_type

[acti_domain_ioc_lookup]
filename = acti_domain_ioc.csv

[acti_ip_ioc_lookup]
filename = acti_ip_ioc.csv
fields_list = domain, weight, time, description, domain

[acti_url_ioc_lookup]
filename = acti_url_ioc.csv
fields_list = url, http_referrer, weight, time, description, domain

[acti_file_ioc_lookup]
filename = acti_file_ioc.csv
fields_list = file_hash, weight, time, description, domain

[acti_vuln_lookup]
filename = acti_vuln.csv
fields_list = cve, signature, cvss2_base_score, cvss, cvss3_base_score, severity, signature_id

[acti_ti_retention]
filename = acti_ti_retention.csv
fields_list = ip, weight, time, description, domain

[acti_vulnerability]
collection = acti_vulnerability
external_type = kvstore
fields_list = _key, title, severity, last_modified, cvss2_base_score, cvss3_base_score, cvss3_temporal_score, cvss2_temporal_score, cvss2, cvss3, threat_types, analysis, cwe, description, display_text, notable_zero_day, fixed_by.vuln_techs.key, fixed_by.vuln_techs.uuid, fixed_by.vuln_techs.vendor, fixed_by.vuln_techs.version, fixed_by.vuln_techs.display_text, affects.vuln_techs.key, affects.vuln_techs.vendor, affects.vuln_techs.product, affects.vuln_techs.version, pocs.description, pocs.poc_authos, pocs.poc_name, sources_external.description, sources_external.name, sources_external.url, vendor_fix_external.advisory_id, vendor_fix_external.url
case_sensitive_match = false
