# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 102

[launcher]
author = Netwrix Corporation
version = 2.0.0
description = Netwrix file activity monitoring solutions enable organizations to successfully, efficiently, and affordably monitor file access and permission changes across Windows and NAS file systems in real-time, without any reliance on native logging. Using the preconfigured Netwrix File Activity Monitor App for Splunk, users can quickly understand all file activities as a whole, for specific resources or users, as well as patterns of activity indicative of threats such as crypto ransomware. With full control over the data, users can create custom searches, views, and dashboard elements, all while enabling Splunk to correlate file system activity with any data source. Learn more about Netwrix at https://www.Netwrix.com/.

[ui]
is_visible = 1
label = Netwrix File Activity Monitor App for Splunk
docs_section_override = AddOns:released

[package]
id = sb_fam

[triggers]
reload.addon_builder = simple
reload.sb_fam_account = simple
reload.sb_fam_settings = simple
reload.passwords = simple

[author=Netwrix]
email = splunk@netwrix.com
company = Netwrix Corporation

