[script:summarize_api]
match                 = /api/v1/itsi_summaries/summarize
python.version        = python3
script                = summarize_api.py
scripttype            = persist
handler               = application.SummarizeAPIHandler
capability.post       = summarize_post
capability.delete     = summarize_delete

[script:health_api]
match                 = /api/v1/itsi_summaries/health
python.version        = python3
script                = health_api.py
scripttype            = persist
handler               = application.HealthAPIHandler
capability.get        = health_get
