[launcher]
version = 2.0.15
description = GitLab Saas Add-on for Splunk

[id]
version = 2.0.15
name = TA-gitlab-saas-add-on-for-splunk

[install]
build = 1741115872
is_configured = false
state = enabled

[package]
id = TA-gitlab-saas-add-on-for-splunk
check_for_updates = true

[ui]
label = GitLab Saas Add-on for Splunk
is_visible = true

[triggers]
reload.ta_gitlab_saas_add_on_for_splunk_settings = simple
reload.ta_gitlab_saas_add_on_for_splunk_account = simple
