[phishiqplus_correlation_fields]
definition = table _time url phishiq_original_url phishiq_prediction phishiq_risk_level phishiq_source_event_time phishiq_source_event_host phishiq_source_event_source phishiq_source_event_sourcetype phishiq_source_event_hash
iseval = 0

[phishiqplus_correlation_filter(2)]
args = index,sourcetype
definition = index=$index$ sourcetype=$sourcetype$ phishiq_source_event_hash=*
iseval = 0
