[id]
name = insights-app
version = 1.0.3

[ui]
is_visible = 1
label = Insights Platform
supported_themes = light,dark

[launcher]
author = msi
description = Insights Platform
version = 1.0.3

[package]
id = insights-app

[install]
is_configured = 0
build = 2

[triggers]
reload.splunk_create = simple