# Splunk app configuration file

[ui]
is_visible = 1
label = DocoDoco Advance

[launcher]
description = get generation data and organizational data from  IP
author = Geolocation Techunology, Inc.
version = 1.0.1

[id]
version = 1.0.1
name = docodoco_advance

[package]
check_for_updates = 1
id = docodoco_advance

[install]
is_configured = 0
state = enabled


[triggers]
reload.docodoco_advance_config = simple
