[expose:qintel_qsentry_elements]
pattern = qintel_qsentry/*
methods = GET

[expose:qintel_qsentry_settings]
pattern = qintel_qsentry_settings
methods = POST, GET

[expose:qintel_qsentry_settings_specified]
pattern = qintel_qsentry_settings/*
methods = POST, GET, DELETE
