[snyk_projects]
start_by_shell = false
python.version = python3
sourcetype = snyk:project
interval = 86400
api_region = https://api.snyk.io
disabled = 0

[snyk_issues]
start_by_shell = false
python.version = python3
sourcetype = snyk:issue
interval = 86400
api_region = https://api.snyk.io
disabled = 0

