[monitor:///$SPLUNK_HOME/var/log/splunk/ServiceIntelligenceForSAP.log]
index=_internal
sourcetype=ServiceIntelligenceForSAP

#[http]
#port=8088
#disabled=0
#crossOriginSharingPolicy = *

#[http://ServiceIntelligenceForSAP]
#token=ServiceIntelligenceForSAP
#indexes=_internal
#index=_internal
#sourcetype=ServiceIntelligenceForSAPWebClient
