[rqaware]
search = index=rqaware

[rqaware_ip]
search = index=rqaware match_type=ip

[rq_c2url]
search = index=rqaware FeedCategory=C2URL

[rq_scanner_ip]
search = index=rqaware FeedCategory=ScannerIP

[rq_ransomware_url]
search = index=rqaware FeedCategory=RansomwareURL

[rq_ransomware_ip]
search = index=rqaware FeedCategory=RansomwareIP

[rq_ransomware_domain]
search = index=rqaware FeedCategory=RansomwareDomain

[rq_phish_url]
search = index=rqaware FeedCategory=PhishURL

[rq_phish_tank]
search = index=rqaware FeedCategory=PhishTank

[rq_phish_ip]
search = index=rqaware FeedCategory=PhishIP

[rq_malware_url]
search = index=rqaware FeedCategory=MalwareURL

[rq_malware_ip]
search = index=rqaware FeedCategory=MalwareIP

[rq_malware_domain]
search = index=rqaware FeedCategory=MalwareDomain

[rq_c2ip]
search = index=rqaware FeedCategory=C2IP

[rq_c2domain]
search = index=rqaware FeedCategory=C2Domain

[rq_bruteforceip]
search = index=rqaware FeedCategory=BruteforceIP

[rq_botip]
search = index=rqaware FeedCategory=BotIP
