######################
## Mitre Attack ICS ##
######################
[threatlist://mitre_attack_ics]
delim_regex = ,
ignore_regex = (^#|^\s*$)
description = MITRE ATT&CK ICS framework
disabled = 0
interval = 86400
file_parser = mitre
is_threatintel = 0
max_age = -365d
max_size = 52428800
parse_modifiers = {"certificate_attribute_breakout": 1, "idna_encode": 1, "domain_from_url": 0}
retries = 3
retry_interval = 60
sinkhole = 1
skip_header_lines = 0
timeout = 30
type = mitre_attack_ics
url = https://raw.githubusercontent.com/mitre/cti/master/ics-attack/ics-attack.json
encoding = utf-8
weight = 60
workloads = [{"type":"savedsearch","workload":"Threat - Mitre Attack_ICS - Lookup Gen"}]