[getdiaginfo]
filename = getdiaginfo.py
python.version = python3
chunked = true

[setupdiag]
filename = setupdiag.py
python.version = python3
chunked = true


[requestdiag]
filename = requestdiag.py
python.version = python3
chunked = true
passauth = true