[compliance_check_json]
KV_MODE=json 
TIME_PREFIX=timestamp\"\s*:\s*\"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
MAX_TIMESTAMP_LOOKAHEAD = 30
TZ = Australia/Sydney

[compliance_check]
INDEXED_EXTRACTIONS =
KV_MODE = none
AUTO_KV_JSON = false