[post_cw_ticket_to_slack]
is_custom = 1
label = Post New Tickets to Slack
icon_path = slackAlertAction.png
payload_format = json
alert.execute.cmd = connectWise2Slack.py
python.version = python3
param.board_id = 0
param.channel = #
param.webhook_url = https://
