[DTEX InTERCEPT Category Investigation]
display_location = event_menu
eventtypes = Alert_Events
fields = *
label = DTEX InTERCEPT Category Investigation
link.method = get
link.target = blank
link.uri = https://$!subject$
type = link

[DTEX InTERCEPT Category Investigation for Notable]
display_location = event_menu
eventtypes = notable
fields = *
label = DTEX InTERCEPT Category Investigation for Notable
link.method = get
link.target = blank
link.uri = https://$!subject$
type = link