######################################################
#
# Splunk_TA_CCX_BeyondTrust_Products
#
#
######################################################
[install]
is_configured = false

[ui]
is_visible = true
label = CCX Add-on for BeyondTrust Products

[launcher]
author = CyberCX
description = CCX Add-on for BeyondTrust Products
version = 1.1.5

[package]
id = Splunk_TA_CCX_BeyondTrust_Products
check_for_updates = true
