[datalake]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-datalake-connect*.log*]
sourcetype = tadatalakeconnect:log

[source::...ta_datalake_connect*.log*]
sourcetype = tadatalakeconnect:log

[source::datalake_connect]
DATETIME_CONFIG = CURRENT
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = 1
SHOULD_LINEMERGE = 0
#REPORT-ta_builder_internal_use_kv_format_results_for_datalake_ip = ta_builder_internal_use_kv_format_results_for_datalake_ip
#EXTRACT-datalake_fields = ^atom_value=(?<atom_value>.*);\sfirst_seen=(?<first_seen>.*);\slast_updated=(?<last_updated>.*);\sthreat_hashkey=(?<threat_hashkey>.*);\sthreat_types=(?<threat_types>.*);\sthreat_scores=(?<threat_scores>.*);\ssources=(?<sources>.*);\stags=(?<tags>.*);\satom_type=(?<atom_type>.*)
EXTRACT-extract-fields = \[\'(?<atom_value>[^\']*)\', \'(?<first_seen>[^\']*)\', \'(?<last_updated>[^\']*)\', \'(?<threat_hashkey>[^\']*)\', \'(?<threat_types>[^\']*)\', \'(?<threat_scores>[^\']*)\', \'(?<sources>[^\']*)\', \'(?<tags>[^\']*)\'\]
EVAL-atom_type = case(sourcetype=="datalake_ip","ip",sourcetype=="datalake_ip_range","ip_range",sourcetype=="datalake_domain","domain",sourcetype=="datalake_fqdn","fqdn",sourcetype=="datalake_file","file",sourcetype=="datalake_email","email",sourcetype=="datalake_regkey","regkey",sourcetype=="datalake_ssl","ssl",sourcetype=="datalake_url","url",sourcetype=="datalake_apk","apk",sourcetype=="datalake_as","as",sourcetype=="datalake_cc","cc",sourcetype=="datalake_crypto","crypto",sourcetype=="datalake_cve","cve",sourcetype=="datalake_iban","iban",sourcetype=="datalake_paste","paste",sourcetype=="datalake_phone","phone")

