[launcher]
version = 2.1.2
description = sendtohec Custom Search Command

[id]
version = 2.1.2
name = ta_send_to_hec_command

[install]
build = 1773818756
is_configured = false
state = enabled

[package]
id = ta_send_to_hec_command
check_for_updates = true

[ui]
label = sendtohec Custom Search Command
is_visible = true

[triggers]
reload.ta_send_to_hec_command_settings = simple
reload.ta_send_to_hec_command_target = simple
