[APISec-Finding]
search = (sourcetype=APISec-Finding)

[APISec-AuditLog-Auth]
search = (sourcetype=APISec-AuditLog operation=*Login* OR operation=*Logout*)

[APISec-AuditLog]
search = (sourcetype=APISec-AuditLog NOT (operation=*Login* OR operation=*Logout*))

[APISec-Incident]
search = (sourcetype=APISec-Incident)
