[IA4S]
acceleration = false
acceleration.backfill_time = -1d
acceleration.cron_schedule = 2-57/5 * * * *
acceleration.earliest_time = -1d
acceleration.hunk.dfs_block_size = 0
acceleration.manual_rebuilds = true
acceleration.schedule_priority = highest
