[STIX]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-pdns-block-data-connector*.log*]
sourcetype = tapdnsblockdataconnector:log

[source::...ta_pdns_block_data_connector*.log*]
sourcetype = tapdnsblockdataconnector:log

