[install]
is_configured = false
build = 1750187813
state = enabled

[ui]
is_visible = true
label = Bitwarden Event Logs
setup_view = setup_page_dashboard

[id]
name = bitwarden_event_logs
version = 1.3.1

[triggers]
reload.script = simple
reload.bitwarden_event_logs_settings = simple

[package]
id = bitwarden_event_logs
check_for_updates = true

[launcher]
author = Bitwarden Inc.
version = 1.3.1
description = Bitwarden event logs integration into Splunk.
