[splunk_search_src_ip]
display_location = both
fields = src_ip, associatedId.flowId.ip.srcIp
label = Search Splunk for Source IP
search.search_string = src_ip=$src_ip$ earliest=$timestampE$ latest=$timestampL$
search.target = blank
search.view = search
type = search
search.preserve_timerange = 0

[splunk_search_dest_ip]
display_location = both
fields = dest_ip, associatedId.flowId.ip.dstIp
label = Search Splunk for Dest IP
search.search_string = dest_ip=$dest_ip$ earliest=$timestampE$ latest=$timestampL$
search.target = blank
search.view = search
type = search
search.preserve_timerange = 0

[ndr_search_killbox_ob_id]
display_location = both
fields = id
label = Search Protectwise Killbox for Observation ID
link.method = get
link.target = blank
link.uri = https://visualizer.protectwise.com/#killbox/observations?start=$occurredE$&end=$occurredL$&timeMode=occurredAt&id=$id$&sid=$sensorId$
type = link

[ndr_search_killbox_ob_dest_ip]
display_location = both
fields = dest_ip, associatedId.flowId.ip.dstIp
label = Search Protectwise Killbox for Dest IP
link.method = get
link.target = blank
link.uri = https://visualizer.protectwise.com/#killbox/observations?start=$occurredE$&end=$occurredL$&timeMode=occurredAt&ip=$dest_ip$
type = link

[ndr_search_killbox_ob_src_ip]
display_location = both
fields = src_ip, associatedId.flowId.ip.srcIp
label = Search Protectwise Killbox for Source IP
link.method = get
link.target = blank
link.uri = https://visualizer.protectwise.com/#killbox/observations?start=$occurredE$&end=$occurredL$&timeMode=occurredAt&ip=$src_ip$
type = link

[ndr_search_explorer_ob_src_ip]
display_location = both
fields = src_ip, associatedId.flowId.ip.srcIp
label = Search Protectwise Explorer for Source IP
link.method = get
link.target = blank
link.uri = https://visualizer.protectwise.com/#explorer?family=observations&start=$occurredE$&end=$occurredL$&ip=$src_ip$
type = link

[ndr_search_explorer_ob_dest_ip]
display_location = both
fields = dest_ip, associatedId.flowId.ip.dstIp
label = Search Protectwise Explorer for Dest IP
link.method = get
link.target = blank
link.uri = https://visualizer.protectwise.com/#explorer?family=observations&start=$occurredE$&end=$occurredL$&ip=$dest_ip$
type = link
