



[critical_check_SA_sideview_webex_custom_index_macro]
title = Check that the custom_index macro in the SA_sideview_webex app is a subset of the indexes specified in the Cisco CDR app's macro of the same name.
category = Data Indexing
tags = configuration, indexing
description = Check that the custom_index macro in the SA_sideview_webex app is a subset of the indexes specified in the Cisco CDR app's macro of the same name.
failure_text = The value set in the "custom_index" macro within the SA_sideview_webex app is not included in the macro by the same name over in the Cisco CDR Reporting and Analytics app.
suggested_action = See the test results for more details.

search = | rest /servicesNS/-/-/admin/macros splunk_server="local" \
| rename eai:acl.app as app \
| search title="custom_index" (app="cisco_cdr" OR app="SA_sideview_webex") \
| table title * \
| eval foo="1" \
| chart last(definition) over foo by app \
| eval cisco_cdr_is_installed=if(isnotnull(cisco_cdr),1,0)\
| eval severity_level=case(cisco_cdr_is_installed==0,1,match(cisco_cdr, SA_sideview_webex),2,true(),0) \
| eval metric=case(severity_level==0,"OK - the custom_index macro in this app matches what is set over in the cisco_cdr app", severity_level==1, "OK - the Cisco CDR app is not installed so we have nothing to check the custom_index macro against. This is fine.", severity_level==2,"ERROR - the custom_index macro in this app is not included in the macro of the same name over in the cisco_cdr app. ") \
| eval instance="all" \
| fields metric severity_level instance
