
######################################
### Anomalous DNS Data Collection  ###
######################################

[anomalous_dns_data]
field._key = string
field._user = string
field.last_update = time
field.domain = string
field.anomalous_type = string

######################################
###  Cluster SRC Data Collection   ###
######################################

[cluster_src_data]
field._key = string
field._user = string
field.last_update = time
field.src = string
field.cluster = bool
field.cluster_distance = number
field.avg_distinct_subdomains = number
field.avg_query_freq_hourly = number
field.avg_len = number
field.beacon_stdev = number
field.max_len = number
field.txt_ratio = number
field.any_ratio = number
field.hinfo_ratio = number
field.axfr_ratio = number

