
[admin:TA_trifork_surveillance]
match = /
members = TA_trifork_surveillance_settings, TA_trifork_surveillance_ntp_check, TA_trifork_surveillance_dns_check, TA_trifork_surveillance_tcp_check, TA_trifork_surveillance_icmp_check, TA_trifork_surveillance_http_check

[admin_external:TA_trifork_surveillance_settings]
handlertype = python
python.version = python3
handlerfile = TA_trifork_surveillance_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_trifork_surveillance_ntp_check]
handlertype = python
python.version = python3
handlerfile = TA_trifork_surveillance_rh_ntp_check.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_trifork_surveillance_dns_check]
handlertype = python
python.version = python3
handlerfile = TA_trifork_surveillance_rh_dns_check.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_trifork_surveillance_tcp_check]
handlertype = python
python.version = python3
handlerfile = TA_trifork_surveillance_rh_tcp_check.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_trifork_surveillance_icmp_check]
handlertype = python
python.version = python3
handlerfile = TA_trifork_surveillance_rh_icmp_check.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_trifork_surveillance_http_check]
handlertype = python
python.version = python3
handlerfile = TA_trifork_surveillance_rh_http_check.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
