[macro_linux_base]
definition = ()

[macro_linux_stats_host]
definition = (`macro_linux_base` sourcetype=linux_stats_v2_host)

[macro_linux_proc_stats]
definition = (`macro_linux_base` sourcetype=linux_proc_stats_v2)

[macro_linux_host_logs]
definition = (`macro_linux_base` sourcetype=linux_host_logs)

[macro_linux_net_stats]
definition = (`macro_linux_base` sourcetype=linux_net_stats*)

[macro_linux_net_socket_table]
definition = (`macro_linux_base` sourcetype=linux_net_socket_table)

[macro_linux_logs_collectord]
definition = (`macro_linux_host_logs` syslog_component::collectorforlinux)

[macro_linux_logs_collectord_license_check]
definition = `macro_linux_logs_collectord` license-check | rex field=_raw "^INFO .*license_check_pipe.go:\d+:\slicense-check\s(?<product>[^\s]+)\s(?<license_id>[^\s]+)?\s(?<limit>[^\s]+)\s(?<expiration>[^\s]+)\s(?<instance_id>[^\s]+)\s(?<created_at>[^\s]+)\s(?<started_at>[^\s]+)\s(?<version>[^\s]+)\s(?<build_date>[^\s]+)\s(?<valid>[^\s]+)\s(?<check_success>[^\s]+)\s(?<err_points>[^\s]+)(\sc(?<lUnits>\d+)\st(?<lType>\d+))?\s(?<message>.*)$" | eval version_major=mvindex(split(version, "."), 0, 0) | eval version_minor=mvindex(split(version, "."), 1, 1)

[macro_linux_mount_stats]
definition = (`macro_linux_base` sourcetype=linux_mount_stats)

[macro_linux_proc_capabilities_hex_to_binary(2)]
args = output, input
definition = eval $output$=replace(replace(replace(replace(replace(replace(replace(replace(\
                           replace(replace(replace(replace(replace(replace(replace(replace(\
                           replace(replace(upper($input$),"0","0000"),"1","0001"),"2","0010")\
                           ,"3","0011"),"4","0100"),"5","0101"),"6","0110"),"7","0111"),"8","1000"),\
                           "9","1001"),"A","1010"),"B","1011"),"C","1100"),"D","1101"),"E","1110"),"F"\
                           ,"1111"), "0", "/0"), "1", "/1")
iseval = 0

[macro_linux_prometheus_metrics_collectord]
definition = (`macro_linux_base` sourcetype=linux_prometheus source=collectord:*)

[macro_linux_alerts_base]
definition = ()