[shclustering]
conf_replication_include.utstream_inputs = true
conf_replication_include.utstream_instance = true
conf_replication_include.utstream_licenses = true
conf_replication_include.utstream_logging = true
conf_replication_include.utstream_settings = true
