##### STANZA FOR CSV LOOKUP (STATIC LOOKUPS USING CSV FILES)

# LOOKUP FOR HOST AND IT'S LOCATION
[host_location_lookup]
filename=Lookup.csv
min_matches=1
default_match=UNKNOWN
python.version=python3


##### DYNAMIC LOOKUPS USING PYTHON SCRIPTS

# LOOKUP TO GET HOSTNAME, GIVEN A HEX IP ADDRESS
[hexip]
default_match = Unresolved
external_cmd = clienthost.py clienthost clientip
fields_list = clienthost, clientip
min_matches = 1
python.version=python3

# LOOKUP TO FETCH COUNTRY NAME, GIVEN A HEX IP ADDRESS
[geolocation]
default_match = Unresolved / Broadcom Internal
external_cmd = geolocation.py country clientip
fields_list = country, clientip
min_matches = 1
python.version=python3

# LOOKUP TO RESOLVE HEX IP ADDRESS INTO IPV4 ADDRESS
[ipaddr]
default_match = Unresolved
external_cmd = ipaddr.py ipaddress clientip
fields_list = ipaddress, clientip
min_matches = 1
python.version=python3