[hibp-command]
syntax = hibp field=<validemailidfield>
shortdesc = HIBP Information checker (using email)
example1 =  | hibp field="validemailfield"
example2 = | makeresults | eval mail="xxx@email.com" | hibp field=mail
usage = public
