[ns_msg_lookup]
filename = ns_lookup.csv

[appid_lookup]
filename = appid_lookup.csv

[hostname_to_address]
filename = hostname_to_address.csv

# extract host. if the data is coming over udp, splunk adds a 
# timestamp and host to begining of the event. ignore those.
[ns_device_host_extract]
DEST_KEY = MetaData:Host
REGEX = \w{3}\s+\d+\s\d{2}:\d{2}:\d{2}\s+\S+\s+\d{2}/\d{2}/\d{4}:\d{2}:\d{2}:\d{2}\s+\w{3}\s+(\S+)
FORMAT = host::$1

# general extract
#REGEX = :\s+(AAA|UI|SSLLOG|SSLVPN|EVENT|APPFW|TCP|ROUTING|PITBOSS|CVPN)\s+(.+)\s+(\d+)\s+: <old rex for 9.3>
[ns_extract]
REGEX = :\s+(AAA|UI|SSLLOG|SSLVPN|EVENT|APPFW|TCP|ROUTING|PITBOSS|CVPN)\s+(\w+)\s+(\d+)\s+(\d+\s+:|:)
FORMAT = log_type::$1 msg_type::$2 msg_id::$3 

# extractions based on message type
[ns_9_firewall_extract]
REGEX = APPFW\sAPPFW_(\S+)\s\d+\s+:\s+(\S+)\s(\S+)\s(\S+)\s(\S+)\s(.*)<(.*)\>
FORMAT = violation::$1 src_ip::$2 session_id::$3 profile::$4 url::$5 msg::$6 action::$7

[ns_10_firewall_extract]
REGEX = APPFW\sAPPFW_(?<violation>\S+)\s(?<session_id>\d+)\s\d+\s:\s+(?<src_ip>\S+)\s+(\S+)\s+(?<uri_stem>\S+)\s+(?<profile>\S+)\s+(?<url>http\S+)\s+(?<msg>.+)\s\<(?<action>.*)\>
# Sample Event
# APPFW APPFW_FIELDCONSISTENCY 2537940 0 :  10.160.255.71 513618-PPE0 cCgPUNO2wqpqL1Qvux+ZWq1M1MIA000 AppFirewall_POL https://server.host.name/citrix/pnagent/enum.aspx Field consistency check failed for field "" <not blocked>

[ns_10_firewall_extract_CSRF]
REGEX = APPFW\sAPPFW_(?<violation>\S+)\s(?<session_id>\d+)\s\d+\s:\s+(?<src_ip>\S+)\s+(\S+)\s+(?<uri_stem>\S+)\s+(?<profile>\S+)\s(?<msg>.+)\s(?<url>http\S+)\s+<(?<action>.*)\>
# Sample Event
# APPFW APPFW_CSRF_TAG 2537939 0 :  10.160.255.71 513618-PPE0 cCgPUNO2wqpqL1Qvux+ZWq1M1MIA000 AppFirewall_POL CSRF Tag validation failed: https://server.host.name/citrix/pnagent/enum.aspx <not blocked>

[ns_uicmd_extract]
REGEX = (?i) CMD_EXECUTED.*User (?P<user>[^ ]+).*Remote_ip (?P<src_ip>[^ ]+).*Command "(?P<command>[^"]+)".*Status "(?P<status>[^"]+)"
FORMAT = user::$1 src_ip::$2 command::$3 status::$4

[ns_ssl_vpn_extract]
REGEX = Context\s(\S+)@(\S+).*Vserver\s(\S+).*Destination\s(\S+)
FORMAT = user::$1 src_ip::$2 vserver::$3 destination::$4

[ns_src_dst]
REGEX=(?i) Source (?P<src_ip>[^:]+):(?P<src_port>[^ ]+).*Destination (?P<dest_ip>[^:]+):(?P<dest_port>[^ ]+)
FORMAT= src_ip::$1 src_port::$2 dest_ip::$3 dest_port::$4

[ns_time]
REGEX=Start Time\s+(\S+)\s+\w+\s+-\s+End Time\s+(\S+)
FORMAT=start_time::$1 end_time::$2

[ns_bytes]
REGEX = Total_bytes_send\s(\S+)\s-\sTotal_bytes_recv\s(\S+)
FORMAT = total_bytes_send::$1 total_bytes_recv::$2

[url_path_split]
REGEX = httpRequestUrl|netscalerHttpReqUrl=\"(?<httpRequestUrlPath>[^\?\"]+)\??(?<httpRequestUrlQuery>[^\"]*)\"
#FORMAT = total_bytes_send::$1 total_bytes_recv::$2