# Copyright (C) 2019 NuHarbor Security. All Rights Reserved.
[1075_Alerts]
acceleration.earliest_time = -1mon
tags_whitelist = pci

[1075_Web]
acceleration.earliest_time = -1mon

[1075_Network_Sessions]
acceleration.earliest_time = -1mon

[1075_Application_State]
acceleration.earliest_time = -1mon

[1075_Authentication]
acceleration.earliest_time = -1mon

[1075_Change_Analysis]
acceleration.earliest_time = -1mon

[1075_Privilege_Escalation]
acceleration.earliest_time = -1mon

