[FSP_MappingLookup]
filename = FSP_Mapping.csv
disabled = 0

[LUN_MappingLookup]
filename = LUN_Mapping.csv
disabled = 0

[LUN_Client_mapping]
filename = LUN_Client_mapping.csv
disabled = 0

[TimeMarkLookup]
filename = TimeMark.csv
disabled = 0

[storyline_mapping]
case_sensitive_match = 1
filename = storyline_mapping.csv

[acm_alarm_mapping]
case_sensitive_match = 1
filename = acm_alarm_mapping.csv
