[aws:certificates]
KV_MODE=JSON
DATETIME_CONFIG = CURRENT
LINE_BREAKER = }(,[\s]+)
MAX_TIMESTAMP_LOOKAHEAD = 
NO_BINARY_CHECK = true
SEDCMD-remove-prefix = s/{\s+"ServerCertificateMetadataList":\s+\[//g
SEDCMD-remove-suffix = s/\s+\]\s+}//g
SEDCMD-xremove-newline= s/[\n\r]+|\s\s+//g
SHOULD_LINEMERGE = false
category = Structured
description = A variant of the JSON source type, with support for nonexistent timestamps
disabled = false
pulldown_type = true
