#
# Splunk app configuration file
#

[install]
is_configured = 0
build = 2

[ui]
is_visible = 1
label = Skurio

[launcher]
author = croesus
description = The Skurio App for Splunk brings open, deep and DarkWeb threat intelligence and data breaches into Splunk to help you improve incident response
version = 1.0.5

[package]
id=Skurio