[expose:TA_uk_open_data_settings]
pattern = TA_uk_open_data_settings
methods = POST, GET

[expose:TA_uk_open_data_settings_specified]
pattern = TA_uk_open_data_settings/*
methods = POST, GET, DELETE

[expose:TA_uk_open_data_carbon_intensity]
pattern = TA_uk_open_data_carbon_intensity
methods = POST, GET

[expose:TA_uk_open_data_carbon_intensity_specified]
pattern = TA_uk_open_data_carbon_intensity/*
methods = POST, GET, DELETE

[expose:TA_uk_open_data_nhs_ae]
pattern = TA_uk_open_data_nhs_ae
methods = POST, GET

[expose:TA_uk_open_data_nhs_ae_specified]
pattern = TA_uk_open_data_nhs_ae/*
methods = POST, GET, DELETE
