[admin:sn_sec_instance_es]
match = /event_ingestion_setup_es
members = myinstance_es, tokeninstance_es_primary, tokeninstance_es_secondary

[admin_external:myinstance_es]
handlertype = python
python.version = python3
handlerfile = sn_instance_es.py
handleractions = list, create

[admin_external:tokeninstance_es_primary]
handlertype = python
handlerfile = sn_instance_es_tokenprimary.py
handleractions = list
python.version = python3

[admin_external:tokeninstance_es_secondary]
handlertype = python
handlerfile = sn_instance_es_tokensecondary.py
handleractions = list
python.version = python3