[update_affected_devices_lookup]
cron_schedule = 30 */24 * * *
description = Update vuln id and device ids in affected devices lookup from the armis:vuln:match sourcetype.
dispatch.earliest_time = -24h
dispatch.latest_time = now
enableSched = 1
disabled = 1
realtime_schedule = 0
request.ui_dispatch_app = armis
request.ui_dispatch_view = search
search = `get_armis_index` sourcetype="armis:vuln:match" | dedup vuln_id | eval value=key | table vuln_id, deviceId{}, firstDetected{}, lastDetected{}, value | rename deviceId{} as deviceId, firstDetected{} as firstDetected, lastDetected{} as lastDetected | outputlookup affected_devices_lookup key_field=value