[expose:netskope]
pattern = data/inputs/netskope/*
methods = GET

[expose:netskope_core]
pattern = data/inputs/netskope
methods = GET

[expose:netskopewebtransactions]
pattern = data/inputs/netskope_webtransactions/*
methods = GET

[expose:netskope_webtransactions_core]
pattern = data/inputs/netskope_webtransactions
methods = GET

