[shake_json]

[shake]
EVAL-device = case(match(userAgent,"Android"),"Android",match(userAgent,"iPad"),"iPad",match(userAgent,"iPhone"),"iPhone",match(userAgent,"Mac"),"iPhone",match(userAgent,"Windows"),"Windows",userAgent=userAgent,"Other",match(ua,"Android"),"Android",match(ua,"iPad"),"iPad",match(ua,"iPhone"),"iPhone",match(ua,"Mac"),"iPhone",match(ua,"Windows"),"Windows",ua=ua,"Other")
