#Copyright (C) 2014 Kieren Crossland

[install]
is_configured = 0

[ui]
is_visible = 1
label = ITM6 App for Splunk

[package]
id = ITM6

[launcher]
author = Kieren Crossland
description = Indexes data from ITM6
version = 1.01

[triggers]
reload.java = access_endpoints /ITM6/tems