[insightappsec_apps]
start_by_shell = false
python.version = python3
sourcetype = rapid7:insightappsec:app
interval = 86400
api_endpoint = https://us.api.insight.rapid7.com

[insightappsec_findings]
start_by_shell = false
python.version = python3
sourcetype = rapid7:insightappsec:app:vulnerability_finding
interval = 86400
api_endpoint = https://us.api.insight.rapid7.com
vulnerability_status = ['VERIFIED', 'UNREVIEWED']

