
[expose:TA_trinity_cyber_settings]
pattern = TA_trinity_cyber_settings
methods = POST, GET

[expose:TA_trinity_cyber_settings_specified]
pattern = TA_trinity_cyber_settings/*
methods = POST, GET, DELETE

[expose:TA_trinity_cyber_trinity_cyber]
pattern = TA_trinity_cyber_trinity_cyber
methods = POST, GET

[expose:TA_trinity_cyber_trinity_cyber_specified]
pattern = TA_trinity_cyber_trinity_cyber/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
