[ipcalclookup]
python.version = python3
external_cmd = ipcalc_lookup.py Address Network Netmask Prefix Broadcast NetworkInt IPVer
fields_list = Address, Network, Netmask, Prefix, Broadcast, NetworkInt, IPVer

[decodehexstring]
python.version = python3
external_cmd = decodehexstring_lookup.py hexstring encoding decodedstring
fields_list = hexstring encoding decodedstring

[checkhexstringencoding]
python.version = python3
external_cmd = checkhexstringencoding_lookup.py hexstring encoding
fields_list = hexstring encoding
