[expose:TA_fints_settings]
pattern = TA_fints_settings
methods = POST, GET

[expose:TA_fints_settings_specified]
pattern = TA_fints_settings/*
methods = POST, GET, DELETE

[expose:TA_fints_fints_balance]
pattern = TA_fints_fints_balance
methods = POST, GET

[expose:TA_fints_fints_balance_specified]
pattern = TA_fints_fints_balance/*
methods = POST, GET, DELETE

[expose:TA_fints_fints_transaction]
pattern = TA_fints_fints_transaction
methods = POST, GET

[expose:TA_fints_fints_transaction_specified]
pattern = TA_fints_fints_transaction/*
methods = POST, GET, DELETE

[expose:TA_fints_fints_bankinformation]
pattern = TA_fints_fints_bankinformation
methods = POST, GET

[expose:TA_fints_fints_bankinformation_specified]
pattern = TA_fints_fints_bankinformation/*
methods = POST, GET, DELETE

[expose:TA_fints_fints_holding]
pattern = TA_fints_fints_holding
methods = POST, GET

[expose:TA_fints_fints_holding_specified]
pattern = TA_fints_fints_holding/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
