
#
# Splunk app configuration file
#

[install]
is_configured = 0


[ui]
is_visible = 1
label = AIShield AI Security Monitoring App for Splunk

[launcher]
author = AIShield
description = AIShield is a AI-security solution to protect AI Systems against emerging security threats. Protecting AI systems throughout their lifecycle and creating a trust for AI amongst consumers, organizations, and regulators is paramount with increasing adoption of AI to realize transforming impacts.AIShield AI Security Monitoring App for Splunk easily integrates with Splunk to increase the adoption and deliver an enhanced and real-time experience to security teams.AIShield.GuArdIan focuses on providing robust application security controls at both the input and output stages of LLM (Large Language Model) technology. AIShield.GuArdIan analyzes LLM-generated content to identify and mitigate harmful content, safeguarding against legal, policy, role-based, and usage-based violations. This comprehensive approach allows businesses to harness the full potential of ChatGPT-like AI while minimizing risks, thus promoting secure coding practices with generative AI.AIShield.GuArdIan analyzes the LLM generated content to identify and mitigate harmful content, safeguarding against legal, policy, role based, and usage based violations. This comprehensive approach allows businesses to harness the full potential of ChatGPT like AI while minimizing potential risks, thus promoting secure coding practices with generative AI.
version = 1.0.8

[package]
id = aishield
check_for_updates = true
