[script:search_similarity]
match = /search_similarity
script = search_similarity_handler.py
scripttype = persist
python.version = python3
handler = application.SearchSimilarity
python.required = 3.9, 3.13
