
## DO NOT DELETE THIS, EVEN IF YOU ARE DEPLOYING TO A SEARCH HEAD CLUSTER
## this is not a real input in that it will never input any data to any 
## index.  Instead this python scripts performs important first-time-run 
## and migration tasks when the app is first installed, and when it is 
## updated to a newer version.

[script://$SPLUNK_HOME/etc/apps/cisco_cdr/bin/app_setup/cisco_cdr_app_setup.py] 
# this interval tells Splunk to run this once at each restart.
interval = -1
passAuth = splunk-system-user
python.version = python3
