
[expose:TA_csam_add_on_reader_account]
pattern = TA_csam_add_on_reader_account
methods = POST, GET

[expose:TA_csam_add_on_reader_account_specified]
pattern = TA_csam_add_on_reader_account/*
methods = POST, GET, DELETE

[expose:TA_csam_add_on_reader_settings]
pattern = TA_csam_add_on_reader_settings
methods = POST, GET

[expose:TA_csam_add_on_reader_settings_specified]
pattern = TA_csam_add_on_reader_settings/*
methods = POST, GET, DELETE

[expose:TA_csam_add_on_reader_csam_input_infotypes]
pattern = TA_csam_add_on_reader_csam_input_infotypes
methods = POST, GET

[expose:TA_csam_add_on_reader_csam_input_infotypes_specified]
pattern = TA_csam_add_on_reader_csam_input_infotypes/*
methods = POST, GET, DELETE

[expose:TA_csam_add_on_reader_csam_input_system]
pattern = TA_csam_add_on_reader_csam_input_system
methods = POST, GET

[expose:TA_csam_add_on_reader_csam_input_system_specified]
pattern = TA_csam_add_on_reader_csam_input_system/*
methods = POST, GET, DELETE

[expose:TA_csam_add_on_reader_csam_input_reports]
pattern = TA_csam_add_on_reader_csam_input_reports
methods = POST, GET

[expose:TA_csam_add_on_reader_csam_input_reports_specified]
pattern = TA_csam_add_on_reader_csam_input_reports/*
methods = POST, GET, DELETE

[expose:TA_csam_add_on_reader_csam_input_poam_milestones]
pattern = TA_csam_add_on_reader_csam_input_poam_milestones
methods = POST, GET

[expose:TA_csam_add_on_reader_csam_input_poam_milestones_specified]
pattern = TA_csam_add_on_reader_csam_input_poam_milestones/*
methods = POST, GET, DELETE

[expose:TA_csam_add_on_reader_csam_input_component]
pattern = TA_csam_add_on_reader_csam_input_component
methods = POST, GET

[expose:TA_csam_add_on_reader_csam_input_component_specified]
pattern = TA_csam_add_on_reader_csam_input_component/*
methods = POST, GET, DELETE

[expose:TA_csam_add_on_reader_csam_input_poam]
pattern = TA_csam_add_on_reader_csam_input_poam
methods = POST, GET

[expose:TA_csam_add_on_reader_csam_input_poam_specified]
pattern = TA_csam_add_on_reader_csam_input_poam/*
methods = POST, GET, DELETE

[expose:TA_csam_add_on_reader_csam_input_all_poams]
pattern = TA_csam_add_on_reader_csam_input_all_poams
methods = POST, GET

[expose:TA_csam_add_on_reader_csam_input_all_poams_specified]
pattern = TA_csam_add_on_reader_csam_input_all_poams/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
