[te_event]
coldPath = $SPLUNK_DB/te_event/colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB/te_event/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/te_event/thaweddb

[te_flow]
coldPath = $SPLUNK_DB/te_flow/colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB/te_flow/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/te_flow/thaweddb

[te_mgmt]
coldPath = $SPLUNK_DB/te_mgmt/colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB/te_mgmt/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/te_mgmt/thaweddb

[te_threateye]
coldPath = $SPLUNK_DB/te_threateye/colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB/te_threateye/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/te_threateye/thaweddb
