[phantom_container]
TRUNCATE=100000

[phantom_artifact]
TRUNCATE=100000

[phantom_action_run]
TRUNCATE=100000

[phantom_app_run]
TRUNCATE=100000

[phantom_playbook]
TRUNCATE=100000

[phantom_custom_function]
TRUNCATE=100000

[phantom_decided_list]
TRUNCATE=100000

[phantom_container_comment]
TRUNCATE=100000

[phantom_container_attachment]
TRUNCATE=100000

[phantom_asset]
TRUNCATE=100000

[phantom_app]
TRUNCATE=100000

[phantom_docs]
TRUNCATE=100000

[phantom_container_note]
TRUNCATE=100000

[phantom_workflow_note]
TRUNCATE=100000

[phantom_note]
TRUNCATE=100000
