[waf_authentication]
search = (sourcetype=waf waf_tag=waf_log_login)

[waf_perf]
search = (sourcetype=waf waf_tag=waf_log_wafstat)

[waf_web]
search = (sourcetype=waf waf_tag=waf_log_webaccess) OR   (sourcetype=waf waf_tag=waf_log_websec)

[waf_ids]
search = (sourcetype=waf waf_tag=waf_log_l4acl) OR (sourcetype=waf waf_tag=waf_log_ddos) OR (sourcetype=waf waf_tag=waf_log_arp)
