[logging]
loglevel = INFO

[additional_parameters]

[push_settings]
webhook_enabled = 0
hec_token =
hec_token_name =
hec_url = https://localhost:8088/services/collector
sap_webhook_url = https://<SPLUNK_HOST>:8088/services/collector/raw?sourcetype=sapsb_push_json&index=sap
target_index = main
