# Base Macros
[blueshark]
definition = index=blueshark_index

[wbs_main]
definition = `blueshark` sourcetype="wbs_main"

[wbs_bcreportermain_v1]
definition = `blueshark` sourcetype="wbs_bcreportermain_v1"

