[admin:threatbook_ti]
match = /
members = threatbook_ti_settings

[admin_external:threatbook_ti_settings]
handlertype = python
python.version = python3
handlerfile = threatbook_ti_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[script:threatbook_ti_correlations]
match = /threatbook_ti_correlations
script = threatbook_ti_rest_handler.py
scripttype = persist
handler = threatbook_ti_rest_handler.ThreatBookHandler
requireAuthentication = true
output_modes = json
passPayload = true
passHttpHeaders = true
passHttpCookies = true
passSystemAuth = true
python.version = python3

[script:threatbook_ti_config]
match = /threatbook_ti_config
script = threatbook_ti_config_handler.py
scripttype = persist
handler = threatbook_ti_config_handler.ThreatBookConfigHandler
requireAuthentication = true
output_modes = json
passPayload = true
passHttpHeaders = true
passHttpCookies = true
passSystemAuth = true
python.version = python3
