
[cyberwatch_mock_auth]
search = sourcetype=cyberwatch:mock:json event_type=authentication

[cyberwatch_mock_ids]
search = sourcetype=cyberwatch:mock:json event_type=ids_attack

[cyberwatch_mock_malware]
search = sourcetype=cyberwatch:mock:json event_type=malware_attack

[cyberwatch_mock_traffic]
search = sourcetype=cyberwatch:mock:json event_type=network_traffic
