[vmware:workspaceone:audit]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
MAX_TIMESTAMP_LOOKAHEAD = 28
TIME_PREFIX = timestamp\":
TRUNCATE = 10000

[source::...ta-workspaceone*.log*]
SHOULD_LINEMERGE = true
sourcetype = taworkspaceone:log

[source::...ta_workspaceone*.log*]
SHOULD_LINEMERGE = true
sourcetype = taworkspaceone:log
