########################
# Base Macros
########################

[n2ws_di_index]
definition = index="default" sourcetype="n2ws:di"

[n2ws_alerts_index]
definition = index="default" sourcetype="n2ws:alerts"
