#
# Splunk app configuration file
#

[install]
state_change_requires_restart = true
is_configured = 0

[ui]
is_visible = 1
label = Akamai Guardicore App For Splunk

[launcher]
author = Akamai Technologies
description = The Guardicore App for Splunk includes dashboards that visually represent Guardicore data, showing network statistics, security incidents, and system health to provide insights into data center security. Guardicore is a cloud and data center security company that safeguards your core assets using flexible, quickly deployed, and easy-to-understand segmentation and micro-segmentation controls. Our solutions offer a simpler and faster way to ensure persistent and consistent security for any application, in any IT environment, including IaaS, PaaS, on-premises VMs, as well as legacy and old bare-metal servers.
version = 2.0.1

[package]
id = akamai_centra_app
check_for_updates = 1

[id]
name = akamai_centra_app
version = 2.0.1
