
[Absolute DDS Alerts]
action.email.useNSSubject = 1
alert.track = 0
display.events.fields = ["host","source","sourcetype","DDS_AlertCondition","DDS_AlertID","DDS_AlertName","DDS_AlertTime","DDS_Category","DDS_ComputerName","DDS_Identifier","DDS_SerialNumber"]
display.visualizations.show = 0
request.ui_dispatch_app = absolute_data_and_device_security_app
request.ui_dispatch_view = search
search = AbsoluteSIEMConnector
