######################################################
#
# deviceTRUST Device Based Licensing app
# 
######################################################

[install]
is_configured = 0
install_source_checksum = 5512c2992da6671a344683ae81a804382067e0d6

[ui]
is_visible = 1
label = deviceTRUST - Device Based Licensing

[launcher]
author = deviceTRUST
description = deviceTRUST - Device Based Licensing
version = 0.9.7

[package]
id = dt_devicebasedlicensing
