[eventtype=sophosxg_authentication]
authentication = enabled

[eventtype=sophosxg_firewall]
network = enabled
communicate = enabled

[eventtype=sophosxg_email_anti_virus]
email = enabled
malware = enabled
attack = enabled

[eventtype=sophosxg_http_anti_virus]
web = enabled
malware = enabled
attack = enabled

[eventtype=sophosxg_malware_detected]
malware = enabled
attack = enabled

[eventtype=sophosxg_definitions_upgraded]
malware = enabled
operations = enabled

[eventtype=sophosxg_system_health]
performance = enabled

[eventtype=sophosxg_system_health_cpu]
cpu = enabled

[eventtype=sophosxg_system_health_memory]
memory = enabled

[eventtype=sophosxg_system_health_disk]
storage = enabled

[eventtype=sophosxg_system_health_interface]
network = enabled

[eventtype=sophosxg_vpn]
network = enabled
session = enabled
vpn = enabled

[eventtype=sophosxg_web_content_policy]
web = enabled
proxy = enabled

[eventtype=sophosxg_web_filter]
web = enabled
proxy = enabled

[eventtype=sophosxg_ids]
ids = enabled
attack = enabled
vulnerability = enabled

[eventtype=sophosxg_change]
change = enabled

[eventtype=sophosxg_atp]
malware = enabled
attack = enabled

[eventtype=sophosxg_anti_spam]
malware = enabled
attack = enabled
email = enabled
filter = enabled

[eventtype=sophosxg_ssl]
certificate = enabled
ssl = enabled

[eventtype=sophosxg_sandbox]
malware = enabled

[eventtype=sophosxg_waf]
ids = enabled
attack = enabled
web = enabled
proxy = enabled

[eventtype=sophosxg_email]
email = enabled

[eventtype=sophosxg_web]
web = enabled

[eventtype=sophosxg_content_filtering]
web = enabled
proxy = enabled
