[extended_capturing_nested1_json]
FORMAT = $2::$3
MV_ADD = 1
REGEX = (\[\{\"columns\":\[\{)?\"([^=",]+)\":\s?\"?([^=",]*)
SOURCE_KEY = DIRECT_OBJECTS_ACCESSED

[extended_capturing_nested2_json]
FORMAT = $2::$3
MV_ADD = 1
REGEX = (\[\{\"columns\":\[\{)?\"([^=",]+)\":\s?\"?([^=",]*)
SOURCE_KEY = OBJECTS_MODIFIED

[extended_capturing_nested3_json]
FORMAT = $1::$2
MV_ADD = 1
REGEX = \{?\"([^=",]+)\":\s?\"?([^=",]*)
SOURCE_KEY = CLIENT_ENVIRONMENT

[extended_dbx_snowflake_unstructured]
CLEAN_KEYS = 0
FORMAT = $1::$2
REGEX = "?(\w+)"\:\s["|]?([^"|\}|\"\]\"]+[^\s\"\,\}])["|\}|\]|\[\{]?