[default]

[install]
is_configured = 0
install_source_checksum = b5ea6bafe40c6fbe40e2ccbf8d8d467a4b38a5de

[launcher]
description = This Splunk app is developed to ingest HP printer logs in real-time and monitor, detect and report critical security events through log analysis.
version = 1.0
author = Nanyang Polytechnic 

[ui]
is_visible = 1
label = HP Printer Security

[package]
check_for_updates = 1
id = printersec
