[deconz_sensors]
start_by_shell = false
python.version = python3
sourcetype = deconz:sensors
interval = 30
disabled = 0

[deconz_sensors://deCONZ_Sensors]
interval = 30
index = deconz
api_key = ********
deconz_url = http://172.19.0.4:80
disabled = 0

