[hyasprotectendpoint-command]
syntax = hyasprotectendpoint type="" value=""
description = Runs a HYAS protect against the given IOC Value and will return the latest results.
shortdesc = Return Hyas Verdict for given IOC value. Supported indicator type's are Ip, Domain, Fqdn and Nameserver.
example1 = | hyasprotectendpoint type="ip" value="103.14.120.241"
usage = public

[hyasprotectverdictfordomain-command]
syntax = hyasprotectverdictfordomain value=""
description = Runs a HYAS protect against the given domain Value and will return the latest results.
shortdesc = Return Hyas Verdict for given domain value.
example1 = | hyasprotectverdictfordomain value="himionsa.com"
usage = public

[hyasprotectverdictforip-command]
syntax = hyasprotectverdictforip value=""
description = Runs a HYAS protect against the given ip address Value and will return the latest results.
shortdesc = Return Hyas Verdict for given ip address value.
example1 = | hyasprotectverdictforip value="4.4.4.4"
usage = public

[hyasprotectverdictfornameserver-command]
syntax = hyasprotectverdictfornameserver value=""
description = Runs a HYAS protect against the given nameserver Value and will return the latest results.
shortdesc = Return Hyas Verdict for given nameserver value.
example1 = | hyasprotectverdictfornameserver value="ns2.duckdns.org"
usage = public

[hyasprotectverdictforfqdn-command]
syntax = hyasprotectverdictforfqdn value=""
description = Runs a HYAS protect against the given fqdn Value and will return the latest results.
shortdesc = Return Hyas Verdict for given fqdn value.
example1 = | hyasprotectverdictforfqdn value="www.fishfarm.duckdns.org"
usage = public