#
# Splunk app configuration file
#
[package]
id = csv-api-handler



[ui]
is_visible = 1
label = CSV Lookup API Example

[launcher]
author = Manoj Jangid
description = Convert CSV lookup files into REST API
version = 1.0.0

