[expose:confluence_and_jira_audit_addon_for_splunk_account]
pattern = confluence_and_jira_audit_addon_for_splunk_account
methods = POST, GET

[expose:confluence_and_jira_audit_addon_for_splunk_account_specified]
pattern = confluence_and_jira_audit_addon_for_splunk_account/*
methods = POST, GET, DELETE

[expose:confluence_and_jira_audit_addon_for_splunk_settings]
pattern = confluence_and_jira_audit_addon_for_splunk_settings
methods = POST, GET

[expose:confluence_and_jira_audit_addon_for_splunk_settings_specified]
pattern = confluence_and_jira_audit_addon_for_splunk_settings/*
methods = POST, GET, DELETE

[expose:confluence_and_jira_audit_addon_for_splunk_jira]
pattern = confluence_and_jira_audit_addon_for_splunk_jira
methods = POST, GET

[expose:confluence_and_jira_audit_addon_for_splunk_jira_specified]
pattern = confluence_and_jira_audit_addon_for_splunk_jira/*
methods = POST, GET, DELETE

[expose:confluence_and_jira_audit_addon_for_splunk_confluence]
pattern = confluence_and_jira_audit_addon_for_splunk_confluence
methods = POST, GET

[expose:confluence_and_jira_audit_addon_for_splunk_confluence_specified]
pattern = confluence_and_jira_audit_addon_for_splunk_confluence/*
methods = POST, GET, DELETE
