[proofpoint_tap_siem]
TIME_PREFIX = "eventTime":\s+"
NO_BINARY_CHECK = true
pulldown_type = 1
SHOULD_LINEMERGE = false
TRUNCATE = 9999999
KV_MODE = json
category = Network & Security
description = Proofpoint TAP SIEM Source Type
TZ = Etc/UTC
disabled = false
FIELDALIAS-src = senderIP as src
FIELDALIAS-src_user = sender as src_user
FIELDALIAS-size = messageSize as size
FIELDALIAS-message_id = messageID as message_id
FIELDALIAS-file_name = messageParts{}.filename as file_name
FIELDALIAS-recpt = recipient{} as recpt
EVAL-src_user_domain = mvindex(split(sender, "@"), 1)
EVAL-recipient_count = case(isnotnull(recipient), mvcount(recipient), isnotnull(recpt), mvcount(recpt))
EVAL-vendor_product = "Proofpoint TAP"

[source::...ta-proofpoint_tap*.log*]
SHOULD_LINEMERGE = true
sourcetype = taproofpointtap:log

[source::...ta_proofpoint_tap*.log*]
SHOULD_LINEMERGE = true
sourcetype = taproofpointtap:log