[script://$SPLUNK_HOME/etc/apps/akamai_mfa/bin/auths.py]
disabled = 1
host = Akamai_Mfa_Host
interval = 30
source = akamai_mfa
sourcetype = akamai_mfa_auths
index = akamai_mfa
python.version = python3
python.required = 3.13

[script://$SPLUNK_HOME/etc/apps/akamai_mfa/bin/session_history.py]
disabled = 1
host = Akamai_Mfa_Host
interval = 30
source = akamai_mfa
sourcetype = akamai_mfa_session_history
index = akamai_mfa
python.version = python3
python.required = 3.13

[script://$SPLUNK_HOME/etc/apps/akamai_mfa/bin/resource.py]
disabled = 1
host = Akamai_Mfa_Host
interval = 30
source = akamai_mfa
sourcetype = akamai_mfa_resource_action
index = akamai_mfa
python.version = python3
python.required = 3.13
