[win:systeminfo]
DATETIME_CONFIG = CURRENT
description = Output of the SystemInfo command on Windows
disabled = false
INDEXED_EXTRACTIONS = csv
KV_MODE = none
NO_BINARY_CHECK = true
pulldown_type = true
SHOULD_LINEMERGE = false
