
[oracle_sbc_cdr]
SHOULD_LINEMERGE = False
TIME_FORMAT = %H:%M:%S.%3Q %Z %b %e %Y
MAX_TIMESTAMP_LOOKAHEAD = 400
BREAK_ONLY_BEFORE_DATE = False
TRANSFORMS-sourcetypeRenamesAndCallID = oracle_cdr_call_id, oracle_cdr_match_start, oracle_cdr_match_end, oracle_cdr_match_interim, oracle_cdr_match_header_row
ANNOTATE_PUNCT = false
initCrcLength = 400

[oracle_cdr_start]
SHOULD_LINEMERGE = False
TIME_FORMAT = %H:%M:%S.%3Q %Z %b %e %Y
MAX_TIMESTAMP_LOOKAHEAD = 400
BREAK_ONLY_BEFORE_DATE = False
initCrcLength = 400

[oracle_cdr_interim]
SHOULD_LINEMERGE = False
TIME_FORMAT = %H:%M:%S.%3Q %Z %b %e %Y
MAX_TIMESTAMP_LOOKAHEAD = 400
BREAK_ONLY_BEFORE_DATE = False
initCrcLength = 400

[oracle_cdr_end]
SHOULD_LINEMERGE = False
TIME_FORMAT = %H:%M:%S.%3Q %Z %b %e %Y
MAX_TIMESTAMP_LOOKAHEAD = 400
BREAK_ONLY_BEFORE_DATE = False
initCrcLength = 400
