[alsid:syslog]
description = Output produced by Alsid for AD
category = Network & Security
MAX_TIMESTAMP_LOOKAHEAD = 32
TIME_FORMAT = %b %d %H:%M:%S
SHOULD_LINEMERGE = 0
pulldown_type = 1
# Fields : 
KV_MODE = none
TRANSFORMS = syslog-host
## Transformations
REPORT-alsid_insertion_string_kv = alsid_insertion_string_kv
REPORT-alsid_ad_object_kv = alsid_ad_object_kv
## Extractions
EXTRACT-alsid_security_alert = ^[^"\n]*\d+:\d+:\d+\s(?<src>.*)\s(?P<app>[a-zA-Z0-9_.]+)\[\d+\]:\s"(?P<alsid_internal_mtype>0)"\s"(?P<alsid_alert_id>\d+)"\s"(?P<ad_forest_name>[^"]+)"\s"(?P<ad_domain_name>[^"]+)"\s"(?P<alsid_code_name>[^"]+)"\s"(?!\d+")(?P<alsid_severity_level>[^"]+)"\s"(?P<ad_object>.*?)"\s"(?P<alsid_deviance_id>[^"]+)"\s"(?P<alsid_profile_id>[^"]+)"\s"(?P<alsid_reason>[^"]+)"\s"(?P<alsid_event_id>[^"]+)"\s(?P<alsid_insertion_strings>".*?")$
EXTRACT-alsid_traiflow_event = ^[^"\n]*\d+:\d+:\d+\s(?<src>.*)\s(?P<app>[a-zA-Z0-9_.]+)\[\d+\]:\s"(?P<alsid_internal_mtype>1)"\s"(?P<alsid_alert_id>\d+)"\s"(?P<ad_forest_name>[^"]+)"\s"(?P<ad_domain_name>[^"]+)"\s"(?P<ad_object>[^"]+)"\s"(?P<alsid_event_id>[^"]+)"\s"(?P<alsid_event_type>[^"]*?)"\s(?P<alsid_insertion_strings>"?\S*?"?=""?.*?"?"?)$
EXTRACT-alsid_security_attack = ^[^"\n]*\d+:\d+:\d+\s(?<src>.*)\s(?P<app>[a-zA-Z0-9_.]+)\[\d+\]:\s"(?P<alsid_internal_mtype>2)"\s"(?P<alsid_alert_id>\d+)"\s"(?P<ad_forest_name>[^"]+)"\s"(?P<ad_domain_name>[^"]+)"\s"(?P<alsid_attack_name>[^"]+)"\s"(?!\d+")(?P<alsid_severity_level>[^"]+)"\s"(?P<source_name>.*?)"\s"(?P<source_ip>[^"]+)"\s"(?P<destination_name>[^"]+)"\s"(?P<destination_ip>[^"]+)"\s(?P<alsid_insertion_strings>".*?")$
## Aliases
FIELDALIAS-alsid_alias_body = alsid_insertion_strings ASNEW body
FIELDALIAS-alsid_alias_subject = alsid_reason ASNEW subject alsid_event_type ASNEW subject
## Eval
EVAL-severity = if(alsid_internal_mtype==1, "informational", alsid_severity_level)
### alsid_severity_level is only used to extract information from logs
EVAL-severity_id = case(alsid_internal_mtype==1, 0, alsid_severity_level=="low", 1, alsid_severity_level=="medium", 2, alsid_severity_level=="high", 3, alsid_severity_level=="critical", 4)
EVAL-type = case(alsid_internal_mtype==0, "alert",alsid_internal_mtype==2, "alert", alsid_internal_mtype==1, "event")
## Lookups
LOOKUP-ALSID-INTERNAL-MTYPE = lookup_alsid_internal_mtype alsid_internal_mtype OUTPUT alsid_message_type