
[expose:TA_qualibooth_account]
pattern = TA_qualibooth_account
methods = POST, GET

[expose:TA_qualibooth_account_specified]
pattern = TA_qualibooth_account/*
methods = POST, GET, DELETE

[expose:TA_qualibooth_settings]
pattern = TA_qualibooth_settings
methods = POST, GET

[expose:TA_qualibooth_settings_specified]
pattern = TA_qualibooth_settings/*
methods = POST, GET, DELETE

[expose:TA_qualibooth_accessibility_errors]
pattern = TA_qualibooth_accessibility_errors
methods = POST, GET

[expose:TA_qualibooth_accessibility_errors_specified]
pattern = TA_qualibooth_accessibility_errors/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
