[expose:spiderSilk_resonance_api_key]
pattern = spiderSilk_resonance_api_key
methods = POST, GET

[expose:spiderSilk_resonance_api_key_specified]
pattern = spiderSilk_resonance_api_key/*
methods = POST, GET, DELETE

[expose:spiderSilk_resonance_settings]
pattern = spiderSilk_resonance_settings
methods = POST, GET

[expose:spiderSilk_resonance_settings_specified]
pattern = spiderSilk_resonance_settings/*
methods = POST, GET, DELETE

[expose:spiderSilk_resonance_spiderSilk_resonance]
pattern = spiderSilk_resonance_spiderSilk_resonance
methods = POST, GET

[expose:spiderSilk_resonance_spiderSilk_resonance_specified]
pattern = spiderSilk_resonance_spiderSilk_resonance/*
methods = POST, GET, DELETE
