[logging]
loglevel = INFO

[additional_parameters]
etp_service_region = 
fireeye_api_key = 
ssl_verify = 

[proxy]
proxy_enabled = 
proxy_type = http
proxy_url = 
proxy_port = 
proxy_username = 
proxy_password = 
proxy_rdns = 
