#
# Splunk app configuration file
#

[ui]
is_visible = 0
label = HTTP GET


[launcher]
author = Nimish Doshi
version=1.2
description = httpget command returns realtime http get info for URL field(s)

[package]
id=httpget_command



