[launcher]
version = 1.2.1
description = Spex Add-on for Microsoft M365 Automation
author = Mario Almeida

[id]
version = 1.2.1
name = spex_add_on_for_microsoft_m365_automation

[install]
build = 1748184940
is_configured = false
state = enabled

[package]
id = spex_add_on_for_microsoft_m365_automation
check_for_updates = true

[ui]
label = Spex Add-on for Microsoft M365 Automation
supported_themes = light, dark
is_visible = true

[triggers]
reload.spex_add_on_for_microsoft_m365_automation_settings = simple
reload.spex_add_on_for_microsoft_m365_automation_account = simple
reload.spex_add_on_for_microsoft_m365_automation_appreg = simple
