[linkshadow_network]
search = sourcetype=linkshadow_ndr_cef

[linkshadow_ids]
search = sourcetype=linkshadow_ndr_cef signature_id=*

[linkshadow_web]
search = sourcetype=linkshadow_ndr_cef requestMethod=*
