[teamcymrumatchindicators-command]
syntax =  teamcymrumatchindicators indicator_type="Value of indicator type"
description = This command performs the correlation between Team Cymru indicator and provided Splunk events.
shortdesc = Correlate team cymru indicators against provided Splunk events.
example1 = | teamcymrumatchindicators indicator_type="domain"
comment1 = Correlate team cymru indicators of type "domain" against provided Splunk events with respected team_cymru_indicators_lookup.

[teamcymruaccountusage-command]
syntax =  teamcymruaccountusage 
description = This command shows the performaance of the queries.
shortdesc = Provide the details of the queries .
example1 = | accountusage | table *
comment1 = shows the table of all the queies related events.

[teamcymruscoutsearch-command]
syntax =  teamcymruscoutsearch
description = This command shows the performaance of the queries.
shortdesc = Provide the details of the queries .
example1 = | teamcymruscoutsearch | table *
comment1 = shows the table of all the queies related events.
example2 = | teamcymruscoutsearch start_date="2025-01-01" end_date="2025-01-05" | table *
comment2 = shows the table of all the queies related events with provided start date and end date.

[teamcymruscoutsectionsearch-command]
syntax =  teamcymruscoutsectionsearch
description = This command shows the performaance of the queries.
shortdesc = Provide the details of the queries .
example1 = | teamcymruscoutsectionsearch | table *
comment1 = shows the table of all the queies related events.
example2 = | teamcymruscoutsectionsearch start_date="2025-01-01" end_date="2025-01-05" | table *
comment2 = shows the table of all the queies related events with provided start date and end date.