# Splunk app configuration file

[ui]
label = LookingGlass Cyber Scout Data Query
is_visible = 1

[launcher]
description = An integration with the LookingGlass Cyber Scout platform to run a generic query and return data via the API.
author = Paul Stark (pstark@lookingglasscyber.com)
version = 1.0.7

[package]
id = Splunk_TA_lookingglasscyber_scout_query

[install]
is_configured = 0
