# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 1

[launcher]
author = Nutanix Inc
version = 1.0.0
description = Nutanix Flow Security Central helps you keep your hybrid cloud safe across Amazon Web Services, Microsoft Azure and Nutanix Private Cloud. Identify and fix security issues in real-time. Automate compliance checks for cloud operations using 550+ audits. Get compliance checks for regulatory policies such as HIPAA, PCI-DSS, NIST, and more.This add-on helps you integrate your Splunk install with your Beam account. It will bring all the Beam logs related to vulnerabilities detected and issue state changes to your Splunk install.

[ui]
is_visible = 1
label = Nutanix Flow Security Central Integration
docs_section_override = AddOns:released

[package]
id = Nutanix-flow-security-central-integration

[triggers]
reload.addon_builder = simple
reload.nutanix_flow_security_central_integration_account = simple
reload.nutanix_flow_security_central_integration_settings = simple
reload.passwords = simple