[ArcticaHeartbeat]
search = `ArcticaIndex` sourcetype="Arctica::HomeOffice::Heartbeat"

[ArcticaUserKeyboardMouseActivity]
color = et_blue
search = `ArcticaIndex` sourcetype="Arctica::HomeOffice::UserKeyboardMouseActivity"

[ArcticaUserActivity]
color = et_green
search = `ArcticaIndex` sourcetype="Arctica::HomeOffice::UserActivity"
