[id]
name = SA_oracle_sbc_cdr
version = 0.8.4
#splunkbase_id = 7051

[ui]
is_visible = 1
label = Supporting App for Oracle SBC CDR
supported_themes = light, dark

[launcher]
author = Sideview, LLC
description = This is a Supporting app designed to be deployed alongside Sideview's commercial "Cisco CDR Reporting and Analytics" app.  Additionally it contains various pieces of Splunk configuration and logic that are used by Cisco CDR Reporting and Analytics, to make the Oracle SBC CDR work within its user interfaces. NOTE: To ingest the data correctly yuo will also need to deploy the TA_oracle_sbc_cdr app. See that app for further details.
version = 0.8.4

[package]
id = SA_oracle_sbc_cdr

[install]
build = 36

[shclustering]
deployer_lookups_push_mode = always_preserve

[triggers]
reload.sideview_data_types = access_endpoints /admin/conf-sideview_data_types
