#Copyright (C) 2014 Kieren Crossland

#####
# Defaults
#####
[itm6_sql_input]
timeout = 30
interval = 300
index = itm

[itm6_obj_input]
interval = 300

[itm6_dash_input]
interval = 300
properties = all

[itm6_daily_health_check]
interval = 0 2 * * *
sourcetype = itm6_daily_health

[tcp://9998]
connection_host = dns
index = itm
source = itm6_eif
sourcetype = itm6_eif
