[source::...ta-zero-networks-add-on-for-splunk*.log*]
sourcetype = tazeronetworksaddonforsplunk:log

[source::...ta_zero_networks_add_on_for_splunk*.log*]
sourcetype = tazeronetworksaddonforsplunk:log

[ZNAudit]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

