[intsights_ipaddresses]
collection = intsights_ipaddresses
external_type = kvstore
fields_list = confidence,first_seen,first_seen_epoch,id,last_seen,last_seen_epoch,severity,source_id,source_name,source_severity,type,value,_key

[intsights_urls]
collection = intsights_urls
external_type = kvstore
fields_list = confidence,first_seen,first_seen_epoch,id,last_seen,last_seen_epoch,severity,source_id,source_name,source_severity,type,value,_key

[intsights_domains]
collection = intsights_domains
external_type = kvstore
fields_list = confidence,first_seen,first_seen_epoch,id,last_seen,last_seen_epoch,severity,source_id,source_name,source_severity,type,value,_key

[intsights_hashes]
collection = intsights_hashes
external_type = kvstore
fields_list = confidence,first_seen,first_seen_epoch,id,last_seen,last_seen_epoch,severity,source_id,source_name,source_severity,type,value,_key

[intsights_emails]
collection = intsights_emails
external_type = kvstore
fields_list = confidence,first_seen,first_seen_epoch,id,last_seen,last_seen_epoch,severity,source_id,source_name,source_severity,type,value,_key
