[splexamples-savedsearch-myquery]
action.email.useNSSubject = 1
alert.track = 0
dispatch.earliest_time = -15m
dispatch.latest_time = now
dispatchAs = user
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.charting.chart = line
display.visualizations.show = 0
display.visualizations.type = mapping
request.ui_dispatch_app = spl_examples
request.ui_dispatch_view = search
search = index=splexamples | head 1 | eval message="My serach result for $replace_me$" | table message

[splexamples-savedsearch-commands]
action.email.useNSSubject = 1
alert.track = 0
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
request.ui_dispatch_app = spl_examples
request.ui_dispatch_view = search
search = | inputlookup cmdlookup

[splexamples-savedsearch-mysecurityquery]
action.email.useNSSubject = 1
alert.track = 0
dispatch.earliest_time = -15m
dispatch.latest_time = now
dispatchAs = user
display.visualizations.charting.chart = line
display.visualizations.show = 0
display.visualizations.type = mapping
request.ui_dispatch_app = spl_examples
request.ui_dispatch_view = search
search = index="splexamples" sourcetype="secure" "Failed password"

[splexamples saved search message]
action.email.useNSSubject = 1
alert.track = 0
dispatch.earliest_time = -15m
dispatch.latest_time = now
dispatchAs = user
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.charting.chart = line
display.visualizations.show = 0
display.visualizations.type = mapping
request.ui_dispatch_app = spl_examples
request.ui_dispatch_view = search
search = index=splexamples | head 1 | eval message="This is the output from a saved search" | table message
