[shclustering]
conf_replication_include.ta_dell_ecs_account.conf = true
conf_replication_include.ta_dell_ecs_settings.conf = true
conf_replication_include.endpoint.conf = true
conf_replication_include.dependent_endpoint.conf = true