##################################################
# Recorded Future Event types needed for Splunk ES
##################################################


# Needed to activate workflows while reviewing incidents.
[rf_notable]
priority = 1
search = index=notable threat_group="rf_threatlist"
