

[expose:vmware_cbc_test_connection]
methods = POST
pattern = vmware_cbc_test_conn

[expose:vmware-cbc-alerts_reload]
pattern = data/inputs/vmware-cbc-alerts/*/_reload
methods = GET, POST

[expose:vmware-cbc-alerts]
pattern = data/inputs/vmware-cbc-alerts/*
methods = GET

[expose:vmware-cbc-alerts_mi]
pattern = data/inputs/vmware-cbc-alerts
methods = GET

[expose:vmware-cbc-assets_reload]
pattern = data/inputs/vmware-cbc-assets/*/_reload
methods = GET, POST

[expose:vmware-cbc-assets]
pattern = data/inputs/vmware-cbc-assets/*
methods = GET

[expose:vmware-cbc-assets_mi]
pattern = data/inputs/vmware-cbc-assets
methods = GET

[expose:vmware-cbc-audit_reload]
pattern = data/inputs/vmware-cbc-audit/*/_reload
methods = GET, POST

[expose:vmware-cbc-audit]
pattern = data/inputs/vmware-cbc-audit/*
methods = GET

[expose:vmware-cbc-audit_mi]
pattern = data/inputs/vmware-cbc-audit
methods = GET

[expose:vmware-cbc-live-query_reload]
pattern = data/inputs/vmware-cbc-live-query/*/_reload
methods = GET, POST

[expose:vmware-cbc-live-query]
pattern = data/inputs/vmware-cbc-live-query/*
methods = GET

[expose:vmware-cbc-live-query_mi]
pattern = data/inputs/vmware-cbc-live-query
methods = GET

[expose:vmware-cbc-vuln_reload]
pattern = data/inputs/vmware-cbc-vuln/*/_reload
methods = GET, POST

[expose:vmware-cbc-vuln]
pattern = data/inputs/vmware-cbc-vuln/*
methods = GET

[expose:vmware-cbc-vuln_mi]
pattern = data/inputs/vmware-cbc-vuln
methods = GET, POST

[expose:vmware-cbc-authentication-events]
pattern = data/inputs/vmware-cbc-authentication-events/*
methods = GET

[expose:vmware-cbc-authentication-events_mi]
pattern = data/inputs/vmware-cbc-authentication-events
methods = GET, POST