[credential:__REST_CREDENTIAL__#TA-fastly-waf#configs/conf-ta_fastly_waf_settings:additional_parameters``splunk_cred_sep``1:]
password = $7$OaAGI5GTTOjGR7RUvWIHzAGrsoUNj5EFr/UWvsbqbMK5sRF8PYQGxBX/Abjc0svw1nwHQCw3aICtzfNKDOnUF3AUJha714FudIuW+5p9gw7E7zVctQ==

[credential:__REST_CREDENTIAL__#TA-fastly-waf#configs/conf-ta_fastly_waf_settings:additional_parameters``splunk_cred_sep``2:]
password = $7$VK1zOJHsYh8Y/cJBAm5+FCweIMgXOn1EvhFkvOFqn2tlYj8p+yqs2cUfFMPeJDw2krUR6QHIrRarguifqGpM+4sG5f2/KPryIRZBlP0Hjk2P/rQKH7Xm7u0P75diSa6JA10Gg7ajmRzsnkw/tvgf94QdvSGZ3uG/jOmwvPlDC8ck+wRGiceoNSMviE7wdLLYIWe+i/7Yw06RTl/i7WMvxrTI1zttRiWxEFkO
