
[admin:TA_banyan_events]
match = /
members = TA_banyan_events_settings, TA_banyan_events_banyan_events

[admin_external:TA_banyan_events_settings]
handlertype = python
python.version = python3
handlerfile = TA_banyan_events_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_banyan_events_banyan_events]
handlertype = python
python.version = python3
handlerfile = TA_banyan_events_rh_banyan_events.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
