[install]
state = enabled
is_configured = 0

[ui]
is_visible = false
label = Vercel Add-on

[id]
name = splunk_ta_vercel
version = 1.0.0

[launcher]
author = Sanjeev
version = 1.0.0
description = TA for Vercel Drains (Logs, Speed Insights, Web Analytics).

[package]
id = splunk_ta_vercel
version = 1.0.0
check_for_updates = true
