[vercel_set_sourcetype]
REGEX = \"(?:type|drainType|drain)\"\\s*:\\s*\"(logs|speed_insights|web_analytics)\"
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::vercel:$1

[vercel_schema_speed_insights]
REGEX = \"schema\"\\s*:\\s*\"vercel\\.speed_insights\\.v1\"
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::vercel:speed_insights

[vercel_schema_web_analytics]
REGEX = \"schema\"\\s*:\\s*\"vercel\\.analytics\\.v1\"
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::vercel:web_analytics
