
[admin:TA_alert_to_mqtt]
match = /
members = TA_alert_to_mqtt_settings

[admin_external:TA_alert_to_mqtt_settings]
handlertype = python
python.version = python3
handlerfile = TA_alert_to_mqtt_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

