# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = true
is_configured = 0
state = enabled
build = 2

[launcher]
author = Leonardo Armesto
version = 1.0.0
description = LibreNMS is an autodiscovering PHP/MySQL/SNMP based network monitoring tool which includes support for a wide range of network hardware and operating systems.

[ui]
is_visible = 1
label = LibreNMS Data Poller
docs_section_override = AddOns:released

[package]
id = TA-librenms-data-poller

[triggers]
reload.addon_builder = simple
reload.ta_librenms_data_poller_account = simple
reload.ta_librenms_data_poller_settings = simple
reload.passwords = simple

