[eventtype=ccx_imperva_waf_alerts]
alert = enabled

[eventtype=ccx_imperva_waf_web]
web = enabled

[eventtype=ccx_imperva_waf_firewall]
communicate = enabled
network = enabled

[eventtype=ccx_imperva_waf_ids]
attack = enabled
ids = enabled
