[CM_collections_changes]

[CM_commands_changes]

[CM_dashboards_changes]

[CM_datamodels_changes]

[CM_eventtypes_changes]

[CM_IR_fields_changes]

[CM_lookup_files_changes]

[CM_macros_changes]

[CM_menus_changes]

[CM_panels_changes]

[CM_props_changes]

[CM_saved_searches_changes]

[CM_tags_changes]

[CM_transforms_changes]

[CM_workflow_actions_changes]
