[hyasinsightpassivedns]
filename = passive.py
chunked = true
python.version = python3

[hyasinsightdynamicdns]
filename = dynamic.py
chunked = true
python.version = python3

[hyasinsightdevice]
filename = device.py
chunked = true
python.version = python3

[hyasinsightwhois]
filename = whois.py
chunked = true
python.version = python3

[hyasinsightwhoiscurrent]
filename = whoiscurrent.py
chunked = true
python.version = python3

[hyasinsightpassivehash]
filename = passivehash.py
chunked = true
python.version = python3

[hyasinsightsinkhole]
filename = sink.py
chunked = true
python.version = python3

[hyasinsightsslcertificate]
filename = hyas_ssl.py
chunked = true
python.version = python3

[hyasinsightc2attribution]
filename = cattribuition.py
chunked = true
python.version = python3

[hyasinsightvalidation]
filename = validation_command.py
chunked = true
python.version = python3

[hyasinsightproxyvalidation]
filename = proxy_validation.py
chunked = true
python.version = python3

[hyasinsightmalwareinformation]
filename = sample_information.py
chunked = true
python.version = python3

[hyasinsightmalwarerecord]
filename = sample.py
chunked = true
python.version = python3

[hyasinsightosindicatorrecord]
filename = os_indicator.py
chunked = true
python.version = python3