[runchecks]
filename = runchecks.py
chunked = true
python.version = python3
python.required = 3.9
enableheader = true
requires_srinfo = true
local = false

[cronstring]
filename = cronstring.py
python.version = python3
python.required = 3.9
passauth = true
retainsevents = true
supports_multivalues = true

[cronminutes]
filename = cronminutes.py
python.version = python3
python.required = 3.9
passauth = true
retainsevents = true
supports_multivalues = true