[runchecks-command]
syntax       = runchecks (searches=<comma-delimited-string>) (tokens=<comma-delimited-string of k=v pairs>)? (max_time=<int>)?  (timeout=<int>)? 
shortdesc    = Run a list of Saved Searches in sequence. 
description  = Run a list of Saved Searches in sequence, letting each complete before starting the next. This command keeps a log of the statuses of its queued searches in the "queued_searches" KVStore collection lookup as it runs. When all searches have completed, this command outputs a JSON event with info on the parent and queued searches. The results of the queued searches are not returned or stored; use SPL to perform these operations as desired within the Saved Search itself. \
Each queued search receives the "$parent_sid$" token which contains the SID of the parent search. To use base and post-process searches, start your post process search with the "queued_search_base" macro, i.e. "| `queued_search_base($parent_sid$, ''My Base Saved Search'')`"
example1     = | runchecks max_time=10 timeout=600 searches="My First Saved Search, My Second Saved Search"
comment2     = Order post-process searches after their base searches:
example2     = | runchecks searches="My Base Saved Search, My First Post Saved Search, My Second Post Saved Search"
comment3     = Optionally, supply tokens for a given Saved Search in a pipe-delimited list within angled brackets after the search name:
example3     = | runchecks searches="My Token Dependant Saved Search<tok1=hello|tok2=world>, My Normal Saved Search"
category     = search
related      = search, savedsearch, loadjob, map
maintainer   = Presidio
usage        = public