[install]
state_change_requires_restart = true
is_configured = false
state = enabled
build = 1680041454
install_source_checksum = 783bb6635696408227f90eb6a1daa995321bb8a6

[launcher]
author = William Searle
version = 1.2.0R8a3badf
description = Import information about your AWS Organization child accounts

[ui]
is_visible = 1
label = AWS Organization Helper
docs_section_override = AddOns:released

[package]
id = TA-aws-organization-helper

[triggers]
reload.ta_aws_organization_helper_account = simple
reload.ta_aws_organization_helper_settings = simple
reload.passwords = simple

[id]
version = 1.2.0R8a3badf

