[proxy]

[logging]

[additional_parameters]
base_event_type = index=main
messages_outstanding = 1000
bytes_outstanding = 15 * 1024 * 1024
thread_count = 5
merged_filesize_limit = 10 * 1024 * 1024
close_file_in_seconds = 30

[email_notification]

[scripted_input_parameters]
account_name = 
type = connection~application
start_datetime = 
user_end_datetime = 
data_collection_window = 60
index = 
max_active_inputs = 5

[csv_input]
custom_path_enabled = 0
custom_path = 
