[pictorial-chart-viz]
label = Pictorial Chart Viz
description = Visualize how metrics compare with each other in an infometric style pictorial chart
search_fragment =... | stats count by category
allow_user_selection = true
disabled = 0
supports_trellis = false
supports_drilldown = false
