
[expose:TA_splunk_cloud_app_exporter_settings]
pattern = TA_splunk_cloud_app_exporter_settings
methods = POST, GET

[expose:TA_splunk_cloud_app_exporter_settings_specified]
pattern = TA_splunk_cloud_app_exporter_settings/*
methods = POST, GET, DELETE

[expose:TA_splunk_cloud_app_exporter_splunk_cloud_app_export]
pattern = TA_splunk_cloud_app_exporter_splunk_cloud_app_export
methods = POST, GET

[expose:TA_splunk_cloud_app_exporter_splunk_cloud_app_export_specified]
pattern = TA_splunk_cloud_app_exporter_splunk_cloud_app_export/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
