[vulndb://<name>]
api_server = The URL of the VulnDB API server.
api_key = The API consumer key provided by VulnDB.
api_secret = The API consumer secret provided by VulnDB.
start_date = The date from which to start gathering VulnDB information in the format YYYY-MM-DD. (A setting of 1 will get ALL vulnerability information)
page_size = The number of results for each API call to return. (maximum 100)
min_cvssv2_score = The events with a score equal to or greater than a specified score will be indexed.(Leave this field blank to ingest all events).
reset_input = When checked, the input will start over from the specified start date.
nested = Nest the list of products/versions within the affected vendors list.
additional_info = Additional information from the National Vulnerability Database (NVD) related to the vulnerability (e.g. their CVSS and CPE data) is returned with each vulnerability.
show_cpe = Only CPE data generated by NVD related to a vulnerability is returned. The CPE data generated by RBS is not returned.
category = Additional information about the type of each classification is returned. This information is also available for reference in the VulnDB Portal Guide.
full_reference_url = All references are returned in full URI (API will return 'https://www.securityfocus.com/bid/62232' instead of '62232'.)
package_info = Affected Packages are returned when available.
show_cvss_v3 = CVSSv3 metrics for each applicable vulnerability are returned.
changelog = VulnDB entry changelog information for each vulnerability is returned. This information shows what type of modifications were made to the database entry.