# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 1

[launcher]
author = SOCRadar CyberIntelligence
version = 2.0.0
description = SOCRadar is a cloud-based, AI-powered Digital Risk Protection Platform enhanced by cyber threat intelligence capabilities. This App provides SOCRadar Alarm Data.

[ui]
is_visible = 1
label = SOCRadar Alarm Collecter APP
docs_section_override = AddOns:released

[package]
id = TA-socradar-alarm-collecter-app

[triggers]
reload.addon_builder = simple
reload.ta_socradar_alarm_collecter_app_account = simple
reload.ta_socradar_alarm_collecter_app_settings = simple
reload.passwords = simple
