[launcher]
version = 1.0.1
description = The Dropzone AI Add-on for Splunk enables integration with Dropzone AI's security automation platform. It monitors Dropzone AI instance health and collects investigation data for analysis in Splunk.
author = Dropzone AI

[id]
version = 1.0.1
name = dropzone_add_on

[install]
build = 1776947486
is_configured = false
state = enabled

[package]
id = dropzone_add_on
check_for_updates = true

[ui]
label = Dropzone AI Add-on for Splunk
supported_themes = light, dark
is_visible = true

[triggers]
reload.dropzone_add_on_settings = simple
