
[admin:TA_mist_for_splunk]
match = /
members = TA_mist_for_splunk_system_events, TA_mist_for_splunk_rogue_ap, TA_mist_for_splunk_audit_log, TA_mist_for_splunk_active_client_events, TA_mist_for_splunk_settings, TA_mist_for_splunk_marvis_events

[admin_external:TA_mist_for_splunk_system_events]
handlertype = python
handlerfile = TA_mist_for_splunk_rh_system_events.py
handleractions = edit, list, remove, create

[admin_external:TA_mist_for_splunk_rogue_ap]
handlertype = python
handlerfile = TA_mist_for_splunk_rh_rogue_ap.py
handleractions = edit, list, remove, create

[admin_external:TA_mist_for_splunk_audit_log]
handlertype = python
handlerfile = TA_mist_for_splunk_rh_audit_log.py
handleractions = edit, list, remove, create

[admin_external:TA_mist_for_splunk_active_client_events]
handlertype = python
handlerfile = TA_mist_for_splunk_rh_active_client_events.py
handleractions = edit, list, remove, create

[admin_external:TA_mist_for_splunk_settings]
handlertype = python
handlerfile = TA_mist_for_splunk_rh_settings.py
handleractions = edit, list

[admin_external:TA_mist_for_splunk_marvis_events]
handlertype = python
handlerfile = TA_mist_for_splunk_rh_marvis_events.py
handleractions = edit, list, remove, create

