[lookup_violations_mapping]
disabled= 0
enableSched = 1
cron_schedule = 45 * * * *
dispatch.earliest_time = -30d@d
dispatch.latest_time = now
display.events.fields = ["host","source","sourcetype","findingChain_cc_location"]
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.charting.chart = bar
display.visualizations.show = 0
run_on_startup = true
request.ui_dispatch_app = vss_v1
request.ui_dispatch_view = search
search = index=vss  source="*vss_rules.json"  \
| table description, displayName, documentationLink, id, level , name, suggestedAction category\
| dedup id\
| outputlookup findings_mapping.csv append=true

[lookup_compliance_mappings]
action.email.useNSSubject = 1
disabled= 0
enableSched = 1
cron_schedule = 45 * * * *
alert.track = 0
dispatch.earliest_time = -4h@m
dispatch.latest_time = now
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.show = 0
run_on_startup = true
request.ui_dispatch_app = vss-splunk-app
request.ui_dispatch_view = search
search = index="vss" sourcetype="_json" \
  | rename frameworkId  as id | join type=inner id\
    [search index="vss" sourcetype="_json" author=*  ]\
    | table title description, references remediationProcedure id name author\
    | fillnull value=n/a | search author="*" name=*\
    |outputlookup compliance_controlls_mapping.csv append=true
