#
#
#

#####################################
# Cisco PSIRT openVuln API Advisory #
#####################################

[cisco:vuln:advisories:all]
search = `cisco_advisory_all`
# tag = vulnerabilities

[cisco:vuln:advisories:asa]
search = `cisco_advisory_all` TERM(asa) product_is_asa=*

[cisco:vuln:advisories:ios]
search = `cisco_advisory_all` TERM(ios) product_is_ios=*

[cisco:vuln:advisories:nxos]
search = `cisco_advisory_all` TERM(nx-os) product_is_nxos=*

[cisco:vuln:advisories:sdwan]
search = `cisco_advisory_all` TERM(sd-wan) product_is_sdwan=*

[cisco:vuln:advisories:firepower]
search = `cisco_advisory_all` (TERM(firepower) OR TERM(fxos)) product_is_firepower=*

[cisco:vuln:advisories:webex]
search = `cisco_advisory_all` TERM(webex) product_is_webex=*

#####################################
# Cisco CVRF XML Data               #
#####################################

[cisco:vuln:cvrf:all]
search = `cisco_cvrf_all`
# tag = vulnerabilities