[mobileiron_cloud://default]
*Autogenerated by Splunk plugin for Eclipse.
username = <value>
password = <value>
admin_url = <value>
devices_poll_frequency = <value>
audit_trails_poll_frequency = <value>
index_data = <value>