# Splunk app configuration file

[install]
is_configured = 0
build = 1660604145

[ui]
is_visible = 1
label = Splunk Add-on for AWS Network Firewall

[launcher]
author = Splunk Works
description = Splunk Add-on for AWS Network Firewall
version = 1.0.1

[package]
check_for_updates = 1
id = Splunk_TA_aws_network_firewall

[id]
version = 1.0.1

