# DO NOT touch this input!!
# This input is used for UF remote upgrade via Deployment Server:
# Copy UF packages to UF updater, and trigger the upgrade
[powershell://Splunk-Upgrader]
script = . "$SplunkHome\etc\apps\splunk_app_uf_remote_upgrade_windows\bin\SPLUNK_UPDATER_INTERNAL_deliver_pkg.ps1"
disabled = 0
index = _internal
sourcetype = splunk_upgrader
schedule = * * * * *
# Update the schedule parameter the UF package upgrade using a cron expression.