
[birtday_remainder]
action.email = 1
action.email.allow_empty_attachment = 0
action.email.include.results_link = 0
action.email.include.view_link = 0
action.email.message.alert = Wish you many more happy returns of the day
action.email.subject.alert = happy birthday
 
action.email.useNSSubject = 1
action.webhook.enable_allowlist = 0
alert.digest_mode = 0
alert.suppress = 0
alert.track = 0
counttype = number of events
cron_schedule = 0 9 * * *
description = It will send birthday wishes to their employee
enableSched = 1
quantity = 0
relation = greater than
search = | bday \
| mvexpand result \
| eval a = split(result,":") \
| eval day =mvindex(a,1) \
| eval email =mvindex(a,3) \
| eval month =mvindex(a,2)|join [| makeresults \
    | eval now = now() \
    | eval day =strftime(now,"%d") \
    | eval month =strftime(now,"%b") \
    | eval month =lower(month)|table day month]|table day email month
