# no changes should need to be made here other than to change the monitoring interval frequency if needed - defaults to 1 day / 86400 seconds

# call check-log-permissions.sh as a scripted input
[script://$SPLUNK_HOME/etc/apps/TA-check-log-permissions/bin/check-log-permissions.sh]
disabled = 0

# set index below which will receive events - defaults to main
index = main

# every 5 minutes
#interval = 300.0

# once a day - default
interval = 86400.0

sourcetype = check_log_permissions
