#
# Splunk app configuration file
#

[install]
is_configured = 0
build = 1
state_change_requires_restart = true

[ui]
is_visible = 1
label = Kollective Collaboration Observability
supported_themes = light, dark
setup_view = setup_page_dashboard

[launcher]
description = Splunk Visualization for Kollective COM Location Performance Data
author = Kollective Technology
version = 1.0.0

[author=Kollective]
email = support@kollective.com
company = Kollective Technology, Inc.

[id]
version = 1.0.0
name = kollective_com

[package]
id = kollective_com
check_for_updates = true
show_upgrade_notification = true
