[calls_twilio]
batch_index_query = 0
case_sensitive_match = 1
filename = calls_twilio.csv

[message_twilio]
batch_index_query = 0
case_sensitive_match = 1
filename = message_twilio.csv

[events_twilio]
batch_index_query = 0
case_sensitive_match = 1
filename = events_twilio.csv
