# Tweaked version of the original windows event log parser which ships with Splunk
# Stackdriver writes in literal \n, \r, and \t characters. 
# Account Name:\t\tTESTUSER\r\n\tAccount Domain:\t\tWORKGROUP
[gcp-wel-col-kv]
SOURCE_KEY = Message
REGEX      = \w([^:\\\n\\\r]+)\:(\\t)+(.*?(?=\\r|\\t|\\n|r\\))
FORMAT     = $1::$3
MV_ADD     = true