[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 5

[launcher]
author = Syscloud
version = 1.0.3
description = SysCloud add-on for Splunk facilitates the collection of events within Splunk.

[ui]
is_visible = 1
label = Syscloud Add-On for Splunk
docs_section_override = AddOns:released

[package]
id = TA-syscloud
check_for_updates = 1

[triggers]
reload.addon_builder = simple
reload.ta_syscloud_account = simple
reload.ta_syscloud_settings = simple
reload.passwords = simple

