const path = require('path');
const MergeIntoSingleFilePlugin = require('webpack-merge-and-include-globally');

module.exports = {
  mode: 'production',
  optimization: {
    minimize: false
  },
  plugins: [
    new MergeIntoSingleFilePlugin({
      files: {
        "ciso.js": [
          './appserver/static/js/config.js',
          './appserver/static/js/vendor/echarts-4.0.4.min.js',
          './appserver/static/js/afterConfig.js',
          './appserver/static/js/vendor/echarts-map-world.js',
          './appserver/static/js/vendor/jquery-3.6.0.js',
          './appserver/static/js/vendor/angular-1.8.2.js',
          './appserver/static/js/vendor/angular-route-1.8.2.js',
          './appserver/static/js/vendor/angular-sanitize-1.8.2.js',
          './appserver/static/js/vendor/angular-dragdrop-1.0.13.js',
          './appserver/static/js/tools.js',
          './appserver/static/js/vendor/kw-ui-bootstrap-tpls-0.6.0.js',
          './appserver/static/js/vendor/angular-ui-router.min.js',
          './appserver/static/js/vendor/angular-ui-ieshiv.min.js',
          './appserver/static/js/vendor/angular-ui-mask.js',
          './appserver/static/js/vendor/spectrum.js',
          './appserver/static/js/vendor/kw-html2canvas-0.5.0-alpha1.js',
          './appserver/static/js/vendor/jquery.ui.widget.js',
          './appserver/static/js/vendor/kw-jquery.fileupload.js',
          './appserver/static/js/vendor/kw-jquery.fileupload-angular.js',
          './appserver/static/js/vendor/jquery.fileupload-process.js',
          './appserver/static/js/vendor/kw-jquery.iframe-transport.js',
          './appserver/static/js/app.module.js',
          './appserver/static/js/directives/echartsDirective.js',
          './appserver/static/js/services/AppRootScopeService.js',
          './appserver/static/js/services/SharedTimeRangeService.js',
          './appserver/static/js/controllers/CisoController.js',
          './appserver/static/js/controllers/CisoAlertsController.js',
          './appserver/static/js/services/UiAccessService.js',
          './appserver/static/js/directives/ButtonSwitchDirective.js',
          './appserver/static/js/directives/CisoEventsDirective.js',
          './appserver/static/js/directives/CisoAlertsDirective.js',
          './appserver/static/js/directives/CisoFileActivitiesDirective.js',
          './appserver/static/js/directives/CisoFilesDirective.js',
          './appserver/static/js/directives/CisoIdsDirective.js',
          './appserver/static/js/directives/CisoMapDirective.js',
          './appserver/static/js/directives/CisoMapSettingsDirective.js',
          './appserver/static/js/directives/CisoNewUsersDirective.js',
          './appserver/static/js/directives/CisoTopUsersDirective.js',
          './appserver/static/js/directives/ColorPickerDirective.js',
          './appserver/static/js/directives/GenericFormDirective.js',
          './appserver/static/js/directives/GenericTableDirective.js',
          './appserver/static/js/directives/ImageUploaderDirective.js',
          './appserver/static/js/directives/MapFilterDirective.js',
          './appserver/static/js/directives/TimeFilterDirective.js',
          './appserver/static/js/directives/CisoUsageDirective.js',
          './appserver/static/js/directives/CisoTopDomainsDirective.js',
          './appserver/static/js/services/SplunkSearchService.js',
          './appserver/static/js/services/AdminApiService.js',
          './appserver/static/js/services/CisoAlertService.js',
          './appserver/static/js/services/CisoMapService.js',
          './appserver/static/js/services/ConstantService.js',
          './appserver/static/js/services/GenericService.js',
          './appserver/static/js/services/ComplianceReportService.js',
          './appserver/static/js/services/ComplianceReportUnauthenticatedService.js',
          './appserver/static/js/services/MenuService.js',
          './appserver/static/js/filters/Filter.js',
          './appserver/static/js/services/SystemService.js',
          './appserver/static/js/services/TemporaryDisabledComponentsService.js',
          './appserver/static/js/services/AutoCompleteDataService.js',
          './appserver/static/js/services/ProcessService.js',
          './appserver/static/js/services/ValidationService.js',
          './appserver/static/js/services/ComplianceReportAccessService.js',
          './appserver/static/js/services/ComplianceReportAtpService.js',
          './appserver/static/js/services/ComplianceReportAvService.js',
          './appserver/static/js/services/ComplianceReportContingencyService.js',
          './appserver/static/js/services/ComplianceReportDlpService.js',
          './appserver/static/js/services/ComplianceReportIntegrityService.js',
          './appserver/static/js/services/ComplianceReportLdapService.js',
          './appserver/static/js/services/ComplianceReportProfilesService.js',
          './appserver/static/js/services/ComplianceReportSsoService.js',
          './appserver/static/js/services/ComplianceReportSyslogService.js',
          './appserver/static/js/services/ComplianceReportTosService.js',
          './appserver/static/js/services/ConstantService.js',
          './appserver/static/js/services/DownloaderService.js',
          './appserver/static/js/services/GenericLibrary.TypeFile.Service.js',
          './appserver/static/js/services/GenericLibraryService.js',
          './appserver/static/js/services/GenericLibrary.Expression.Service.js',
          './appserver/static/js/services/RestAPI.js',
          './appserver/static/js/services/SetupHelpboxTextService.js'
        ],
        "ciso.css": [
          './appserver/static/css/admin.css',
          './appserver/static/css/anomalies.css',
          './appserver/static/css/branding-editor.css',
          './appserver/static/css/button-switch.css',
          './appserver/static/css/ciso-dashboard.css',
          './appserver/static/css/color-picker.css',
          './appserver/static/css/flot.css',
          './appserver/static/css/generic-table-filter.css',
          './appserver/static/css/generic-table-responsive.css',
          './appserver/static/css/branding-editor.css',
          './appserver/static/css/hipaa-report.css',
          './appserver/static/css/image-uploader.css',
          './appserver/static/css/intlTelInput.css',
          './appserver/static/css/jquery.fileupload-ui.css',
          './appserver/static/css/kw16-bootstrap-resize.min.css',
          './appserver/static/css/kw16-main.css',
          './appserver/static/css/kw16-main-resize.css',
          './appserver/static/css/manage-folder.css',
          './appserver/static/css/position-editor.css',
          './appserver/static/css/routing-graph.css',
          './appserver/static/css/scope-editor.css',
          './appserver/static/css/sftp-popup.css',
          './appserver/static/css/spectrum.css',
          './appserver/static/css/storage-portlet.css',
          './appserver/static/css/webform.css',
          './appserver/static/css/webform-kwui.css',
          './appserver/static/css/v2/anomalies.css',
          './appserver/static/css/v2/ciso-dashboard.css',
          './appserver/static/css/v2/compliance-report.css',
          './appserver/static/css/v2/date-picker.css',
          './appserver/static/css/v2/icons.css',
          './appserver/static/css/v2/main.css',
          './appserver/static/css/v2/map-filter.css',
        ]
      }
    }),
  ],
  output: {
     path: path.resolve(__dirname, 'appserver/static'),
   },
};