#
# Splunk app configuration file
#

[package]
id = power_of_spl
check_for_updates = true

[install]
state = enabled
is_configured = 1
build = 1.0

[ui]
is_visible = 1
label = Power of SPL

[launcher]
author = Stephen Luedtke
description = This App is a tutorial for common SPL examples.
version = 1.0

