[script:alert_info]
match                 = /skylight_security_for_splunk/alert_info
script                = alert_info.py
scripttype            = persist
handler               = alert_info.AlertHandler
# requireAuthentication = true
#capability           = am_read_helpers
output_modes          = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true

[script:skylight_mode]
match                 = /skylight_security_for_splunk/skylight_mode
script                = skylight_mode.py
scripttype            = persist
handler               = skylight_mode.ModeHandler
output_modes          = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true

[script:network_chain]
match                 = /skylight_security_for_splunk/network_chain
script                = network_chain.py
scripttype            = persist
handler               = network_chain.ChainHandler
output_modes          = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true

[admin:skylight_security_for_splunk]
match = /
members = skylight_security_for_splunk_settings, skylight_security_for_splunk_skylight_assets

[admin_external:skylight_security_for_splunk_settings]
handlertype = python
handlerfile = skylight_security_for_splunk_rh_settings.py
handleractions = edit, list

[admin_external:skylight_security_for_splunk_skylight_assets]
handlertype = python
handlerfile = skylight_security_for_splunk_rh_skylight_assets.py
handleractions = edit, list, remove, create
