[whois_lookup_history]
external_type = kvstore
collection = whois_lookup_history
fields_list = _key, domain, fooyn, qwaittime, queued, retrieved, created, expires, updated, nameservers, registrant, registrar, registrant_country, registrant_email, registrant_org, admin_country, admin_email, technical_country, technical_email, risk_score, components
case_sensitive_match=false

[whois_lookup_queue]
external_type = kvstore
collection = whois_lookup_queue
fields_list = _key, domain, fooyn, queued
case_sensitive_match=false

[public_suffix_list]
filename = public_suffix_list.csv
case_sensitive_match=false
replicate = true

[dtools_watchlist]
filename = dtools_watchlist.csv
case_sensitive_match=false
replicate = true

[iris_lookup_queue]
external_type = kvstore
collection = iris_lookup_queue
fields_list = _key, domain, fooyn, queued
case_sensitive_match=false

[iris_lookup_history]
external_type = kvstore
collection = iris_lookup_history
fields_list = _key, domain, fooyn, qwaittime, queued, retrieved, registrant_contact_org, ip_2_asn_1, redirect_domain, alexa, registrant_contact_state, google_analytics, ip_1_country_code, ip_1_isp, admin_contact_name, billing_contact_state, technical_contact_postal, technical_contact_fax, _time, whois_url, billing_contact_name, technical_contact_phone, name, adsense, registrant_contact_phone, soa_email_1, technical_contact_name, ip_2_address, email_domain_2, admin_contact_fax, technical_contact_country, email_domain_1, create_date, website_response, active, registrar, technical_contact_state, admin_contact_phone, billing_contact_fax, name_server_1_host, registrant_contact_name, additional_whois_email_1, registrant_contact_street, admin_contact_city, billing_contact_city, name_server_2_ip_1, name_server_2_domain, registrant_name, registrant_contact_postal, data_updated_timestamp, admin_contact_org, name_server_1_ip_1, ip_2_isp, tld, registrant_org, risk_score, billing_contact_street, billing_contact_phone, admin_contact_postal, registrant_contact_country, admin_contact_country, registrant_contact_city, ip_1_asn_1, spf_info, admin_contact_street, registrant_contact_fax, technical_contact_street, redirect, billing_contact_postal, admin_contact_state, billing_contact_org, technical_contact_org, ip_1_address, billing_contact_country, technical_contact_city, name_server_2_host, ip_2_country_code, name_server_1_domain, expiration_date, mx_1_ip_1, ssl_info_1_hash, ssl_info_1_organization, priority, mx_1_domain, ssl_info_1_subject, mx_1_host, admin_contact_email_1, registrant_contact_email_1, name_server_2_ip_2, technical_contact_email_1, name_server_1_ip_2, note, proximity, threat_profile, threat_profile_malware, threat_profile_phishing, threat_profile_spam, tags, risk_evidence
case_sensitive_match=false

[suppressed_tags]
external_type = kvstore
collection = suppressed_tags
fields_list = _key, tag_name

[critical_tags]
external_type = kvstore
collection = critical_tags
fields_list = _key, tag_name

[phisheye_results]
external_type = kvstore
collection = phisheye_results
time_field = imported
time_format = %s
fields_list = _key, domain, imported, monitor, risk_score

[phisheye_monitors]
external_type = kvstore
collection = phisheye_monitors
fields_list = _key, term, enabled

[critical_phisheye_iocs]
external_type = kvstore
collection = critical_phisheye_iocs
fields_list = _key, value, type, imported