[ObsidianAlerts]
acceleration.manual_rebuilds = true
acceleration.schedule_priority = highest
tags_whitelist = alerts

[ObsidianAuthentication]
acceleration.cron_schedule = 3-58/5 * * * *
acceleration.earliest_time = -1y
acceleration.manual_rebuilds = true
acceleration.schedule_priority = highest
tags_whitelist = cleartext,default,insecure,multifactor,pci,privileged

