
[expose:TA_upstream_settings]
pattern = TA_upstream_settings
methods = POST, GET

[expose:TA_upstream_settings_specified]
pattern = TA_upstream_settings/*
methods = POST, GET, DELETE

[expose:TA_upstream_upstreamdata]
pattern = TA_upstream_upstreamdata
methods = POST, GET

[expose:TA_upstream_upstreamdata_specified]
pattern = TA_upstream_upstreamdata/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
