[nix]
title = Unix and Linux
description = Logs and metrics
icon_path = app/itsi/images/icon_library/data_integrations/linux.svg

[windows]
title= Windows
description = Logs and metrics
icon_path = app/itsi/images/icon_library/data_integrations/windows.svg

[sim]
title = Splunk Infrastructure Monitoring
description = Logs and metrics
icon_path = app/itsi/images/icon_library/data_integrations/sim.png

[vmware]
title = VMware
description = Logs and metrics
icon_path = app/itsi/images/icon_library/data_integrations/vmware.svg

[appdynamics]
title = Splunk AppDynamics
description = Inbound notifications
icon_path = app/itsi/images/icon_library/data_integrations/AppDynamics.svg
supported_ingest_methods = webhook,splunk-add-on

[thousandeyes]
title = Cisco ThousandEyes
description = Inbound notifications
icon_path = app/itsi/images/icon_library/data_integrations/ThousandEyes.svg
supported_ingest_methods = webhook,splunk-add-on

[cloudtrail]
title = AWS CloudTrail
description = Inbound notifications
icon_path = app/itsi/images/icon_library/data_integrations/AWS_CloudTrail.svg
supported_ingest_methods = webhook,splunk-add-on

[nagios]
title = Nagios
description = Inbound notifications
icon_path = app/itsi/images/icon_library/data_integrations/nagios.svg
supported_ingest_methods = webhook,splunk-add-on

[o11y]
title = Splunk Observability Cloud
description = Inbound notifications
icon_path = app/itsi/images/icon_library/data_integrations/o11y.svg
supported_ingest_methods = webhook,splunk-add-on

[solarwinds]
title = Solarwinds
description = Inbound notifications
icon_path = app/itsi/images/icon_library/data_integrations/solarwinds.svg
supported_ingest_methods = webhook

[scom]
title = Microsoft SCOM
description = Inbound notifications
icon_path = app/itsi/images/icon_library/data_integrations/scom.svg
supported_ingest_methods = webhook,splunk-add-on

[generic]
title = Generic
description = Inbound notifications
icon_path = app/itsi/images/icon_library/data_integrations/generic.svg
supported_ingest_methods = webhook