[install]
state_change_requires_restart = false
state = enabled

[package]
check_for_updates = true
id = TA-JamfProtect

[ui]
is_visible = true
label = Jamf Protect
docs_section_override = AddOns:released

[launcher]
author = Jamf Software
version = 2.0.6
description = Jamf Protect Add-on for Splunk

[id]
name = TA-JamfProtect
version = 2.0.6
