# Below we define to script stanza exactly the same but with different path seperators
# This allows us to work on either windows or *ix
# Bug has been filed to have script stanza work like tail/monitor where it does not matter.

[script://./bin/getimap.py]
interval = 300
sourcetype = imap
source = imap
index = mail
disabled = false 

[script://.\bin\getimap.py]
interval = 300
sourcetype = imap
source = imap
index = mail
disabled = true 
