
[expose:TA_s3_sink_alert_action_for_splunk_account]
pattern = TA_s3_sink_alert_action_for_splunk_account
methods = POST, GET

[expose:TA_s3_sink_alert_action_for_splunk_account_specified]
pattern = TA_s3_sink_alert_action_for_splunk_account/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
