[source::...ta-eot-connector-for-osisoft-pi-gateways*.log*]
sourcetype = ta:eot:connector:for:osisoft:pi:gateways:log

[source::...ta_eot_connector_for_osisoft_pi_gateways*.log*]
sourcetype = ta:eot:connector:for:osisoft:pi:gateways:log

[eotosipigateway]
DATETIME_CONFIG = None
KV_MODE = json
NO_BINARY_CHECK = 1
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

