[expose:splunk-filelink/accounts]
methods = GET, POST, DELETE
pattern = splunk-filelink/accounts/**

[expose:splunk-filelink/files]
methods = GET, POST, DELETE
pattern = splunk-filelink/files/**

[expose:splunk-filelink/permissions]
methods = GET, POST
pattern = splunk-filelink/permissions/**

[expose:splunk-filelink/popup]
methods = GET, POST
pattern = splunk-filelink/popup/**