
[admin:Radware_CWAF_Event_Collector]
match = /
members = Radware_CWAF_Event_Collector_settings, Radware_CWAF_Event_Collector_cloud_waf

[admin_external:Radware_CWAF_Event_Collector_settings]
handlertype = python
python.version = python3
handlerfile = Radware_CWAF_Event_Collector_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:Radware_CWAF_Event_Collector_cloud_waf]
handlertype = python
python.version = python3
handlerfile = Radware_CWAF_Event_Collector_rh_cloud_waf.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
