[install]
build = 1

[ui]
is_visible = 0
label = Monitoring SOAR as a Service

[launcher]
author = Splunk, Inc.
description = The Content Pack for Monitoring SOAR as a Service provides an ITSI-based approach to monitor the health of your SOAR server environment.
version = 1.0.0

