
[purestorage:flasharray:alerts]
DATETIME_CONFIG = NONE
INDEXED_EXTRACTIONS = NONE
SHOULD_LINEMERGE = false
KV_MODE = JSON
LINE_BREAKER = ([\r\n]+)

TIME_PREFIX = "created"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ

EVAL-app = "Pure Storage Flash Array"
EVAL-body = 'issue'
EVAL-description = 'issue'
EVAL-severity = if('severity'=="info", "informational", 'severity')
EVAL-signature = 'issue'
EVAL-src = 'ipaddress'
EVAL-src_ip = 'ipaddress'
EVAL-src_port = 'ipaddress_port'
EVAL-vendor_product = "Pure Storage:Flash Array"

REPORT-ccx_purestorage_flasharray_alerts_ipaddress = ccx_purestorage_flasharray_alerts_ipaddress

[purestorage:flasharray:audit]
DATETIME_CONFIG = NONE
INDEXED_EXTRACTIONS = NONE
SHOULD_LINEMERGE = false
KV_MODE = JSON
LINE_BREAKER = ([\r\n]+)

TIME_PREFIX = "created"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ

EVAL-action = case('subcommand' IN ("create") OR like('arguments', "create%"), "created", 'subcommand' IN ("destroy", "eradicate")  OR like('arguments', "delete%"), "deleted", 'subcommand' IN ("tag", "untag", "demote", "promote", "setattr"), "modified", 'subcommand'=="remoteassist" AND 'arguments'=="--connect", "started")
EVAL-change_type = 'command'
EVAL-command = 'arguments'
EVAL-dvc = 'origin.name'
EVAL-object = 'arguments'
EVAL-src = 'origin.name'
EVAL-src_name = 'origin.name'

[purestorage:flasharray:login]
DATETIME_CONFIG = NONE
INDEXED_EXTRACTIONS = NONE
SHOULD_LINEMERGE = false
KV_MODE = JSON
LINE_BREAKER = ([\r\n]+)

TIME_PREFIX = "end_time"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ

EVAL-action = case(('event'=="failed authentication" OR 'event'="login"), if('event'=="failed authentication", "failure", "success"))
EVAL-app = case(('event'=="failed authentication" OR 'event'="login"), "Pure Storage:Flash Array")
EVAL-signature = case(('event'=="failed authentication" OR 'event'="login"), 'event')
EVAL-src = case(('event'=="failed authentication" OR 'event'="login"), 'location')
EVAL-src_ip = case(('event'=="failed authentication" OR 'event'="login"), 'location')
EVAL-user = if('user'=="null" OR isnull('user'), null(), 'user')
EVAL-vendor_product = "Pure Storage:Flash Array"
