[SuccessfulAuthentication]
search = (sourcetype=proofpoint:casb:activitylog AND action = "success")

[UnsuccessfulAuthentication]
search = (sourcetype=proofpoint:casb:activitylog AND action = "failure")

[FileEvent]
search = (sourcetype=proofpoint:casb:activitylog AND (resource="File/Folder" OR resource="File" OR resource = "Folder" OR resource = "Bucket / Container"))

[UserChanges]
search = (sourcetype=proofpoint:casb:activitylog AND resource="User(s)")

[ProofpointCasbAlert]
search = (sourcetype=proofpoint:casb:alerts)
