# Microsoft Teams Card action settings

action.msteamscards.param.webhookurl = <string>
* The target Teams channel URL generated by adding an Incoming Webhook connector.

action.msteamscards.param.title = <string>
* Title that will appear on the Card in the Teams channel.

action.msteamscards.param.subtitle = <string>
* Subtitle that will appear on the Card in the Teams channel.

action.msteamscards.param.imgurl = <string>
* An image that will appear on the Card in the Teams channel.

action.msteamscards.param.theme = <string>
* Theme color for the Card. This displays as a colored bar along the top of the Card.