[skylight_http]
search = (sourcetype=skylight:http)

[skylight_sql]
search = (sourcetype=skylight:sql)

[skylight_dns]
search = (sourcetype=skylight:dns)

[skylight_smb]
search = (sourcetype=skylight:smb)

[skylight_tls]
search = (sourcetype=skylight:tls)
