[urlsonar]
is_custom = 1
label = Scan URL using URLSonar
description = Accepts a URL input to scan for threats by passing it through the VirusTotal API.
icon_path = urlsonar.png
payload_format = json

param.user_agent = Splunk/$server.guid$
