#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 1
label = Centrify App for Splunk

[launcher]
author = Centrify Corporation
description = This app provides different dashboards and reports to visualize data normalised Centrify audit trail events.
version = 2.4.0

[package]
id = Centrify

