# Linux

[script://./bin/rss.sh]
interval = 86400
sourcetype = rssfeed
source = rss_news
disabled = false

# Either enable the first one above or this one below, but not both.
[script://./bin/rss2.sh]
interval = 86400
sourcetype = rssfeeds
source = rss_news
disabled = true

# Windows Only below. Only enable one of the inputs below on Windows.

[script://.\bin\rss.bat]
interval = 86400
sourcetype = rssfeed
source = rss_news
disabled = true

[script://.\bin\rss2.bat]
interval = 86400
sourcetype = rssfeed
source = rss_news
disabled = true


