[launcher]
version = 1.1.0
description = Retrieve data from FTP
author = LukeMurphey

[package]
id = ftp_receiver

[install]
build = 1649193588
# Last commit: Tue, 5 Apr 2022 17:19:48 -0400
is_configured = false

[ui]
is_visible = false
label = FTP Receiver