[InSights_ioc_mark_whitelist]
display_location = field_menu
fields = *
label = IntSights: Add to Whitelist
link.uri = /app/IntSightsAppForSplunk/intsights_indicators?search=%7C%20intsightsaddtowhitelist%20value%3D%22$@field_value$%22%20%7C%20table%20Value%2C%20Whitelist%2C%20Note
type = link