# Copyright (C) 2005-2011 Splunk Inc.  All Rights Reserved.  
#
# Splunk app configuration file
#

[package]
id = ufx

[ui]
is_visible = true
label = Field Extractor

[install]
is_configured = true
state = enabled

[launcher]
author=Carasso
description = Create and manage fields in your data, with simple point-and-click! 
version=2.3

