[launcher]
description = Splunk_Essentials_For_Wire_Data
author = Simon O'Brien
version = 1.0.5

[package]
id = Splunk_Essentials_For_Wire_Data

[install]
build = 1
install_source_checksum = 6a2843e0b3a181491b13e4d24524b455a8b9b321

[ui]
is_visible = 1
label = Splunk Essentials for Wire Data

[triggers]
reload.ui-tour = simple
