# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = true
is_configured = 0
state = enabled
build = 2

[launcher]
author = Ryan Faircloth
version = 1.0.1
description = Download content from specified URL and index the resulting metadata for threat hunting activities

[ui]
is_visible = 1
label = UrlInfoCollector
docs_section_override = AddOns:released

[package]
id = TA-UrlInfoCollector

[triggers]
reload.addon_builder = simple
reload.ta_urlinfocollector_account = simple
reload.ta_urlinfocollector_settings = simple
reload.passwords = simple
