[threatq_indicators]
start_by_shell = false
sourcetype = threatq:indicators
indicator_status = Active
interval = 900
threshold_score = 8
checkbox_for_index = true
pull_all_iocs = false
disabled = 0
python.version = python3
