[source::...ta-infoblox-ipam*.log*]
sourcetype = tainfobloxipam:log

[source::...ta_infoblox_ipam*.log*]
sourcetype = tainfobloxipam:log

[infoblox:status:node]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[infoblox:status:service]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[infoblox:ipam:host]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

