[Total Request Types]
action.email.useNSSubject = 1
alert.track = 0
dispatch.earliest_time = 0
display.general.type = visualizations
display.page.search.tab = visualizations
display.statistics.show = 0
request.ui_dispatch_app = SafeNetAT
request.ui_dispatch_view = search
search = sourcetype="activity-st" | timechart count by ClientReqType

[Top Processes Accessing PF Assets]
action.email.useNSSubject = 1
alert.track = 0
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.charting.chart = pie
display.visualizations.show = 0
request.ui_dispatch_app = SafeNetAT
request.ui_dispatch_view = search
search = top Process | eval Process=ltrim(Process,"PROCESS:"), Process=rtrim(Process,".")

[Console Login Failures]
search = sourcetype="audit-st" Action="Login" Failed OR failure OR invalid | rex field=_raw "from (?<from>.*)" | stats count by host, UserName, from | sort -count | rename host as KeySecure

[User Console Logins]
search = sourcetype="audit-st" Action="Login" "Logged in" | rex field=_raw "from (?<from>.*)" | stats count by UserName, from, host | sort -count | rename host as KeySecure

[Access attempts from unauthorized PFClients]
action.email.useNSSubject = 1
alert.track = 0
dispatch.earliest_time = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.charting.chart = bar
display.visualizations.show = 0
request.ui_dispatch_app = SafeNetAT
request.ui_dispatch_view = search
search = sourcetype="pfmgr-st" "not properly validated." | rex "(?<PFclient>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})" | stats count by host, PFclient | sort -count | rename host as KeySecure

[Resouces Protected by ProtectFile]
action.email.useNSSubject = 1
alert.track = 0
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.charting.chart = bar
display.visualizations.show = 0
request.ui_dispatch_app = SafeNetAT
request.ui_dispatch_view = search
search = sourcetype="safenetat:pfclient" | rex field=_raw "Path: (?P<Path>[^\s]+)" | eval Process=ltrim(Process,"PROCESS:"), Process=rtrim(Process,".") | eval UserGroup=ltrim(UserGroup,"USER:"), UserGroup=rtrim(UserGroup,".") | stats count by host, UserGroup, Process, Path | sort -count
