
[admin:TA_forza_telemetry]
match = /
members = TA_forza_telemetry_settings, TA_forza_telemetry_forza_udp

[admin_external:TA_forza_telemetry_settings]
handlertype = python
handlerfile = TA_forza_telemetry_rh_settings.py
handleractions = edit, list

[admin_external:TA_forza_telemetry_forza_udp]
handlertype = python
handlerfile = TA_forza_telemetry_rh_forza_udp.py
handleractions = edit, list, remove, create
