# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = true
is_configured = false
state = enabled
build = 2

[launcher]
author = Cisco
version = 1.0.33
description = Cisco Cloud Security Umbrella Addon for CIsco managed and client managed buckets

[ui]
is_visible = 1
label = Cisco Cloud Security Umbrella Addon
docs_section_override = AddOns:released

[package]
id = TA-cisco-cloud-security-umbrella-addon

[triggers]
reload.addon_builder = simple
reload.ta_cisco_cloud_security_umbrella_addon_account = simple
reload.ta_cisco_cloud_security_umbrella_addon_settings = simple
reload.passwords = simple