[csv_extractions]
SOURCE_KEY = event_csv
DELIMS = ","
FIELDS = "event_time","src_ip","src_port","dest_ip","dest_port","transport","future_use_1","future_use_2","packets_out","packets_in","bytes_out","bytes_in","src_interface","dest_interface","path_id","app","vendor_action","zbfw_classification_rules"

