[inputs://<name>]
u4v_ip_address = 
u4v_port = Unisphere default port is 8443
u4v_username = 
u4v_password = 
u4v_vmax_id = This is the 12-digit array ID
rest_request_timeout = (Optional) Default REST request timeout value in seconds, default is 60, for more information please consult the TA user guide
select_array = Collect Array level information
select_array_metrics = (Optional) For custom Array reporting metrics please define comma separated list of metrics here.
select_srp = Collect Storage Resource Pool level information
select_srp_metrics = (Optional) For custom SRP reporting metrics please define comma separated list of metrics here
select_sg = Collect Storage Group level information
select_sg_metrics = (Optional) For custom SG reporting metrics please define comma separated list of metrics here
select_director = Collect Director level information
select_fe_dir_metrics = (Optional) For custom FE Director reporting metrics please define comma separated list of metrics here
select_be_dir_metrics = (Optional) For custom BE Director reporting metrics please define comma separated list of metrics here
select_rdf_dir_metrics = (Optional) For custom RDF Director reporting metrics please define comma separated list of metrics here
select_im_dir_metrics = (Optional) For custom IM Director reporting metrics please define comma separated list of metrics here
select_eds_dir_metrics = (Optional) For custom EDS Director reporting metrics please define comma separated list of metrics here
select_em_dir_metrics = (Optional) For custom EM Director reporting metrics please define comma separated list of metrics here
select_port = Collect Port level information
select_fe_port_metrics = (Optional) For custom FE Port reporting metrics please define comma separated list of metrics here
select_be_port_metrics = (Optional) For custom BE Port reporting metrics please define comma separated list of metrics here
select_rdf_port_metrics = (Optional) For custom RDF Port reporting metrics please define comma separated list of metrics here
select_pg = Collect Port Group level information
select_pg_metrics = (Optional) For custom Port Group reporting metrics please define comma separated list of metrics here
select_iscsi = Collect iSCSI Target & IP Interface level information
select_ip_interface_metrics = (Optional) For custom IP Interface reporting metrics please define comma separated list of metrics here
select_iscsi_target_metrics = (Optional) For custom iSCSI Target reporting metrics please define comma separated list of metrics here
select_host = Collect Host level information
select_host_metrics = (Optional) For custom Host reporting metrics please define comma separated list of metrics here
select_mv = Collect Masking View level information
select_mv_metrics = (Optional) For custom Masking View reporting metrics please define comma separated list of metrics here
select_initiator = Collect Initiator level information
select_initiator_metrics = (Optional) For custom Initiator reporting metrics please define comma separated list of metrics here.
select_rdf = Collect RDF Group level information
select_rdfs_metrics = (Optional) For custom RDF/S reporting metrics please define comma separated list of metrics here
select_rdfa_metrics = (Optional) For custom RDF/A reporting metrics please define comma separated list of metrics here
select_metro_dr = Collect Metro Disaster Recovery level information
select_snap_policy = Collect Snapshot Policy level information
select_audit_logs = Collect system audit logs - WARNING: Only enable this once per instance of Unisphere configured with Splunk
select_alerts = Collect Array alerts - WARNING: If Alerts are not managed in Unisphere this can result a significant level of data ingestion into Splunk