[set_access]
REGEX = logtype=access
FORMAT = sourcetype::access
DEST_KEY = MetaData:Sourcetype

[set_cloudsummary]
REGEX = logtype=cloudsummary
FORMAT = sourcetype::cloudsummary
DEST_KEY = MetaData:Sourcetype

[set_cloudaudit]
REGEX = logtype=cloudaudit
FORMAT = sourcetype::cloudaudit
DEST_KEY = MetaData:Sourcetype

[set_stats]
REGEX = STATS=True
FORMAT = sourcetype::stats
DEST_KEY = MetaData:Sourcetype

[riskscores]
batch_index_query = 0
case_sensitive_match = 1
filename = riskscores.csv

[countries]
batch_index_query = 0
case_sensitive_match = 0
filename = country.csv

[bgpenalty]
batch_index_query = 0
case_sensitive_match = 1
filename = bgpenalty.csv
