###############################
##     Mark Hill - 2018      ##
## mark.hill@intalock.com.au ##
###############################

## Monitor stanzas commected out to get through Splunk Cloud App inspect. If this is use on-prem, please uncomment.

##[monitor:///opt/splunk/etc/apps/maxmind_tracker/bin]
##disabled = false
##index = maxmind_tracker
##sourcetype = wget
##whitelist = .log$

[script://$SPLUNK_HOME/etc/apps/maxmind_tracker/bin/md5_tracker.sh]
disabled = false
index = maxmind_tracker
interval = 1 */12 * * *
sourcetype = wget

##[monitor:///opt/splunk/etc/apps/maxmind_tracker/bin/GeoLite2-City.tar.gz.md5]
##disabled = false
##index = maxmind_tracker
##sourcetype = wget_md5
##crcSalt = <SOURCE>
