[cyera_collector]
python.version = python3
python.required = 3.13
start_by_shell = false

[cyera_events]
python.version = python3
python.required = 3.13
start_by_shell = false

[cyera_issues]
python.version = python3
python.required = 3.13
start_by_shell = false

[cyera_datastores]
python.version = python3
python.required = 3.13
start_by_shell = false

[cyera_classifications]
python.version = python3
python.required = 3.13
start_by_shell = false

[cyera_audit]
python.version = python3
python.required = 3.13
start_by_shell = false
