[ccx_suricata_eve_alert_web]
search = (sourcetype=suricata) event_type=alert url="*"
#tags = web

[ccx_suricata_eve_alert_ids_attack]
search = (sourcetype=suricata) event_type=alert NOT "alert.category" IN("Not Suspicious Traffic")
#tags = attack communicate ids network

[ccx_suricata_eve_alert_certificates]
search = (sourcetype=suricata) event_type=alert ssl_issuer_common_name="*"
#tags = certificate tls

[ccx_suricata_eve_alert_flow]
search = (sourcetype=suricata) event_type=alert flow_id="*"
#tags = communicate network session

[ccx_suricata_eve_alert_alerts]
search = (sourcetype=suricata) event_type=alert "alert.category" IN("Not Suspicious Traffic")
#tags = alert communicate network

[ccx_suricata_eve_alert_dns]
search = (sourcetype=suricata) event_type=alert transaction_id="*"
#tags = dns network resolution

[ccx_suricata_eve_dns]
search = (sourcetype=suricata) event_type=dns
#tags = network resolution dns

[ccx_suricata_eve_http]
search = (sourcetype=suricata) event_type=http
#tags = web

[ccx_suricata_eve_tls]
search = (sourcetype=suricata) event_type=tls
#tags = certificate tls

[ccx_suricata_eve_flow]
search = (sourcetype=suricata) event_type=flow
#tags = network communicate session
