[admin:ransomware_addon_for_splunk]
match = /
members = ransomware_addon_for_splunk_Victim, ransomware_addon_for_splunk_account, ransomware_addon_for_splunk_csirt, ransomware_addon_for_splunk_group_details, ransomware_addon_for_splunk_group_iocs, ransomware_addon_for_splunk_listsectors, ransomware_addon_for_splunk_negotiation, ransomware_addon_for_splunk_press_all, ransomware_addon_for_splunk_ransomnotes, ransomware_addon_for_splunk_ransomstats, ransomware_addon_for_splunk_settings, ransomware_addon_for_splunk_yara

[admin_external:ransomware_addon_for_splunk_account]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_settings]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_csirt]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_csirt.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_group_details]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_group_details.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_listsectors]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_listsectors.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_group_iocs]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_group_iocs.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_negotiation]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_negotiation.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_press_all]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_press_all.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_ransomnotes]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_ransomnotes.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_ransomstats]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_ransomstats.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_Victim]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_Victim.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ransomware_addon_for_splunk_yara]
handlertype = python
python.version = python3
handlerfile = ransomware_addon_for_splunk_rh_yara.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
