
[CrowdStrike Event Streams TA Logs - 30 Days]
action.email.useNSSubject = 1
alert.track = 0
description = Collects the CrowdStrike Event Streams Technical Add-on logs for the past 30 days
dispatch.earliest_time = -30d@d
dispatch.latest_time = now
display.visualizations.show = 0
request.ui_dispatch_app = TA-crowdstrike-falcon-data-replicator
request.ui_dispatch_view = search
search = index=_internal  sourcetype="tacrowdstrikefalconeventstreams:log"

[CrowdStrike Event Streams: Indexing]
action.email.useNSSubject = 1
alert.track = 0
description = Shows the amount of CrowdStrike Event Streams Data that was indexed within a specific time frame.
dispatch.earliest_time = -7d@h
dispatch.latest_time = now
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.show = 0
request.ui_dispatch_app = TA-crowdstrike-falcon-event-streams
request.ui_dispatch_view = search
search = `cs_es_get_index`  | eval "Indexed Time"=strftime(_indextime,"%Y-%m-%d %H:%M:%S") | stats count by "Indexed Time" | rename count as "CrowdStrike Event Streams Events Indexed" | sort -"Indexed Time"

[CrowdStrike Event Stream Data Indexed vs Event Time]
action.email.useNSSubject = 1
alert.track = 0
description = Shows when the CrowdStrike Event Streams data was indexed, the event timestamp, the sourcetype , the metadata.eventType and the count of events. Timespan needs to be large enough to include the event's time stamp.
dispatch.earliest_time = -7d@h
dispatch.latest_time = now
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.show = 0
request.ui_dispatch_app = TA-crowdstrike-falcon-event-streams
request.ui_dispatch_view = search
search = index=* sourcetype="CrowdStrike:Event:Streams:JSON" | eval "Indexed Time"=strftime(_indextime,"%Y-%m-%d %H:%M:%S")  | eventstats count by "Indexed Time" | rename count as "Number of CrowdStrike Event Streams Events"  | eval "Event Streams Event Time" = strftime(_time, "%Y-%m-%d %H:%M:%S")| table  "Indexed Time", "Event Streams Event Time", sourcetype, metadata.eventType, "Number of CrowdStrike Event Streams Events"  | sort  -"Indexed Time"

[CrowdStrike Token Refresh Check]
action.crowdstrike_event_streams_restart_input.param.base_url = https://10.10.10.211:8089
action.crowdstrike_event_streams_restart_input.param.input_name = demo
alert_condition = search count < 2
search = `cs_es_tc_input(demo)` | stats count
counttype = custom
action.crowdstrike_event_streams_restart_input = 1
action.keyindicator.invert = 0
action.makestreams.param.verbose = 0
action.nbtstat.param.verbose = 0
action.notable.param.verbose = 0
action.nslookup.param.verbose = 0
action.ping.param.verbose = 0
action.risk.param.verbose = 0
action.send2uba.param.verbose = 0
action.threat_add.param.verbose = 0
disabled = 1
quantity = 2
relation = less than
alert.digest_mode = 0
alert.expires = 999d
alert.severity = 5
alert.suppress = 0
alert.track = 1
cron_schedule = */60 * * * *
description = Monitors the CrowdStrike Event Streams log file to detect if an input has stopped running.
dispatch.earliest_time = -60m@m
dispatch.latest_time = now
display.events.fields = ["host","source","sourcetype","action"]
display.page.search.mode = verbose
enableSched = 1
request.ui_dispatch_app = TA-crowdstrike-falcon-event-streams
request.ui_dispatch_view = search

