[VMRay ES Threatintel generation]
action.email.useNSSubject = 1
action.keyindicator.invert = 0
action.makestreams.param.verbose = 0
action.nbtstat.param.verbose = 0
action.notable.param.verbose = 0
action.nslookup.param.verbose = 0
action.ping.param.verbose = 0
action.risk.param.verbose = 0
action.send2uba.param.verbose = 0
action.threat_add.param.verbose = 0
alert.track = 0
cron_schedule = 15 * * * *
description = Generates a Lookup for the ES App
dispatch.earliest_time = -30d@d
dispatch.latest_time = now
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 0
request.ui_dispatch_app = TA-vmray-analyzer
request.ui_dispatch_view = search
schedule_window = 15
search = index=vmray (sourcetype=vmray:analysis OR sourcetype=vmray:submission) | eval bind_id=coalesce(analysis_sample_id,submission_sample_id)| transaction bind_id maxspan=12h | where analysis_vti_score>=75 | eval description="VMRay" | eval file_hash=submission_sample_md5 | eval file_name=submission_filename| eval weight=5 | table description file_hash file_name weight  |outputlookup vmray_es_threat_export
