
[expose:TA_mural_account]
pattern = TA_mural_account
methods = POST, GET

[expose:TA_mural_account_specified]
pattern = TA_mural_account/*
methods = POST, GET, DELETE

[expose:TA_mural_settings]
pattern = TA_mural_settings
methods = POST, GET

[expose:TA_mural_settings_specified]
pattern = TA_mural_settings/*
methods = POST, GET, DELETE

[expose:TA_mural_mural_audit]
pattern = TA_mural_mural_audit
methods = POST, GET

[expose:TA_mural_mural_audit_specified]
pattern = TA_mural_mural_audit/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
