#
# Splunk app configuration file
#

[install]
is_configured = true

[package]
id = cuviz_status_matrix

[ui]
is_visible = false
label = Status Matrix Custom Viz

[launcher]
author = jzhang@splunk.com
description = status matrix custom viz
version = 1.0.4


