display.visualizations.custom.animated_chart_viz.animated_chart_viz.chartType = bar
display.visualizations.custom.animated_chart_viz.animated_chart_viz.playSpeed = normal
display.visualizations.custom.animated_chart_viz.animated_chart_viz.autoPlay = true
display.visualizations.custom.animated_chart_viz.animated_chart_viz.title = 
display.visualizations.custom.animated_chart_viz.animated_chart_viz.showTimeline = true
display.visualizations.custom.animated_chart_viz.animated_chart_viz.showTimeSlice = true
display.visualizations.custom.animated_chart_viz.animated_chart_viz.alignTitle = center
display.visualizations.custom.animated_chart_viz.animated_chart_viz.yAxisLabel = 
display.visualizations.custom.animated_chart_viz.animated_chart_viz.yAxisMax = none
display.visualizations.custom.animated_chart_viz.animated_chart_viz.yAxisMin = none
display.visualizations.custom.animated_chart_viz.animated_chart_viz.yAxisMaxCustom = 0
display.visualizations.custom.animated_chart_viz.animated_chart_viz.yAxisMinCustom = 100
display.visualizations.custom.animated_chart_viz.animated_chart_viz.xAxisLabel =
display.visualizations.custom.animated_chart_viz.animated_chart_viz.colorTheme = bright
display.visualizations.custom.animated_chart_viz.animated_chart_viz.customColors = #c23531,#2f4554,#61a0a8,#d48265,#91c7ae,#749f83,#ca8622,#bda29a,#6e7074,#546570,#c4ccd3
display.visualizations.custom.animated_chart_viz.animated_chart_viz.dateFormat =  dd-mmm-yyyy hh:mm:ss
display.visualizations.custom.animated_chart_viz.animated_chart_viz.tokenName = ac_name_token
display.visualizations.custom.animated_chart_viz.animated_chart_viz.tokenValue = ac_value_token
display.visualizations.custom.animated_chart_viz.animated_chart_viz.tokentime = ac_time_token
display.visualizations.custom.animated_chart_viz.animated_chart_viz.pieLabelShowPercent = true 
display.visualizations.custom.animated_chart_viz.animated_chart_viz.backgroundColorStyle = auto
display.visualizations.custom.animated_chart_viz.animated_chart_viz.backgroundColorCustom = #212527 
