[animated_chart_viz]
label = Animated Chart Viz
description = See the trend of values animate in a bar, pie, line, or area chart
search_fragment =... | timechart count by host
allow_user_selection = true
disabled = 0
supports_trellis = false
supports_drilldown = true
