[windows_snare_syslog]
MAX_TIMESTAMP_LOOKAHEAD = 32
TRANSFORMS = syslog-host
REPORT-syslog = syslog-extractions
REPORT-colon_1 = snare_colon_1
REPORT-colon_2 = snare_colon_2
#REPORT-colon_3 = snare_colon_3

EXTRACT-Event_ID = (?i)^(?:[^\t]*\t){5}(?P<Event_ID>[^\t]+)
EXTRACT-Event_Log = (?i)^(?:[^\t]*\t){2}(?P<Event_Log>[^\t]+)
EXTRACT-Event_Source = (?i)^(?:[^\t]*\t){6}(?P<Event_Source>[^\t]+)

SHOULD_LINEMERGE = False
TIME_FORMAT = %b %d %H:%M:%S
