
[expose:TA_splunk_observability_events_settings]
pattern = TA_splunk_observability_events_settings
methods = POST, GET

[expose:TA_splunk_observability_events_settings_specified]
pattern = TA_splunk_observability_events_settings/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET

