[default]
[install]
is_configured = 0
state = enabled

[launcher]
version = 7.0.7
description = This app contains keeps audit of Correlation Search
author = Amit Panjawani

[package]
id = Correlation_Search_Audit

[ui]
is_visible = 1
label = Correlation Search Audit

