[replicationWhitelist]
scmLib = apps/bv_aba/lib/**
configProperties = apps/bv_aba/config/scm-framework.properties

[replicationBlacklist]
scmPython = apps/bv_aba/bin/xm*
#scmPythonBson = apps/bv_aba/bin/bson/**
scmPythonGridfs = apps/bv_aba/bin/gridfs/**
#scmPythonMongo = apps/bv_aba/bin/pymongo/**
#scmPythonDBUtils = apps/bv_aba/bin/saDbUtils*
scmExe = apps/bv_aba/bin/Linux/64bit/xm*
scmMongo = apps/bv_aba/bin/Linux/64bit/mongo*
scmDir = apps/bv_aba/scm
scmAppserver = apps/bv_aba/appserver
scmLog = apps/bv_aba/log
scmStatic = apps/bv_aba/static
lookupActors = apps/bv_aba/lookups/actors.csv
lookupAssets = apps/bv_aba/lookups/assets.csv
lookupDataDictionary = apps/bv_aba/lookups/data-dictionary.json
lookupResourceMappings = apps/bv_aba/lookups/resource-mapping.json
configDataDictionary = apps/bv_aba/config/data-dictionary*.json
configResourceMappings = apps/bv_aba/config/resource-mapping*.json
configDefaultProps = apps/bv_aba/config/scm-framework-default.properties
configDbSeedProperties = apps/bv_aba/config/db-seed.properties
tempActorLookups = apps/bv_aba/lookups/*_actorsLookup.csv
