#
# Heatmap
#

[install]
is_configured = 1
build = 2

[ui]
is_visible = true
label = Heatmap

[launcher]
author = Xander Johnson
description = An interactive heatmap visualization.
version = 1.0.1

[package]
id = heatmap_app
