# TODO: should this be exposed, since the command should only be used internally?

# [searchbnf.conf](http://docs.splunk.com/Documentation/Splunk/latest/Admin/Searchbnfconf)

[uceupdatetable-command]
syntax = UCEUPDATETABLE append=<boolean> <usecase_interactions|usecase_bookmark>
alias =
shortdesc = Updates either usecase_interactions or usecase_bookmark tables.
description = \
    For internal use only. Update (overwrite or append) one of the two tables \
    usecase_interactions or usecase_bookmark used for keeping state.
category = streaming
usage = private

