[ui]
is_visible = 1
label = SOLACE: ServiceInsight Model

[id]
version = 1.0.5
name = SOLACE-API-DataModel 

[launcher]
version = 1.0.5
description = Solsys API CIM for Splunk

[package]
id = SOLACE-API-DataModel
check_for_updates = 1
