[default]
[script://$SPLUNK_HOME\etc\apps\erabitbucketta\bin\fetch_commits.py]
host = smax
index = bitbucket
interval = 60.0
sourcetype = json_no_timestamp
python.version = python3

[script://./bin/fetch_commits.py]
disabled = 0
interval = 300
sourcetype = json_no_timestamp
source = bitbucket_api
python.version = python3
index = bitbucket

