[eventtype=cisco_nvm_flowdata]
network = enabled
communicate = enabled
listening = enabled
port = enabled
process = enabled
report = enabled
web = enabled

[eventtype=cisco_nvm_sysdata]
network = enabled
communicate = enabled

[eventtype=cisco_nvm_ifdata]
network = enabled
communicate = enabled

[eventtype=cisco_nvm_process]
network = enabled
communicate = enabled
process = enabled
report = enabled

[eventtype=cisco_nvm_osquery]
network = enabled
communicate = enabled

[eventtype=cisco_nvm_eve]
network = enabled
communicate = enabled