#
# SNOW Table for Splunk app configuration file
#

[main]

# ServiceNow URL, for example, https://myaccount.service-now.com
snow_url=

# ServiceNow user
snow_user=

# ServiceNow timeout
snow_timeout=60

# Proxy enable
proxy_enabled=no

# Proxy Type
proxy_type=http

# Proxy IP address
proxy_host=

# Proxy port
proxy_port=


