[logging]
log_level = info

[network]
proxy =

[ip_risk_list]
enabled = true
interval = 3600
max_entries = 25000

[domain_risk_list]
enabled = true
interval = 3600
max_entries = 25000

[hash_risk_list]
enabled = true
interval = 86400
max_entries = 25000

[vulnerability_risk_list]
enabled = true
max_entries = 25000
interval = 86400
