[install]
is_configured = 0
build = 1748111463

[ui]
is_visible = 0
label = Sunburst Viz

[launcher]
author = Chris Younger
description = Sunburst Viz
version = 1.4.8

[package]
id = sunburst_viz
check_for_updates = true