[Success events in the last 24 hours]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit RETURNCODE="0"
dispatch.earliest_time = -24h@h

[Failed events in the last 24 hours]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit RETURNCODE!="0"
dispatch.earliest_time = -24h@h

[Event type: Session info]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventtype="Session info"
dispatch.earliest_time = -24h@h

[Event type: Administrative action]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventtype="Administrative action"
dispatch.earliest_time = -24h@h

[Event type: User action]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventtype="User action"
dispatch.earliest_time = -24h@h

[Event type: Metadata change]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventtype="Metadata change"
dispatch.earliest_time = -24h@h

[Event class: User]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventclass="User"
dispatch.earliest_time = -24h@h

[Event class: Role]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventclass="Role"
dispatch.earliest_time = -24h@h

[Event class: Profile]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventclass="Profile"
dispatch.earliest_time = -24h@h

[Event class: Data]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventclass="Data"
dispatch.earliest_time = -24h@h

[Event class: Object Privilege]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventclass="Object Privilege"
dispatch.earliest_time = -24h@h

[Event class: User/Role Privilege]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventclass="User/Role Privilege"
dispatch.earliest_time = -24h@h

[Event class: System Privilege]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventclass="System Privilege"
dispatch.earliest_time = -24h@h

[Event class: Metadata]
displayview = flashtimeline
request.ui_dispatch_view = flashtimeline
search = index=oracleaudit oracle_eventclass="Metadata"
dispatch.earliest_time = -24h@h

[Top audit actions - pie chart]
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
displayview = charting
request.ui_dispatch_view = charting
search = index="oracleaudit" | top oracle_actionname limit=10

[Top audit event types - pie chart]
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
displayview = charting
request.ui_dispatch_view = charting
search = index="oracleaudit" | top oracle_eventtype limit=10

[Top audit event classes - pie chart]
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
displayview = charting
request.ui_dispatch_view = charting
search = index="oracleaudit" | top oracle_eventclass limit=10

