[source::...ta-xprotect*.log*]
sourcetype = taxprotect:log

[source::...ta_xprotect*.log*]
sourcetype = taxprotect:log

[xprotect_hosts]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
LINE_BREAKER = ({"_id)
INDEXED_EXTRACTIONS = json

[xprotect_hosts_overview]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
LINE_BREAKER = ({"_id)
INDEXED_EXTRACTIONS = json

[xprotect_events]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
LINE_BREAKER = ({"_id)
INDEXED_EXTRACTIONS = json

[xprotect_auditlogs]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
LINE_BREAKER = ({"_id)
INDEXED_EXTRACTIONS = json

[xprotect_tenant_statistics]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
LINE_BREAKER = ({"_id)
INDEXED_EXTRACTIONS = json

