[source::.../openam/log/*]
SHOULD_LINEMERGE = false
KV_MODE = none
LOOKUP-message_for_openam_logs = openam_logs_message_lookup MessageID OUTPUT Message,Description,Triggers,Actions,Data_fields
REPORT-openamlogs = openam_logs_parsing,openam_logs_parsing2,fieldsplit_MessageID,username_for_openam
EVAL-Username = coalesce(Username,LoginID)
EVAL-ServiceORModule = if(Message_Type="AUTHENTICATION",mvindex(Data_values,2),null)

[SAML2]
SHOULD_LINEMERGE = false
KV_MODE = none
REPORT-xml_fields = parse_xml1,parse_xml2,parse_sid,parse_destination_protocole_URL,parse_recipient_sp
