[script://./bin/rss_traffic.sh]
interval = 1800
sourcetype = rssfeed
source = rss_traffic
disabled = false


# Windows

[script://.\bin\rss_traffic.bat]
interval = 1800
sourcetype = rssfeed
source = rss_traffic
disabled = true
