[script://./bin/rss_nfl.sh]
interval = 86400
sourcetype = rssfeed
source = rss_nfl
disabled = false

[script://./bin/rss_espn_college.sh]
interval = 86400
sourcetype = rssfeed
source = rss_espn_football
disabled = false


# Windows

[script://.\bin\rss_nfl.bat]
interval = 86400
sourcetype = rssfeed
source = rss_nfl
disabled = true

[script://.\bin\rss_espn_college.bat]
interval = 86400
sourcetype = rssfeed
source = rss_espn_football
disabled = true




