[object_attrs]
CLEAN_KEYS = 0
REGEX = Product:(?<object_attrs>.*?)--
SOURCE_KEY = Message

# FOR NNDC ONLY
[removeheaderrow]
REGEX = ^\"#.*
DEST_KEY = queue
FORMAT = nullQueue


[REPORT-JobSizes]
DELIMS = ","
FIELDS = "DateTime","JobName","SizeInGB","DataSizeInGB","JobID","VmCount"

[REPORT-JobDET]
DELIMS = ","
FIELDS = "JobKickOffTime","JobName","TransferedGB","Duration","JobID","TotalSizeGB","TotalUsedSizeGB","TransferSpeedMB","BackupStatus","JobType","JobEndTime"

[REPORT-vbrsize]
DELIMS = ","
FIELDS = "DateTime", "Name","Path","FreeSpace","TotalSpace","Id"

[REPORT-JobTsk]
DELIMS = ","
FIELDS = "DateTime", "Id","Name","JobName","JobSessId","Status","Reason"

[REPORT-BkpSvr]
DELIMS = ","
FIELDS = "DateTime","Name","Info","Type","APIVersion"


[REPORT-BkpPxy]
DELIMS = ","
FIELDS = "DateTime","Name","Host","Type","IsDisabled","Description"

# NNDC END CONFIG

[gpg13_controls]
batch_index_query = 0
case_sensitive_match = 1
filename = gpg13_controls.csv

[gpg13_req_dms]
batch_index_query = 0
case_sensitive_match = 1
filename = gpg13_req_dm.csv

