# (c) 2009 The Splunk Community 
# Tasks are done in the order they are listed here.  Index your data before searching on it.

[ourData]
type = index
datasetDirectory = /tmp/foo
# "stopAtEventCount" is optional
stopAtEventCount = 314159

[bigOne]
type = search
query = * | stats count
# "parallelSearchRaces" is optional
parallelSearchRaces = 1,4,16
