
[expose:TA_openweather_add_on_for_splunk_settings]
pattern = TA_openweather_add_on_for_splunk_settings
methods = POST, GET

[expose:TA_openweather_add_on_for_splunk_settings_specified]
pattern = TA_openweather_add_on_for_splunk_settings/*
methods = POST, GET, DELETE

[expose:TA_openweather_add_on_for_splunk_current_and_forecast_weather_data]
pattern = TA_openweather_add_on_for_splunk_current_and_forecast_weather_data
methods = POST, GET

[expose:TA_openweather_add_on_for_splunk_current_and_forecast_weather_data_specified]
pattern = TA_openweather_add_on_for_splunk_current_and_forecast_weather_data/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
