[vmware_cb_edr_base_index]
definition = eventtype=vmware_cb_edr_base_index
iseval = 0

[vmware_alert_action_tenant_dropdown]
definition = rest splunk_server=local /services/configs/conf-tenants | fields api_key comment org_key guid tenant | eval title = org_key . "/" . api_key." (".tenant.")" | fields guid title | append [|makeresults count=1 |eval guid="", title="Global" | fields - _time]

[cb_edr_new_binaries]
definition = `vmware_cb_edr_base_index` type=binaryinfo.observed

[cb]
definition = `vmware_cb_edr_base_index`

[vmware_cb_edr_hc_severity(2)]
args = compare, level
definition = eval severity_level = case(total_failures == $compare$, 0, total_failures > $compare$, $level$)

[vmware_cb_edr_hc_errors]
definition = search index=_internal sourcetype=vmware* log_level="ERROR"| `vmware_cb_edr_hc_is_recent` | stats count by host msg | rename host as instance, msg as message, count as total_failures | `vmware_cb_edr_hc_severity(0,3)`

[vmware_cb_edr_hc_generic_alert(3)]
args = severity, failures, message
definition = makeresults | eval instance="all", message="$message$", severity_level=$severity$, total_failures=$failures$

[vmware_cb_edr_hc_is_recent]
definition = eval is_recent = now() - (3600 * 24 * 5), is_recent = if(_time > is_recent,"true", "false") | search is_recent="true"
