[admin:bhosts_setup]
match=/bhosts
members=bhosts_setup

[admin_external:bhosts_setup]
python.version = python3
python.required = 3.9, 3.13
handlerfile = setup_endpoint.py
handleractions = edit
handlertype = python