[install]
is_configured = 0

[id]
name = TA-entra-id-group-lookup
version = 1.0.3

[launcher]
author = Eric Jorgensen
description = External lookup for resolving Microsoft Entra ID group memberships through Microsoft Graph.
version = 1.0.3

[ui]
is_visible = 0
label = Microsoft Entra ID Group Lookup
setup_view = setup

[package]
id = TA-entra-id-group-lookup

[triggers]
reload.entra_id_lookup = simple
