[strikeready]
homePath=$SPLUNK_DB/strikeready/db
coldPath=$SPLUNK_DB/strikeready/colddb
thawedPath=$SPLUNK_DB/strikeready/thaweddb

[strikeready_taxii2.1]
homePath=$SPLUNK_DB/strikeready_taxii2.1/db
coldPath=$SPLUNK_DB/strikeready_taxii2.1/colddb
thawedPath=$SPLUNK_DB/strikeready_taxii2.1/thaweddb