[ml_events_by_sourcetype_1h]
batch_index_query = 0
case_sensitive_match = 1
filename = ml_events_by_sourcetype_1h.csv

[ml_events_by_sourcetype_24h]
batch_index_query = 0
case_sensitive_match = 1
filename = ml_events_by_sourcetype_24h.csv

[ml_events_by_host_1h]
batch_index_query = 0
case_sensitive_match = 1
filename = ml_events_by_host_1h.csv

[ml_events_by_host_24h]
batch_index_query = 0
case_sensitive_match = 1
filename = ml_events_by_host_24h.csv

[ml_events_by_search_1h]
batch_index_query = 0
case_sensitive_match = 1
filename = ml_events_by_search_1h.csv

[ml_events_by_search_24h]
batch_index_query = 0
case_sensitive_match = 1
filename = ml_events_by_search_24h.csv

[ml_results_by_search_1h]
batch_index_query = 0
case_sensitive_match = 1
filename = ml_results_by_search_1h.csv

[ml_results_by_search_24h]
batch_index_query = 0
case_sensitive_match = 1
filename = ml_results_by_search_24h.csv
