[ccx_ftnt_fortigate_malware]
search = (sourcetype=fortigate_utm OR sourcetype=fgt_utm) subtype=virus vendor_action!=analytics NOT verdict=clean NOT verdict="submission failed" NOT (category="FileFilter" AND signature="FileFilter" AND virus="FileFilter" AND virusid="0") NOT (category="fortisandbox" AND vendor_eventtype="analytics" AND ( NOT signature="*"))
#tags = malware attack

[ccx_ftnt_fortigate_malware_operations]
search = (sourcetype=fortigate_utm OR sourcetype=fgt_utm) subtype=virus file_hash="*" NOT eventtype IN("ccx_ftnt_fortigate_malware")
#tags = malware operations

[ccx_ftnt_fortigate_webfilter_alert]
search = (sourcetype=fortigate_utm OR sourcetype=fgt_utm) subtype=webfilter severity IN("high","critical")
#tags = alert