[ui]
is_visible = 1
setup_view = setup
label = IBM Security Guardium Insights for Splunk

[install]
is_configured = 0

[launcher]
author = IBM
description = Guardium Insights for Splunk.
version = 3.3.1

[package]
id = gi_for_splunk

[id]
version = 3.3.1
name = gi_for_splunk