# this add-on is powered by splunk Add-on builder

[id]
name = TA-ardoq-audit 
version = 1.0.0

[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 1

[launcher]
author = Rotimi
version = 1.0.0
description = It collects audit logs from Ardoq

[ui]
is_visible = 1
label = Add-on for Ardoq-audit
docs_section_override = AddOns:released

[package]
id = TA-ardoq-audit

[triggers]
reload.addon_builder = simple
reload.ta_ardoq_audit_account = simple
reload.ta_ardoq_audit_settings = simple
reload.passwords = simple
