
[expose:TA_ardoq_audit_account]
pattern = TA_ardoq_audit_account
methods = POST, GET

[expose:TA_ardoq_audit_account_specified]
pattern = TA_ardoq_audit_account/*
methods = POST, GET, DELETE

[expose:TA_ardoq_audit_settings]
pattern = TA_ardoq_audit_settings
methods = POST, GET

[expose:TA_ardoq_audit_settings_specified]
pattern = TA_ardoq_audit_settings/*
methods = POST, GET, DELETE

[expose:TA_ardoq_audit_ardoq_audit_logs]
pattern = TA_ardoq_audit_ardoq_audit_logs
methods = POST, GET

[expose:TA_ardoq_audit_ardoq_audit_logs_specified]
pattern = TA_ardoq_audit_ardoq_audit_logs/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
