# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 10

[launcher]
author = Claroty
version = 1.2.1
description = Use the Claroty Add-On to retrieve device data and alerts from Claroty repositories into Splunk

[ui]
is_visible = 1
label = Claroty xDome add-on for Splunk
docs_section_override = AddOns:released

[package]
id = TA-claroty-xdome-add-on-for-splunk

[triggers]
reload.addon_builder = simple
reload.ta_claroty_xdome_add_on_for_splunk_account = simple
reload.ta_claroty_xdome_add_on_for_splunk_settings = simple
reload.passwords = simple

[id]
name = TA-claroty-xdome-add-on-for-splunk
version = 1.2.1
