[script:SA_expressway_cdr_shunt]
handler = SA_expressway_cdr_shunt.SaExpresswayCdrShuntHandler
match = /SA_expressway_cdr_shunt
output_modes = json, xml
passHttpCookies = true
passHttpHeaders = true
passPayload = true
passSession = true
requireAuthentication = true
script = shunt/SA_expressway_cdr_shunt.py
scripttype = persist
python.version  = python3
python.required = 3.9, 3.13