[role_tc_admin]
cumulativeRTSrchJobsQuota = 0
cumulativeSrchJobsQuota = 0
importRoles = user
list_storage_passwords = enabled
schedule_search = enabled
srchIndexesAllowed = *
srchIndexesDefault = main
srchMaxTime = 0
