[install]
state_change_requires_restart = true
is_configured = false
state = enabled
build = 1

[launcher]
author = Airwind
description = MITRE ATLAS Heatmap visualization
version = 1.0.1

[ui]
is_visible = 0
label = MITRE ATLAS Heatmap for Splunk

[id]
name = mitre_atlas_heatmap
version = 1.0.1

[package]
id = mitre_atlas_heatmap
