#
# Splunk app configuration file
#

[install]
state_change_requires_restart = true
build = 26

[ui]
is_visible = 1
label = Dell EMC PowerFlex App for Splunk

[launcher]
author = Crest Data Systems
description = The Dell EMC PowerFlex App for Splunk provides dashboards to visualize PowerFlex Systems and also shows historical performance of the PowerFlex systems.
version = 1.0.0

[package]
id = dell_powerflex_app_for_splunk