[clockify_users]
python.version = python3

[clockify_workspace]
python.version = python3

[clockify_usergroups]
python.version = python3

[clockify_timeentries]
python.version = python3

[clockify_tags]
python.version = python3

[clockify_supporttasks]
python.version = python3

[clockify_projects]
python.version = python3

[clockify_client]
python.version = python3

[clockify_expenses]
python.version = python3

[clockify_invoice]
python.version = python3

