[app_defense_alarm]
search = sourcetype=app_defense_alarms OR sourcetype=_json
[app_defense_network_alarm]
search = (sourcetype=app_defense_alarms OR sourcetype=_json) AND (ruleViolated = INBOUND_CONNECTION OR ruleViolated = OUTBOUND_CONNECTION)

