[nextcloud-serverinfo]
KV_MODE = xml
ANNOTATE_PUNCT = false
SHOULD_LINEMERGE = true

[nextcloud-serverstatus]
KV_MODE = json
ANNOTATE_PUNCT = false
SHOULD_LINEMERGE = true

[nextcloud-log]
KV_MODE = json
category = Application
description=Events from Nextcloud logs
SHOULD_LINEMERGE=false
TRUNCATE=10000

EXTRACT-action = "message":"(?P<ncAction>\w+ \w+)
EXTRACT-failedLoginUser = "message":"Login failed: '(?P<ncUser>\S*\b)'
EXTRACT-AddedToGroup = "message":"User \\"(?P<ncModifiedUser>\S*)\\" added to group \\"(?P<ncGroupName>\S*)\\""

FIELDALIAS-remoteAddr = remoteAddr AS src
FIELDALIAS-app = app AS ncApp
FIELDALIAS-dest = host AS dest
FIELDALIAS-user = user AS src_user

EVAL-user = coalesce(ncModifiedUser, user)
EVAL-vendor_product = "Nextcloud"
EVAL-app = "nextcloud"

LOOKUP-NextcloudActions = NextcloudActions ncAction AS ncAction OUTPUTNEW action AS action change_type AS change_type object_category AS object_category status AS status