# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 4
install_source_checksum = a7a43954f8c40e7d53dfe63d6861f32cedab8218

[launcher]
author = Exodus Intelligence LLC
version = 0.1.1
description = Retrieve Vulnerabilities from Exodus Intelligence Database

[ui]
is_visible = 1
label = Exodus Eve
docs_section_override = AddOns:released

[package]
id = TA-exodus-eve

[triggers]
reload.addon_builder = simple
reload.ta_exodus_eve_account = simple
reload.ta_exodus_eve_settings = simple
reload.passwords = simple

