# fields.conf

[tenant_id]
INDEXED = true
INDEXED_VALUE = true

[object]
INDEXED = true
INDEXED_VALUE = true

[object_category]
INDEXED = true
INDEXED_VALUE = true

[monitored_state]
INDEXED = true
INDEXED_VALUE = true
