
[expose:TA_forza_telemetry_settings]
pattern = TA_forza_telemetry_settings
methods = POST, GET

[expose:TA_forza_telemetry_settings_specified]
pattern = TA_forza_telemetry_settings/*
methods = POST, GET, DELETE

[expose:TA_forza_telemetry_forza_udp]
pattern = TA_forza_telemetry_forza_udp
methods = POST, GET

[expose:TA_forza_telemetry_forza_udp_specified]
pattern = TA_forza_telemetry_forza_udp/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
