##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##

[default]
[Azure Subscriptions Lookup]
search = `azure-index` sourcetype="azure:subscriptions" | stats count by subscriptionId, displayName | inputlookup lookup_subscriptions append=true | stats count by subscriptionId, displayName | fields - count | outputlookup lookup_subscriptions
alert.suppress = 0
cron_schedule = 0 */24 * * *
alert.track = 0
alert.digest_mode = 1
display.general.type = statistics
display.page.search.tab = statistics
dispatch.latest_time = @h
run_on_startup = 1
enableSched = 1
request.ui_dispatch_view = search
dispatch.earliest_time = -48h@h
schedule_window = auto
