[sc_plugin_data_lookup]
collection = sc_plugin_data_lookup
external_type = kvstore
fields_list = plugin_id, plugin_name, vpr_score, plugin_family_id, plugin_family, plugin_version, risk_factor, plugin_synopsis, plugin_solution, plugin_publication_date, plugin_modification_date

[sc_asset_data_lookup]
collection = sc_asset_data_lookup
external_type = kvstore
fields_list = ip, SC_address, bios_uuid, dns_name, last_authenticated_scan_date, last_unauthenticated_scan_date, mac_address, mcafee_epo_guid, netbios_name, os_cpe, repository_id, source, asset_exposure_score, acr_score, policy_name, uuid

[sc_vuln_data_lookup]
collection = sc_vuln_data_lookup
external_type = kvstore
fields_list = plugin_id, port, protocol, synopsis, solution, state, first_found, last_found, last_fixed, severity, vpr_score, repository_id, ip, SC_address, dns_name

[io_plugin_data_lookup]
collection = io_plugin_data_lookup
external_type = kvstore
fields_list = plugin_id, plugin_name, vpr_score, plugin_family, plugin_version, risk_factor, plugin_synopsis, plugin_solution, plugin_publication_date, plugin_modification_date

[io_asset_data_lookup]
collection = io_asset_data_lookup
external_type = kvstore
fields_list = uuid, agent_names, fqdns, hostnames, sources, system_types, ipv4, ipv6, mac_address, aes, acr, acr_score, exposure_score, state, last_seen

[io_vuln_data_lookup]
collection = io_vuln_data_lookup
external_type = kvstore
fields_list = plugin_id, asset_uuid, port, protocol, synopsis, solution, state, first_found, last_found, last_fixed, severity, vpr_score, dns_name, data_source

[nnm_vuln_data_lookup]
collection = nnm_vuln_data_lookup
external_type = kvstore
fields_list = plugin_id, protocol, src_port, dest_port, severity, src_ip, dest_ip

[was_vulnerability_data_lookup]
collection = was_vulnerability_data_lookup
external_type = kvstore
fields_list = IO_address, asset_fqdn, asset_uuid, finding_id, first_found, last_found, last_observed, ipv4, ipv6, plugin_id, plugin_name, risk_factor, plugin_synopsis, scan_uuid, scan_completed, severity, url, vendor_severity, state, plugin_publication_date

[ot_vuln_data_lookup]
collection = ot_vuln_data_lookup
external_type = kvstore
fields_list = OT_address, assetId, output, pluginId, port, protocol, status, svcName, scan_time, id

[was_assets_data_lookup]
collection = was_assets_data_lookup
external_type = kvstore
fields_list = acr_score, exposure_score, state, network_fqdns, uuid, types, updated_at

[asm_assets_data_lookup]
collection = asm_assets_data_lookup
external_type = kvstore
fields_list = ip_address, record_type, severity_ranking, hostname, cves, last_metadata_change, id

[sc_mobile_assets_data_lookup]
collection = sc_mobile_assets_data_lookup
external_type = kvstore
fields_list = model, identifier, score, serial, timefield

[ot_assets_data_lookup]
collection = ot_assets_data_lookup
external_type = kvstore
fields_list = category, severity, direct_ip, type, super_type, direct_mac, id, run_status, state, vendor, name, first_seen, last_seen, last_update
