[script://$SPLUNK_HOME/etc/apps/nordpass_activities_app/bin/nordpass_activities_app.py]
interval = 60
sourcetype = nordpass:activities
index = main
disabled = false
passAuth = splunk-system-user
python.version = python3