# Lenovo XClarity Orchestrator Tool

[launcher]
author = Lenovo Group Ltd.
description = Lenovo XClarity Orchestrator Application
version = 1.0.0

[package]
check_for_updates = 1
id = lenovo_lxco

[install]
state = enabled
state_change_requires_restart = true 
is_configured = false
build = 2
allows_disable = true

[ui]
is_visible = 1
label = Lenovo XClarity Orchestrator
