[agari:bp:alerts]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999
# CIM Mapping
EVAL-app = "agari"
FIELDALIAS-body = event_data.summary as body
FIELDALIAS-id = event_data.id as id
EVAL-type = "alert"
FIELDALIAS-dest_category = event_data.alert_type as dest_category

[agari:bp:status]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:bp:threatfeeds]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:bp:failures]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pd:policy_events]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pd:messages]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999
EXTRACT-attack_type = \"attack_class\":\s?{\"(?<attack_type>\S+?)\"
# CIM Mapping
EVAL-vendor_product = "Agari Phishing Defense"
FIELDALIAS-internal_message_id = event_data.id as internal_message_id
FIELDALIAS-message_id = event_data.message_id as message_id
FIELDALIAS-message_info = event_data.authentication_results as message_info
FIELDALIAS-orig_src = event_data.sending_ip_address.ip as orig_src
FIELDALIAS-orig_recipient = event_data.from as orig_recipient
FIELDALIAS-recipient = event_data.from as recipient
FIELDALIAS-recipient_domain = event_data.from_domain as recipient_domain
FIELDALIAS-subject = event_data.subject as subject
FIELDALIAS-file_hash = event_data.attachment_sha256 as file_hash
FIELDALIAS-file_name = event_data.attachment_filenames as file_name
FIELDALIAS-uris = event_data.uris{} as url

[agari:pd:status]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pr:status]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pr:investigation_details]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pr:messages]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pr:ips]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pr:attachments]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pr:domains]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pr:uris]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[agari:pr:tags]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
TRUNCATE = 99999999

[source::...ta-agari*.log*]
SHOULD_LINEMERGE = true
sourcetype = ta:agari:logs

[source::...ta_agari*.log*]
SHOULD_LINEMERGE = true
sourcetype = ta:agari:logs
