
[admin:TA_agari]
match = /
members = TA_agari_account, TA_agari_settings, TA_agari_agari_bp, TA_agari_agari_pd, TA_agari_agari_pr

[admin_external:TA_agari_account]
handlertype = python
handlerfile = TA_agari_rh_account.py
handleractions = edit, list, remove, create
python.version = python3

[admin_external:TA_agari_settings]
handlertype = python
handlerfile = TA_agari_rh_settings.py
handleractions = edit, list
python.version = python3

[admin_external:TA_agari_agari_bp]
handlertype = python
handlerfile = TA_agari_rh_agari_bp.py
handleractions = edit, list, remove, create
python.version = python3

[admin_external:TA_agari_agari_pd]
handlertype = python
handlerfile = TA_agari_rh_agari_pd.py
handleractions = edit, list, remove, create
python.version = python3

[admin_external:TA_agari_agari_pr]
handlertype = python
handlerfile = TA_agari_rh_agari_pr.py
handleractions = edit, list, remove, create
python.version = python3