[haversine(6)]
args = hav_input_lat1,hav_input_lon1,hav_input_lat2,hav_input_lon2,hav_unit,hav_output_field
definition = eval hav_lat1_radians = pi()*$hav_input_lat1$/180, hav_lat2_radians=pi()*$hav_input_lat2$/180, hav_delta_lat_radians = pi()* ($hav_input_lat2$-$hav_input_lat1$)/180, hav_delta_lon_radians= pi()*($hav_input_lon2$-$hav_input_lon1$)/180 \
| eval hav_intermediate = pow(sin(hav_delta_lat_radians/2), 2) + cos(hav_lat1_radians) * cos(hav_lat2_radians) * pow(sin(hav_delta_lon_radians/2), 2) \
| eval hav_distance = 2 * 6371 * atan2(sqrt(hav_intermediate), sqrt(1-hav_intermediate))\
| eval $hav_output_field$ = case("$hav_unit$"=="km", hav_distance, "$hav_unit$"=="nm", hav_distance*0.53996, "$hav_unit$"=="mi", hav_distance*0.62137, true(), hav_distance) \
| fields - hav_*_radians, hav_intermediate, hav_distance
iseval = 0

[haversine(5)]
args = hav_input_lat1,hav_input_lon1,hav_input_lat2,hav_input_lon2,hav_unit
definition = `haversine($hav_input_lat1$,$hav_input_lon1$,$hav_input_lat2$,$hav_input_lon2$,$hav_unit$, distance)`
iseval = 0

[haversine(4)]
args = hav_input_lat1,hav_input_lon1,hav_input_lat2,hav_input_lon2
definition = `haversine($hav_input_lat1$,$hav_input_lon1$,$hav_input_lat2$,$hav_input_lon2$,"km", distance)`
iseval = 0

[factorial_stirling(1)]
args = stirling_input
definition = round(sqrt(2*pi()*$stirling_input$)*pow($stirling_input$/exp(1), $stirling_input$))
iseval = 0

[factorial_lookup(2)]
args = factorial_lookup_input,factorial_lookup_output
definition = lookup factorial input as "$factorial_lookup_input$" OUTPUT factorial as "$factorial_lookup_output$"
iseval = 0

[nCk(3)]
args = nck_n, nck_k, nck_output
definition = eval nck_difference = $nck_n$ - $nck_k$ \
| `factorial_lookup($nck_n$, nck_n_factorial)`\
| `factorial_lookup($nck_k$, nck_k_factorial)`\
| `factorial_lookup(nck_difference, nck_difference_factorial)`\
| eval $nck_output$ = nck_n_factorial / (nck_k_factorial * nck_difference_factorial)\
| fields - nck_n_factorial, nck_k_factorial, nck_difference, nck_difference_factorial
iseval = 0

[nPk(3)]
args = npk_n, npk_k, npk_output
definition = eval npk_difference = $npk_n$ - $npk_k$\
| `factorial_lookup($npk_n$, npk_n_factorial)`\
| `factorial_lookup(npk_difference, npk_diff_factorial)`\
| eval $npk_output$ = npk_n_factorial/npk_diff_factorial\
| fields - npk_difference, npk_n_factorial, npk_diff_factorial
iseval = 0

