[launcher]
version = 2.0.4
description = Add-on to collect Redfish data
author = Dean Jackson, Kyle Prins & Sebastian Schimper

[id]
version = 2.0.4
name = TA-redfish-add-on-for-splunk

[install]
build = 1707288567
is_configured = false
state = enabled

[package]
id = TA-redfish-add-on-for-splunk
check_for_updates = true

[ui]
label = Redfish add-on for Splunk
is_visible = true

[triggers]
reload.ta_redfish_add_on_for_splunk_settings = simple
reload.ta_redfish_add_on_for_splunk_account = simple

