# Connections to external elastic servers
[DEFAULT] 
#default settings for all stanzas.  Note [default] or no-stanza not supported
protocol = http|https
host = <hostname>
port = <int>


#default elastic server to communicate with
[elasticserver]

# Elastic 8+ comes up with security by default, with authentication and running
# https with autogenerated cert, 7 and eaarlier do not.  Your local elastic
# deployment will of course determine the settings you need to use.
protocol = http|https
host = <hostname>
port = <int>

# An optional certfile can be specified to use when making https connections
# to verify the server-provided certificate.  This is typical when using
# self-signed certificates.
# This is not a client certificate.
certfile = <path>|

# apikey is optional.  If elastic server is set up to not require authentication, this can be omitted
apikey = <base64 encoded apikey>|

# additional alternates can be configured to communicate with other elastic
# servers
[elasticserver:<tagname>]
protocol = http|https 
host = <hostname>
port = <int>

certfile = <path>|
apikey = <api_key, base64 encoded>|
