#
# Splunk app configuration file
#
[author]
email = support@oscontext.com
company = Open Source Context

#[id]
#group = Splunk_TA 
#name = OSContext
#version = 1.0.1


[install]
is_configured = 0

[ui]
is_visible = 1
label = Open Source Context

[launcher]
description = Open Source Context API connnector
version = 1.0.1

[package]
id = Splunk_TA_OSContext
