[cr_auth]
search = index=* sourcetype=cyberoam (log_component=GUI OR log_component=CLI) (log_subtype=Admin OR log_subtype=Authentication) log_id="*17507"

[cr_traffic]
search = index=* sourcetype=cyberoam log_component="Firewall Rule"
