#
[success_detail]
definition = | rex field=_raw "\"owner_name=\"(?P<owner>.*)\"\"\saction_name" \
	| transaction search_name maxpause=10s \
	| stats count by _time search_name ticket owner pid \
	| fields - count \
	| rename search_name as savedsearch_name \
	| join type=left savedsearch_name \
	[ search eventtype=scheduler \
	| stats count by savedsearch_name result_count] \
	| table _time savedsearch_name ticket owner pid result_count \
	| rename savedsearch_name as "Alert Name" \
	| sort - _time
iseval = 0

[payload_detail]
definition = | rex field=_raw "\"payload=(?P<payload>.*)\saction_name" \
	\
	| transaction search_name maxpause=10s \
	| stats count by _time payload \
	| fields - count
iseval = 0

[failure_detail]
definition = | rex field=_raw "\"response=(?P<response>.*\n.*)\saction_name" \
	| rex field=_raw "\"owner_name=\"(?P<owner>.*)\"\"\saction_name" \
	| transaction search_name maxpause=10s \
	| stats count by _time search_name owner response pid \
	| fields - count \
	| rename search_name as savedsearch_name \
	| join type=left savedsearch_name \
	[ search eventtype=scheduler \
	| stats count by savedsearch_name result_count] \
	| table _time savedsearch_name response owner pid result_count \
	| rename savedsearch_name as "Alert Name" \
	| sort - _time
iseval = 0

