############CCX Sophos Central##########################################################

##Mod sourcetypes CCX Sophos Central##
#sophos_alerts                       #
#sophos_events                       #
#sophos_tenants                      #
#sophos_endpoints                    #
######################################

[set_sophos_alerts]
REGEX = .
FORMAT = sourcetype::ccx:sophos:central:alerts
DEST_KEY = MetaData:Sourcetype
WRITE_META = true

[set_sophos_events]
REGEX = .
FORMAT = sourcetype::ccx:sophos:central:events
DEST_KEY = MetaData:Sourcetype
WRITE_META = true

[set_sophos_tenants]
REGEX = .
FORMAT = sourcetype::ccx:sophos:central:tenants
DEST_KEY = MetaData:Sourcetype
WRITE_META = true

[set_sophos_endpoints]
REGEX = .
FORMAT = sourcetype::ccx:sophos:central:endpoints
DEST_KEY = MetaData:Sourcetype
WRITE_META = true

[event_vendor_action]
CLEAN_KEYS = 0
REGEX = \w+::(\w+::)+(?P<vendor_action>[^|"]+)

[sophos_central_vendor_actions]
batch_index_query = 0
case_sensitive_match = 1
filename = sophos_central_vendor_actions.csv

[ccx_sophos_central_malware_file]
CLEAN_KEYS = 0
REGEX = .+Malware\sdetected\:\s.+at\s\'(?<x_file_path>[^\']+(?:\\(?<x_file_name>[^\']+)))\'.+
