
[admin:TA_whatsapp_alert_action]
match = /
members = TA_whatsapp_alert_action_settings

[admin_external:TA_whatsapp_alert_action_settings]
handlertype = python
python.version = python3
handlerfile = TA_whatsapp_alert_action_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true
