# Blue Shark blueshark.conf
# Copyright 2015 Wereshark, Inc. All rights reserved
[configuration]
copyright = Copyright 2015 Wereshark, Inc. All rights reserved
edition = basic
version = 1.0
app_name = blueshark
app_name_full_display = Blue Shark Basic
app_doc_prefix = BlueSharkBasic
