# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 25

[launcher]
author = Gary Croker
version = 1.0.3
description = Collect certificate information for domains. Intended to run in single instance mode and collect high numbers of certificates a day.

[ui]
is_visible = 1
label = Certificates-expiry
docs_section_override = AddOns:released

[package]
id = TA-certificates-expiry

[triggers]
reload.addon_builder = simple
reload.ta_certificates_expiry_account = simple
reload.ta_certificates_expiry_settings = simple
reload.passwords = simple
