[radar]
is_custom = 1
disabled = 0
label = RADAR Alert Action
description = Creates an open incident in RADAR Incident Management Platform
icon_path = radar_alert_action.png
payload_format = json

param.radar_url = https://api.radarfirst.com/
param.radar_incident_name = Splunk Alert from '$name$'
param.radar_incident_description = Splunk Alert on $trigger_date$ at $trigger_timeHMS$.
