[converttera(1)]
args = bytes
definition = Round($bytes$/1099511627776, 2)
iseval = 0
description = This macro is converting bytes to terabytes

[nutanixpc]
definition = index = nutanixpc
iseval = 0

[nutanixpc_index]
definition = index = nutanixpc
iseval = 0

[nutanixpc_syslog_index]
definition = index = nutanixpc
iseval = 0

[get_clusters(1)]
args = pc_ip
definition = if("$pc_ip$"!="all", "pc_ip=\"$pc_ip$\"", "")
iseval = 1

