
## Below stanza collect DHCP IPv4 Scope properties
[powershell://DHCP_Collect_scope]
index=windows
sourcetype=dhcpScope:properties
script = ."$SplunkHome\etc\apps\Databl_windows_dhcp\bin\powershell\dhcp_scope_properties.ps1"
schedule = 3600
disabled = 1

## Below stanza collect DHCP IPv4 Scope utilization
[powershell://DHCP_Collect_stats]
index=windows
sourcetype=dhcpScope:stats
script = ."$SplunkHome\etc\apps\Databl_windows_dhcp\bin\powershell\dhcp_scope_stats.ps1"
schedule = 60
disabled = 1

## Below stanza collect DHCP IPv6 Scope properties
[powershell://DHCP_Collect_v6_scope]
index=windows
sourcetype=dhcpScopeV6:properties
script = ."$SplunkHome\etc\apps\Databl_windows_dhcp\bin\powershell\dhcp_scope_properties_ipv6.ps1"
schedule = 3600
disabled = 1

## Below stanza collect DHCP Scope IPv6 utilization
[powershell://DHCP_Collect_v6_stats]
index=windows
sourcetype=dhcpScopeV6:stats
script = ."$SplunkHome\etc\apps\Databl_windows_dhcp\bin\powershell\dhcp_scope_stats_ipv6.ps1"
schedule = 60
disabled = 1



###### DHCP ######
# This input is in the Deafult Splunk windows App - you can enable here , or in the native app
# Dont enable both
[monitor://$WINDIR\System32\DHCP]
disabled = 1
whitelist = DhcpSrvLog*
crcSalt = <SOURCE>
sourcetype = DhcpSrvLog
