[launcher]
version = 1.0.5
description = Splunk Add-on for eMASS. Ingest POA&M data from eMASS.
author = TA-suhlabs-eMASS

[id]
version = 1.0.5
name = TA-suhlabs-eMASS

[install]
build = 1779406228
is_configured = false
state = enabled

[package]
id = TA-suhlabs-eMASS
check_for_updates = true

[ui]
label = TA-suhlabs-eMASS
is_visible = true

[triggers]
reload.ta_suhlabs_emass_settings = simple
reload.ta_suhlabs_emass_account = simple
reload.ta_suhlabs_emass_output = simple
