[source::...ta-riskrecon-api*.log*]
# SHOULD_LINEMERGE = true
sourcetype = tariskreconapi:log

[source::...ta_riskrecon_api*.log*]
# SHOULD_LINEMERGE = true
sourcetype = tariskreconapi:log

[findings:json]
INDEXED_EXTRACTIONS = json
SHOULD_LINEMERGE = false
LINE_BREAKER = (},{)"\w+
MAX_TIMESTAMP_LOOKAHEAD = 19
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
TIME_PREFIX = "last_seen":"
TZ = UTC
category = Splunk App Add-on Builder
pulldown_type = 1

[ratings:json]
LINE_BREAKER = ([\n\r]+)
MAX_TIMESTAMP_LOOKAHEAD = 23
SHOULD_LINEMERGE = 0
TIME_FORMAT = %Y-%m-%d %H:%M:%S %Z
TIME_PREFIX = "analysis_ts":"
TRUNCATE = 999999
category = Splunk App Add-on Builder
pulldown_type = 1

[compliance:json]
DATETIME_CONFIG = CURRENT
KV_MODE = json
LINE_BREAKER = ((,|{"data":\[){"attributes":)
SHOULD_LINEMERGE = false
TZ = UTC

