#
# Keeper.io Add-on for Splunk
#
# File:         props.conf
#
#

[keeper]
SHOULD_LINEMERGE = false
TIME_PREFIX = "created":"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3NZ
MAX_TIMESTAMP_LOOKAHEAD = 30



REPORT-keeper_src_user = keeper_src_user
REPORT-keeper_location = keeper_location
REPORT-keeper_activity = keeper_activity
REPORT-keeper_user = keeper_user
REPORT-keeper_device = keeper_device
REPORT-keeper_authentication_method = keeper_authentication_method
REPORT-keeper_record_uid = keeper_record_uid
REPORT-src_country = keeper_src_country

EVAL-user = coalesce(user,src_user)