[bitsight_index]
definition = index IN (main)
iseval = 0

[bisight_relative_latest_time(1)]
args = time_token.latest
description = To handle now and all time in time filter.
definition = | eval latest=case("$time_token.latest$" == "now", relative_time(now(), "@m"), "$time_token.latest$" == "", relative_time(now(), "@m"), 1 == 1, "$time_token.latest$")
iseval = 0

[bisight_relative_earliest_time(1)]
args = time_token.earliest
description = To handle all time in time filter.
definition = | eval earliest=if(like("$time_token.earliest$", "%-%"), relative_time(now(), "$time_token.earliest$"), "$time_token.earliest$")
iseval = 0