[expose:TA-whatsapp-alert-action_settings]
pattern = TA-whatsapp-alert-action_settings
methods = POST, GET

[expose:TA-whatsapp-alert-action_settings_specified]
pattern = TA-whatsapp-alert-action_settings/*
methods = POST, GET, DELETE
