[ui]
is_visible = 1
label = props.conf Helper

[launcher]
author = vbumgarner
description = Provides helper forms for building efficient time extraction and for apache extracts based on an Apache LogFormat string.
version = 0.5

[install]
state = enabled
build = 1

[package]
id = propshelper

