[default]
[bosch_analytic]
definition = `fabric_bosch_index` sourcetype=fabric:bosch_v1_json Topic="analytic"
iseval = 0

[bosch_counters]
definition = `fabric_bosch_index` sourcetype=fabric:bosch_v1_json Topic="counter" Type IN("counter","occupancy")
iseval = 0

[bosch_crowd]
definition = `fabric_bosch_index` sourcetype=fabric:bosch_v1_json Topic="counter" Type="crowddensity"
iseval = 0

[bosch_del_objects]
definition = `fabric_bosch_index` sourcetype=fabric:bosch_v1_json Topic="object" Type="deletedobj"\
| mvexpand ObjectID{}\
| rename ObjectID{} as ObjectID
iseval = 0

[bosch_fabric]
definition = `fabric_bosch_index` sourcetype=fabric:bosch_v1_json Topic="fabric"
iseval = 0

[bosch_general]
definition = `fabric_bosch_index` sourcetype=fabric:bosch_v1_json Topic="general"
iseval = 0

[bosch_objects]
definition = `fabric_bosch_index` sourcetype=fabric:bosch_v1_json Topic="object" Type="liveobj"
iseval = 0

[bosch_objects_dist]
definition = `fabric_bosch_index` sourcetype=fabric:bosch_v1_json Topic="object" Type="objdist"
iseval = 0

[fabric_bosch_index]
definition = index=netgeniq_bosch_cctv
iseval = 0

