# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = true
is_configured = false
state = enabled
build = 2

[launcher]
author = shanghai it-up information technology co.,ltd
version = 1.0.0
description = NSFOCUS-WAF ADD-ON

[ui]
is_visible = 0
label = nsfocus-waf
docs_section_override = AddOns:released

[package]
id = TA-nsfocus-waf

[triggers]
reload.addon_builder = simple
reload.ta_nsfocus_waf_account = simple
reload.ta_nsfocus_waf_settings = simple
reload.passwords = simple
