#
# Splunk app configuration file
#

[ui]
is_visible = true
label = Splunk for use with AMMAP

[launcher]
author= will@splunk.com
description=The AMMAP Splunk app provides a sample view incorporating ammap geo SWFs and the supporting alert action and search commands for creating the data file

[version=1.0]