# Splunk app configuration file 

[install]
is_configured = 0
build = 100016
state_change_requires_restart = true
install_source_checksum = db60354fb1853c46b763ec1403d22551a3145d14

[ui]
label = Cisco Cloudlock
is_visible = 1

[launcher]
author = CloudLock
description = CloudLock’s CIM-compliant app allows security professionals to manage the cloud security incident lifecycle within Splunk as well as leverage Splunk’s data visualization and reporting functionalities.
version = 1.0.19

[package]
id = cloudlock
check_for_updates = 1
