#
# Configuration for the Aptrinsic library and widget
#

[aptrinsic]
environment = production
http_proxy = https://proxy-web.experienceservices.splunkdev.net
esp_proxy = https://proxy-esp.experienceservices.splunkdev.net
