[maze:investigations]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TIME_PREFIX = "updated_at"\s*:\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%6N%z
MAX_TIMESTAMP_LOOKAHEAD = 40
KV_MODE = json
TRUNCATE = 0

FIELDALIAS-severity = maze_severity AS severity
FIELDALIAS-signature = cve_id AS signature
FIELDALIAS-signature_id = cve_id AS signature_id
FIELDALIAS-cvss = snapshot.cvss.base_score AS cvss
FIELDALIAS-cve = cve_id AS cve
EVAL-vendor_product = "Maze Security"
EVAL-dest = mvindex('related_scanner_findings{}.asset_name', 0)
EVAL-category = "vulnerability"
LOOKUP-severity_order = maze_severity_lookup maze_severity OUTPUT severity_order
