[expose:maze_security_account]
pattern = maze_security_account
methods = POST, GET

[expose:maze_security_account_specified]
pattern = maze_security_account/*
methods = POST, GET, DELETE

[expose:maze_security_settings]
pattern = maze_security_settings
methods = POST, GET

[expose:maze_security_settings_specified]
pattern = maze_security_settings/*
methods = POST, GET, DELETE

[expose:maze_security_maze_investigations_search]
pattern = maze_security_maze_investigations_search
methods = POST, GET

[expose:maze_security_maze_investigations_search_specified]
pattern = maze_security_maze_investigations_search/*
methods = POST, GET, DELETE

[expose:data/indexes]
pattern = data/indexes
methods = GET
