[default]
[install]
is_configured = 0
is_visible = 0
show_in_nav = 0
check_for_updates = false

[launcher]
author = Baharuddin Zulkifli
company = NetbyteSec
description = Add ons for teamviewer log.
version = 1.0.0

[package]
check_for_updates = 1
id = splunk_TA_teamviewer

[ui]
is_visible = 0
label = TA-Teamviewer

