#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 1
label = M5Stack ENV sensor for Splunk

[launcher]
author = NAKAJIMA Takaaki
description = Environmental data measured by M5Stack ENV sensor.
version = 0.1.2

[package]
id = m5stack_env_sensor_for_splunk
check_for_updates = true
