
[install]
is_configured = 0

[launcher]
description = There are several methods one can use to determine the average volume per host, this is another one.
version = 1.5
author = James Donn and Franco Ferrero-Poschetto

[package]
id = data_volume_calculator

[ui]
is_visible = 1
label = Data Volume Calculator

