
[expose:TA_RL_SQS_Poller_rl_sqs_json]
pattern = TA_RL_SQS_Poller_rl_sqs_json
methods = POST, GET

[expose:TA_RL_SQS_Poller_rl_sqs_json_specified]
pattern = TA_RL_SQS_Poller_rl_sqs_json/*
methods = POST, GET, DELETE

[expose:TA_RL_SQS_Poller_settings]
pattern = TA_RL_SQS_Poller_settings
methods = POST, GET

[expose:TA_RL_SQS_Poller_settings_specified]
pattern = TA_RL_SQS_Poller_settings/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
