[scenarios_MITRE]
batch_index_query = 0
case_sensitive_match = 1
filename = scenarios_MITRE.csv
max_matches = 1000
min_matches = 0

[scenario_Sigma]
batch_index_query = 0
case_sensitive_match = 1
filename = scenarios_Sigma.csv

[scenario]
batch_index_query = 0
case_sensitive_match = 1
filename = scenarios.csv

[scenarios_Splunk_AS]
batch_index_query = 0
case_sensitive_match = 0
filename = scenarios_Splunk_AS.csv
