[eventtype=storms_network]
network = enabled
communicate = enabled

[eventtype=storms_web]
web = enabled

[eventtype=storms_virus]
malware = enabled
attack = enabled

[eventtype=storms_ids]
ids = enabled
attack = enabled

[eventtype=storms_auth]
authentication = enabled
