[apl_web_ua_family_field]
definition = ua_family
iseval = 0

[apl_web_user_agent_lookup]
definition = user_agents
iseval = 0

[apl_web_ua_info]
definition = eval apl_web_ua_info = if(isnotnull(ua_family) AND ua_family != "unknown",ua_family,"unknown").if(isnotnull(ua_major) AND ua_major != "unknown", " ".ua_major,"").if(isnotnull(ua_minor) AND ua_minor != "unknown", ".".ua_minor,"").if(isnotnull(ua_patch) AND ua_patch != "unknown", ".".ua_patch,"")
iseval = 0

[apl_web_proxy_tstats]
definition = tstats prestats=false local=false summariesonly=true allow_old_summaries=true
iseval = 0

[apl_web_proxy_tstats_pre]
definition = tstats prestats=true local=false summariesonly=true allow_old_summaries=true
iseval = 0

[apl_web_wfa_lookup]
definition = apl_web_bluecoat_wfa

iseval = 0
