[dxsearchparser-command]
syntax = dxsearchparser (<dxsearchparser-options>)*
shortdesc = Wrapper for the search/parser endpoint
description = Wrapper for the search/parser endpoint
usage = public
example1 = dxsearchparser
comment1 = Passes the contents of the field 'search' to search/parser and returns the results into 'search_expanded'
example2 = dxsearchparser input=spl output=search_parser
comment2 = Passes the contents of the field 'spl' to search/parser and returns the results into 'search_parser'

[dxsearchparser-options]
syntax = input=<string> | output=<string> | app=<string> | owner=<string>
description = The dxsearchparser command is a wrapper for the search/parser endpoint and returns the expanded search.  'input' is the field containing SPL.  'output' is the field returned by the command.  'app' is the field containg the app context.  'owner' is the field containing the owner context.

[dxsearchexpansion-command]
syntax = dxsearchexpansion (<dxsearchexpansion-options>)*
shortdesc = Wrapper for the search/parser endpoint
description = Wrapper for the search/parser endpoint
usage = public
example1 = dxsearchexpansion
comment1 = Passes the contents of the field 'search' to search/parser and returns the results into 'search_expanded'
example2 = dxsearchexpansion input=spl output=search_parser
comment2 = Passes the contents of the field 'spl' to search/parser and returns the results into 'search_parser'

[dxsearchexpansion-options]
syntax = input=<string> | output=<string> | app=<string> | owner=<string>
description = The dxsearchexpansion command is a wrapper for the search/parser endpoint and returns the expanded search.  'input' is the field containing SPL.  'output' is the field returned by the command.  'app' is the field containg the app context.  'owner' is the field containing the owner context.