#GLOBAL ZIMBRA HOST LOGS

#[monitor:///var/log/zimbra.log]
#index=zimbra
#sourcetype=zimbra:zsyslog

#[monitor:///var/log/maillog]
#index=zimbra
#sourcetype=zimbra:postfix

#[monitor:///opt/zimbra/log/audit.log]
#index=zimbra
#sourcetype=zimbra:auditlog

#MBX LOGS
#[monitor:///opt/zimbra/log/access_log.*]
#index=zimbra
#sourcetype=zimbra:mailbox:access 

#[monitor:///opt/zimbra/log/mailbox.log]
#index=zimbra
#sourcetype=zimbra:mailbox

#[monitor:///opt/zimbra/log/zmmailboxd.out]
#index=zimbra

#MTA LOGS

#[monitor:///opt/zimbra/log/freshclam.log]
#index=zimbra
#sourcetype=zimbra:clamd:updates

#[monitor:///opt/zimbra/log/clamd.log]
#index=zimbra
#sourcetype=zimbra:clamd

#[monitor:///opt/zimbra/log/spamtrain.log]
#index=zimbra

#PROXY LOGS

#[monitor:///opt/zimbra/log/nginx.access.log]
#index=zimbra
#sourcetype=zimbra:proxy

#[monitor:///opt/zimbra/log/nginx.error.log]
#index=zimbra
#sourcetype=nginx:plus:error

#[monitor:///opt/zimbra/log/nginx.log]
#index=zimbra

#ZPUSH LOGS

#[monitor:///var/log/httpd/ssl_splunk_access_log]
#index=zimbra
#sourcetype=apache:access:kv

#[monitor:///var/log/httpd/ssl_*_log]
#index=zimbra
