#
# Homepage for Splunk
#

[install]
is_configured = false
build = 102
state_change_requires_restart = true

[ui]
is_visible = 0
label = Homepage for Splunk

[launcher]
author = DiscoveredIntel
description = Homepage for Splunk presents logged in users with a 'virtual cockpit' that provides a single-pane-of-glass view into their specific use of Splunk.
version = 1.0.2

[package]
id = homepage
