
[admin:Splunk_TA_ctm360]
match = /
members = Splunk_TA_ctm360_settings, Splunk_TA_ctm360_hackerview_feeds, Splunk_TA_ctm360_cbs_feeds, Splunk_TA_ctm360_threatcover_feeds

[admin_external:Splunk_TA_ctm360_settings]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = Splunk_TA_ctm360_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:Splunk_TA_ctm360_hackerview_feeds]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = Splunk_TA_ctm360_rh_hackerview_feeds.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:Splunk_TA_ctm360_cbs_feeds]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = Splunk_TA_ctm360_rh_cbs_feeds.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:Splunk_TA_ctm360_threatcover_feeds]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = Splunk_TA_ctm360_rh_threatcover_feeds.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
