[cribldecryptv2-command] 
syntax = cribldecryptv2 (<selfjoin-options>)* <field-list> 
shortdesc = Decrypt data encrypted by Cribl 
description = Decrypt data encrypted by Cribl - applies to all fields as well as encrypted data within a field
usage = public 