
[expose:TA_vuln_db_settings]
pattern = TA_vuln_db_settings
methods = POST, GET

[expose:TA_vuln_db_settings_specified]
pattern = TA_vuln_db_settings/*
methods = POST, GET, DELETE

[expose:TA_vuln_db_vulndb]
pattern = TA_vuln_db_vulndb
methods = POST, GET

[expose:TA_vuln_db_vulndb_specified]
pattern = TA_vuln_db_vulndb/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
