
[expose:TA_acunetix_360_settings]
pattern = TA_acunetix_360_settings
methods = POST, GET

[expose:TA_acunetix_360_settings_specified]
pattern = TA_acunetix_360_settings/*
methods = POST, GET, DELETE

[expose:TA_acunetix_360_vulnerabilitiesfoundbyacunetix]
pattern = TA_acunetix_360_vulnerabilitiesfoundbyacunetix
methods = POST, GET

[expose:TA_acunetix_360_vulnerabilitiesfoundbyacunetix_specified]
pattern = TA_acunetix_360_vulnerabilitiesfoundbyacunetix/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
