[launcher]
author = admin
description = Manage and update apps and add-ons across deployment clients and agents
version = 1.1.0

[ui]
is_visible = 1
label = Deployment and Agent App Version Manager

[package]
id = SA-deployment-app-manager
check_for_updates = true

[id]
name = SA-deployment-app-manager
version = 1.1.0
