[IMAP-messagesLastHour]
action_rss = 0
search = index=_internal series imap eps metrics starthoursago=1 | timechart avg(eps) 
schedule = */2 * * * *
sendresults = 0
userid = 1
dispatch.ttl = 30

[IMAP-topFromLast1000]
action_rss = 0
search = index=mail | head 1000 | top From showperc=false 
schedule = */2 * * * *
sendresults = 0
userid = 1
dispatch.ttl = 30
