[ui]
is_visible = 0
label = SentinelOne


[diag]


[triggers]









[launcher]
author = Aplura, LLC
description = Allows a SentinelOne administrator or analyst interact with the SentinelOne product.
version = 6.1.0

[package]
id = TA-sentinelone_app_for_splunk
check_for_updates = 1

[install]
build = 20251216


[id]
version = 6.1.0
name = TA-sentinelone_app_for_splunk
