
[virsec_data]
coldPath = $SPLUNK_DB\virsec_data\colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB\virsec_data\db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB\virsec_data\thaweddb

[new_index]
coldPath = $SPLUNK_DB\new_index\colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB\new_index\db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB\new_index\thaweddb

[index1]
coldPath = $SPLUNK_DB\index1\colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB\index1\db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB\index1\thaweddb

[veridx]
coldPath = $SPLUNK_DB\veridx\colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB\veridx\db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB\veridx\thaweddb

[eve_idx]
coldPath = $SPLUNK_DB\eve_idx\colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB\eve_idx\db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB\eve_idx\thaweddb

[vir_idx]
coldPath = $SPLUNK_DB\vir_idx\colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB\vir_idx\db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB\vir_idx\thaweddb

[virsec_idx]
coldPath = $SPLUNK_DB\virsec_idx\colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB\virsec_idx\db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB\virsec_idx\thaweddb
