[script:tmcfg_handler]
match                 = /tmcfg_handler
script                = trendmicro_cti_app_cfg_mgr.py
scripttype            = persist
handler               = trendmicro_cti_app_cfg_mgr.TMCFGManager
requireAuthentication = true
output_modes          = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true
python.version        = python3