
[expose:TA_sandfly_security_account]
pattern = TA_sandfly_security_account
methods = POST, GET

[expose:TA_sandfly_security_account_specified]
pattern = TA_sandfly_security_account/*
methods = POST, GET, DELETE

[expose:TA_sandfly_security_settings]
pattern = TA_sandfly_security_settings
methods = POST, GET

[expose:TA_sandfly_security_settings_specified]
pattern = TA_sandfly_security_settings/*
methods = POST, GET, DELETE

[expose:TA_sandfly_security_sandfly_ssh_keys]
pattern = TA_sandfly_security_sandfly_ssh_keys
methods = POST, GET

[expose:TA_sandfly_security_sandfly_ssh_keys_specified]
pattern = TA_sandfly_security_sandfly_ssh_keys/*
methods = POST, GET, DELETE

[expose:TA_sandfly_security_sandfly_hosts]
pattern = TA_sandfly_security_sandfly_hosts
methods = POST, GET

[expose:TA_sandfly_security_sandfly_hosts_specified]
pattern = TA_sandfly_security_sandfly_hosts/*
methods = POST, GET, DELETE

[expose:TA_sandfly_security_sandfly_sandflies]
pattern = TA_sandfly_security_sandfly_sandflies
methods = POST, GET

[expose:TA_sandfly_security_sandfly_sandflies_specified]
pattern = TA_sandfly_security_sandfly_sandflies/*
methods = POST, GET, DELETE

[expose:TA_sandfly_security_sandfly_audit_logs]
pattern = TA_sandfly_security_sandfly_audit_logs
methods = POST, GET

[expose:TA_sandfly_security_sandfly_audit_logs_specified]
pattern = TA_sandfly_security_sandfly_audit_logs/*
methods = POST, GET, DELETE

[expose:TA_sandfly_security_sandfly_error_logs]
pattern = TA_sandfly_security_sandfly_error_logs
methods = POST, GET

[expose:TA_sandfly_security_sandfly_error_logs_specified]
pattern = TA_sandfly_security_sandfly_error_logs/*
methods = POST, GET, DELETE

[expose:TA_sandfly_security_sandfly_alarms]
pattern = TA_sandfly_security_sandfly_alarms
methods = POST, GET

[expose:TA_sandfly_security_sandfly_alarms_specified]
pattern = TA_sandfly_security_sandfly_alarms/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
