
[expose:TA_aiops_magento_account]
pattern = TA_aiops_magento_account
methods = POST, GET

[expose:TA_aiops_magento_account_specified]
pattern = TA_aiops_magento_account/*
methods = POST, GET, DELETE

[expose:TA_aiops_magento_settings]
pattern = TA_aiops_magento_settings
methods = POST, GET

[expose:TA_aiops_magento_settings_specified]
pattern = TA_aiops_magento_settings/*
methods = POST, GET, DELETE

[expose:TA_aiops_magento_magento_logs]
pattern = TA_aiops_magento_magento_logs
methods = POST, GET

[expose:TA_aiops_magento_magento_logs_specified]
pattern = TA_aiops_magento_magento_logs/*
methods = POST, GET, DELETE

[expose:TA_aiops_magento_magento_orders]
pattern = TA_aiops_magento_magento_orders
methods = POST, GET

[expose:TA_aiops_magento_magento_orders_specified]
pattern = TA_aiops_magento_magento_orders/*
methods = POST, GET, DELETE

[expose:TA_aiops_magento_magento_order_updates]
pattern = TA_aiops_magento_magento_order_updates
methods = POST, GET

[expose:TA_aiops_magento_magento_order_updates_specified]
pattern = TA_aiops_magento_magento_order_updates/*
methods = POST, GET, DELETE

[expose:TA_aiops_magento_magento_jobs]
pattern = TA_aiops_magento_magento_jobs
methods = POST, GET

[expose:TA_aiops_magento_magento_jobs_specified]
pattern = TA_aiops_magento_magento_jobs/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET

