[package]
id = duo_splunkapp

[id]
name = duo_splunkapp
version = 2.1.0

[install]
build = 1
is_configured = 0
state_change_requires_restart = true

[ui]
is_visible = 1
label = Duo Security

[launcher]
author = Duo Security
description = The Duo Security App for Splunk enables Duo customers to pull their Account, Activity, Administrator, Authentication, Authentication v2, Telephony, and Telephony v2 logs into Splunk. Duo Premier and Duo Advantage customers can also pull in Trust Monitor logs and Endpoint information.
version = 2.1.0

[triggers]
reload.duo_splunkapp = simple
