[default]
[crowdstrike_scheduled_search_json]
python.version = python3
sourcetype = crowdstrike:scheduledsearch:json
interval = 3600
cloud = us_commercial
collection_option = historic_search
disabled = 0