[Bstn_current]
action.email.reportServerEnabled = 0
alert.suppress = 0
alert.track = 0
dispatch.earliest_time = -15m@m
dispatch.latest_time = now
displayview = report_builder_display
request.ui_dispatch_view = report_builder_display
search = sourcetype=yahoo_weather boston |rex field=_raw "(?i)/weather/(?P<city>\w+)" |rex field=_raw "(?i), (?P<current_temp>\d+) F" |table current_temp |head 1
vsid = *:gmzawtae

[paris_current]
action.email.reportServerEnabled = 0
alert.suppress = 0
alert.track = 0
dispatch.earliest_time = -15m@m
dispatch.latest_time = now
displayview = report_builder_display
request.ui_dispatch_view = report_builder_display
search = sourcetype=yahoo_weather paris |rex field=_raw "(?i)/weather/(?P<city>\w+)" |rex field=_raw "(?i), (?P<current_temp>\d+) F" |table current_temp |head 1
vsid = *:gmzbln77

[Toronto_current]
action.email.reportServerEnabled = 0
alert.suppress = 0
alert.track = 0
dispatch.earliest_time = -15m@m
dispatch.latest_time = now
displayview = report_builder_display
request.ui_dispatch_view = report_builder_display
search = sourcetype=yahoo_weather toronto  | rex field=_raw "(?i)/weather/(?P<city>\w+)"  | rex field=_raw "(?i), (?P<current_temp>\d+) F" |table current_temp |head 1
vsid = *:gmzcg1h0
