# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 17

[launcher]
author = Auguria
version = 1.5.4
description = The Auguria SKL Add-On enables security teams to leverage Auguria's Security Knowledge Layer™ (SKL) enrichment capabilities to identify critical security events and patterns across cohorts of related data.

[ui]
is_visible = 1
label = Auguria SKL Add-On
docs_section_override = AddOns:released

[package]
id = TA-auguria-skl

[triggers]
reload.addon_builder = simple
reload.ta_auguria_skl_account = simple
reload.ta_auguria_skl_settings = simple
reload.passwords = simple

