[region_alias]
filename = checkpoint_dome9_region_aliases.csv

[region_coords]
filename = checkpoint_dome9_region_coordinates.csv

[exclusion_list_lookup]
external_type = kvstore
collection = collection_exclusion_list_from_splunk
fields_list = _key, findingKey, exclude
