[whoisLookup]
python.version = python3
external_cmd = whois_lookup.py ip whois
fields_list = ip,whois

[whoisLookupRedis]
python.version = python3
external_cmd = whois_redis_lookup.py ip whois
fields_list = ip,whois
