[asiainfo:tda]
EXTRACT-asiainfo-cef-head = CEF:(\s|)(?<cef_cefVersion>\d+)\|(?<vendor>[^|]*)\|(?<product>[^|]*)\|(?<version>[^|]*)\|(?<evt_code>[^|]*)\|(?<signature>[^|]*)\|(?<severity_id>[^|]*)
LOOKUP-asiainfor_severity = severity.csv severity_id AS severity_id OUTPUTNEW severity AS severity
FIELDALIAS-asiainfo-ips-alias = act ASNEW action cat ASNEW category dpt ASNEW dest_port dst ASNEW dest spt ASNEW src_port
EXTRACT-aisainfo_ips_action = act=(?P<act>.+)\s*cn3Label
