[install]
is_configured = 0
build = 1695850948

[ui]
is_visible = 1
label = wfence integration App

[launcher]
author = UNeedSecurity GmbH
description = This App works on Network traffic detected by wfence
version = 0.0.2
#version = AUTOBUMPED

[id]
name = wfence_app
version = 0.0.2

[package]
id = wfence_app
check_for_updates = true
