[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 1750858921

[launcher]
author = Splunk Works
version = 1.1.1
description = Splunk Add-on for SFDC streaming API

[ui]
is_visible = true
label = Splunk Add-on for SFDC streaming API
docs_section_override = AddOns:released

[package]
check_for_updates = true
id = TA-sfdc-streaming-api

[triggers]
reload.ta_sfdc_streaming_api_account = simple
reload.ta_sfdc_streaming_api_settings = simple
reload.passwords = simple

[id]
version = 1.1.1
name = TA-sfdc-streaming-api
