[rides]
index = default
start_by_shell = false
sourcetype = rides
interval = 900

[rides://magic_kingdom]
index = main
interval = 900
theme_park = magic_kingdom
disabled = 0

[rides://epcot]
index = main
interval = 900
theme_park = epcot

[rides://hollywood_studios]
index = main
interval = 900
theme_park = hollywood_studios

[rides://animal_kingdom]
index = main
interval = 900
theme_park = animal_kingdom

[rides://disneyland]
index = main
interval = 900
theme_park = disneyland

[rides://universal_studios_florida]
index = main
interval = 900
theme_park = universal_studios_florida

[rides://islands_of_adventure]
index = main
interval = 900
theme_park = islands_of_adventure

