#
# Splunk app configuration file
#
[id]
name = conceal
version = 0.11.2

[install]
is_configured = 0

[ui]
is_visible = 1
label = Conceal Splunk App

[author=Conceal]
email = support@conceal.io
company = Conceal Inc.

[launcher]
description = Conceal Splunk App. Currently supports ConcealBrowse
author = Conceal Inc.
version = 0.11.2

[package]
id = conceal
