[install]
state = enabled
is_configured = 0

[launcher]
author = brett.whynot@gmail.com
version = 0.1.1
description = pfSense ifStats Metrics

[package]
id = TA_pfsense_ifstat

[ui]
label = pfSense ifstat
is_visible = 0

