[rika_firenet]
start_by_shell = false
python.version = python3
sourcetype = rika:firenet
interval = 900
disabled = 0

[rika_firenet://Rika_FILO]
interval = 300
index = rika
stoveid = 57932377
sourcetype = rika:firenet
disabled = 0

