# this add-on is powered by splunk Add-on builder
[launcher]
author = Trifork.Security
version = 1.0.4
description = Makes it possible to change ITSI episode status/severity/owner by using an SPL command: | itsiedit

[ui]
is_visible = 0
label = Trifork.Security ITSI edit command

[package]
id = SA-itsi-edit-command

