[install]
is_configured = false
state = enabled
allows_disable = false

[ui]
is_visible = false
label = JSON Web Token (JWT) Decoder

[id]
version = 1.0.6
name = jwt

[launcher]
author = Michael Jones
description = Decode JSON Web Tokens (JWT) from HTTP Payloads
version = 1.0.6

[package]
id = jwt
check_for_updates = true

