[logging]
loglevel = INFO

[additional_parameters]
loonsecio_base_url = api.loonsec.io
loonsecio_client_id = 
loonsecio_client_secret = 
sla_days_critical = 30
sla_days_high = 30
sla_days_medium = 90
sla_days_low = 180
kv_store_pre_pend = 

