[eventtype=aix_apm]
apm = enabled
performance = enabled
application = enabled

[eventtype=aix_euem]
apm = enabled
performance = enabled
euem = enabled

# Below is an example of Business Process tag definition for Aternity data. _biz suffix is mandatory
# See corresponding Business Process eventtype definition in eventtypes.conf. We recommend using Web UI -> Settings -> Event types
[eventtype=BP-%28Business%20Process%20Example%29]
Business_Process_Example_biz = enabled
