
[admin:TA_trello_import]
match = /
members = TA_trello_import_trello_members, TA_trello_import_trello_boards, TA_trello_import_trello_cards, TA_trello_import_trello_lists, TA_trello_import_settings, TA_trello_import_trello_movements, TA_trello_import_trello_checklists

[admin_external:TA_trello_import_trello_members]
handlertype = python
handlerfile = TA_trello_import_rh_trello_members.py
handleractions = edit, list, remove, create

[admin_external:TA_trello_import_trello_boards]
handlertype = python
handlerfile = TA_trello_import_rh_trello_boards.py
handleractions = edit, list, remove, create

[admin_external:TA_trello_import_trello_cards]
handlertype = python
handlerfile = TA_trello_import_rh_trello_cards.py
handleractions = edit, list, remove, create

[admin_external:TA_trello_import_trello_lists]
handlertype = python
handlerfile = TA_trello_import_rh_trello_lists.py
handleractions = edit, list, remove, create

[admin_external:TA_trello_import_settings]
handlertype = python
handlerfile = TA_trello_import_rh_settings.py
handleractions = edit, list

[admin_external:TA_trello_import_trello_movements]
handlertype = python
handlerfile = TA_trello_import_rh_trello_movements.py
handleractions = edit, list, remove, create

[admin_external:TA_trello_import_trello_checklists]
handlertype = python
handlerfile = TA_trello_import_rh_trello_checklists.py
handleractions = edit, list, remove, create
