[qintel_pmi_cache]
external_type = kvstore
collection = qintel_pmi_cache
fields_list = _key, first_seen, last_seen, data.attributes.affected_system.name, data.attributes.affected_system.versions, data.attributes.link