# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = true
is_configured = 0
state = enabled
build = 1

[launcher]
author = SCADAfence
version = 2.1.1
description = SCADAfence for Splunk allows SCADAfence admins and users to view and correlate their existing data within Splunk.

[ui]
is_visible = 1
label = scadafence for splunk
docs_section_override = AddOns:released

[package]
id = TA-scadafence-for-splunk

[triggers]
reload.addon_builder = simple
reload.ta_scadafence_for_splunk_account = simple
reload.ta_scadafence_for_splunk_settings = simple
reload.passwords = simple

