[ui]
is_visible = 1
label = Hurricane Labs App for Shodan

[launcher]
version = 2.2.6
author = Hurricane Labs
description = Provides a custom command to query Shodan as well as dashboards to monitor your subnets

[package]
id = Hurricane_Labs_App_for_Shodan

[install]
is_configured = false

[triggers]
reload.shodan = simple
