[expose:apex-setup-templates]
pattern = apex-setup-templates
methods = GET, POST, DELETE

[expose:hec-config]
pattern = apex-setup-templates/*
methods = GET, POST, DELETE

[expose:reset]
pattern = apex-setup-templates/*
methods = POST
