
[admin:TA_jira_tracking_add_on_for_splunk]
match = /
members = TA_jira_tracking_add_on_for_splunk_account, TA_jira_tracking_add_on_for_splunk_settings, TA_jira_tracking_add_on_for_splunk_input_jira_issues, TA_jira_tracking_add_on_for_splunk_input_jira_worklogs

[admin_external:TA_jira_tracking_add_on_for_splunk_account]
handlertype = python
python.version = python3
handlerfile = TA_jira_tracking_add_on_for_splunk_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_jira_tracking_add_on_for_splunk_settings]
handlertype = python
python.version = python3
handlerfile = TA_jira_tracking_add_on_for_splunk_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_jira_tracking_add_on_for_splunk_input_jira_issues]
handlertype = python
python.version = python3
handlerfile = TA_jira_tracking_add_on_for_splunk_rh_input_jira_issues.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_jira_tracking_add_on_for_splunk_input_jira_worklogs]
handlertype = python
python.version = python3
handlerfile = TA_jira_tracking_add_on_for_splunk_rh_input_jira_worklogs.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
