[admin:dnsdb_settings]
match = /SA-FarsightDNSDB
members= dnsdb_settings

[admin_external:dnsdb_settings]
python.version = python3
handlertype = python
handlerfile = dnsdb_settings.py
handleractions = list, edit