[kv_cp_cloud_syslog_format]
FORMAT = $1::$2
REGEX = "?([^\n"]*)"?:"?([^\n"]*)"?
SOURCE_KEY = ccx_encap_json
MV_ADD = true
DEPTH_LIMIT = 150000

## SOURCE PARSING
[checkpoint_cloud_audit_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(Web-UI|WEB_API|Log\sUpdate|smart_event|SmartUpdate|SmartConsole|license-mgmt|SmartDashboard|System\sMonitor|SmartEvent\sClient|SmartView|Scheduled\ssystem\supdate|Eventia\sAnalyzer\sClient|Security\sGateway\/Management|Smart\sDefense|LogUpdate|Log\s+Update|SmartDefense|Web_API_internal|Eventia\sAnalyzer\sClient|Connectra|Check\sPoint\sSecurity\sManagement\sServer|SmartProvisioning\sConnector|SmartLSM\sEndpoint\sSecurity\sConsole|SmartLSM|ROBO\s+GUI|Management\sBlade)"?
FORMAT = source::checkpoint:smart1:audit
LOOKAHEAD = 10000

[checkpoint_cloud_email_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(MTA|Anti-Spam|Anti\sSpam)"?
FORMAT = source::checkpoint:smart1:email
LOOKAHEAD = 10000

[checkpoint_cloud_endpoint_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(Endpoint\sCompliance|Core|Endpoint\sManagement|Media\sEncryption\s&\sPort\sProtection|MEPP|Endpoint\sSecurity\sConsole)"?
FORMAT = source::checkpoint:smart1:endpoint
LOOKAHEAD = 10000

[checkpoint_cloud_firewall_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(Firewall|DLP|Application\sControl|RAD|HTTPS\sInspection|Compliance\sBlade|Compliance(?:\||\")|VPN-1\s&\sFirewall-1|Network\sSecurity)"?
FORMAT = source::checkpoint:smart1:firewall
LOOKAHEAD = 10000

[checkpoint_cloud_firewall_subproduct_source]
DEST_KEY = MetaData:Source
REGEX = fw_subproduct="?(?:(?i)VPN)
FORMAT = source::checkpoint:smart1:sessions
LOOKAHEAD = 10000

[checkpoint_cloud_ids_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(IPS|WIFI|Cellular)"?
FORMAT = source::checkpoint:smart1:ids
LOOKAHEAD = 10000

[checkpoint_cloud_ids_malware_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(Threat\sEmulation|Anti\sVirus|New\sAnti\sVirus|Anti-Virus|Anti-Bot|Threat\sExtraction|Anti-Ransomware|Anti-Exploit|Forensics|OS\sExploit|Application(?:\||\")|Text\sMessage|Network\sAccess|Zero\sPhishing|Anti-Malware|Anti\sMalware\sNew\sAnti\sVirus|Anti\sMalware)"?
FORMAT = source::checkpoint:smart1:ids_malware
LOOKAHEAD = 10000

[checkpoint_cloud_sessions_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(VPN(?:\||\")|Mobile\sApp|Mobile(?:\||\"))"?
FORMAT = source::checkpoint:smart1:sessions
LOOKAHEAD = 10000

[checkpoint_cloud_web_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(URL\sFiltering)"?
FORMAT = source::checkpoint:smart1:web
LOOKAHEAD = 10000

[checkpoint_cloud_network_source]
DEST_KEY = MetaData:Source
REGEX = "?product"?:"?(IOS\sProfile|Device|Mobile\sAccess|WIFI\sNetwork)"?
FORMAT = source::checkpoint:smart1:network
LOOKAHEAD = 10000

[checkpoint_cloud_default_source]
DEST_KEY = MetaData:Source
REGEX = product="?\S+
FORMAT = source::checkpoint:smart1:cp_default
LOOKAHEAD = 10000


## AUTOMATIC LOOKUPS
[checkpoint_cloud_transport_protocols]
filename = checkpoint_cloud_transport_protocols.csv

[checkpoint_cloud_service_app]
filename = checkpoint_cloud_service_app.csv

## FURTHER EXTRACTION - REPORT
[transforms_file_path]
SOURCE_KEY = file_name
REGEX = (?<file_path>.*(?:\\|\/))

[resource_file_path]
SOURCE_KEY = resource
REGEX = ^(?<resource_file_path>(?:^(?!http).*(?:\\|\/))|.*)

[remediated_files_list]
SOURCE_KEY = remediated_files
REGEX = \s*(.*?)\((?:[^\)]*)\)(?:$|,)
FORMAT = remediated_files_list::$1
MV_ADD = true

[checkpoint_audit_auth_method]
SOURCE_KEY = _raw
REGEX = Authentication\smethod\:\s(?<authentication_method>[^\s|]+)




