
[ccx_abnormal_security_authentication]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=audit log_subtype=authentication
#tags = authentication

[ccx_abnormal_security_cases]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=cases
#tags = alert

[ccx_abnormal_security_cases_email]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=cases verdict IN ("spam", "safe")
# tags = email filter

[ccx_abnormal_security_cases_ids]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=cases verdict="malicious"
# tags = ids attack

[ccx_abnormal_security_changes]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=audit (log_subtype=change OR abx_body.category IN ("update*", "create*", "delete*"))
#tags = change audit

[ccx_abnormal_security_email_alerts]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=email
#tags = alert

[ccx_abnormal_security_email_filter]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=threat_log attack_type IN("Spam","Other") remediation_status="Auto-Remediated"
#tags = email filter

[ccx_abnormal_security_email_ids]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=threat_log AND NOT (attack_type IN("Spam","Other") AND remediation_status="Auto-Remediated")
#tags = ids attack

[ccx_abnormal_security_email_log_view]
search = `ccx_abnormal_security_index` source="abnormal-security" log_type=audit log_subtype=email
#tags = change audit
