[default]

[id]
version = 1.9.1
name = alert_timing_optimization_scheduler

[install]
is_configured = 0

[launcher]
description = Display alert timings from savedsearches.conf file. Provided balanced alert timing via new downloadable savedsearches.conf file as .gz or .zip files
version = 1.9.1
author = Jeffrey Fall

[package]
check_for_updates = true
id = alert_timing_optimization_scheduler

[ui]
is_visible = 1
label = Alert Timing Optimization Scheduler

