[script://$SPLUNK_HOME/etc/apps/Splunk_TA_lookingglasscyber_scout_query/bin/scout_query_download.py]
disabled = false
interval = */15 * * * *
source = lookingglasscyber
sourcetype = lookingglasscyber_scout_query
