[(?::){0}azure:topology:*]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
EXTRACT-topology_subscription_id = \/subscriptions\/(?P<subscription_id>[^\/]+)
EXTRACT-topology_resource_group = \/resourceGroups\/(?P<resource_group>[^\/]+)
EXTRACT-topology_vnet = \/providers\/Microsoft\.Network\/virtualNetworks\/(?P<vnet_name>[^(\/|\")]+)
EXTRACT-topology_subnet = \/subnets\/(?P<subnet_name>[^(\/|\")]+)
EVAL-resourceType = case(\
    match(id,"\/subscriptions\/([^\/]+)\/resourceGroups\/([^\/]+)\/providers\/Microsoft\.Network\/virtualNetworks\/([^\/]+)\/subnets\/([^\/]+)$"), "Subnet", \
    match(id,"\/subscriptions\/([^\/]+)\/resourceGroups\/([^\/]+)\/providers\/Microsoft\.Compute\/virtualMachines\/([^\/]+)$"), "Virtual Machine", \
    match(id,"\/subscriptions\/([^\/]+)\/resourceGroups\/([^\/]+)\/providers\/Microsoft\.Network\/virtualNetworks\/([^\/]+)$"), "Virtual Network", \
    match(id,"\/subscriptions\/([^\/]+)\/resourceGroups\/([^\/]+)\/providers\/Microsoft\.Network\/networkInterfaces\/([^\/]+)$"), "Network Interface", \
    match(id,"\/subscriptions\/([^\/]+)\/resourceGroups\/([^\/]+)\/providers\/Microsoft\.Network\/networkSecurityGroups\/([^\/]+)$"), "Network Security Group", \
    match(id,"\/subscriptions\/([^\/]+)\/resourceGroups\/([^\/]+)\/providers\/Microsoft\.Network\/networkSecurityGroups\/([^\/]+)\/securityRules\/([^\/]+)$"), "Network Security Rule"\
    )

[azure:topology:auto]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[azure:topology:manual]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

###############
## VM
###############
[azure:inventory:vm]
EXTRACT-ivm-subscription_id = \"id\" *\: *\"\/subscriptions\/(?P<subscription_id>[^\/]+)
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[azure:compute:vm]
EXTRACT-vm-subscription_id = \"id\" *\: *\"\/subscriptions\/(?P<subscription_id>[^\/]+)
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

###############
## Disk
###############

[azure:inventory:disk]
EXTRACT-idisk-subscription_id = \"id\" *\: *\"\/subscriptions\/(?P<subscription_id>[^\/]+)
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[azure:compute:disk]
EXTRACT-disk-subscription_id = \"id\" *\: *\"\/subscriptions\/(?P<subscription_id>[^\/]+)
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

###############
## VNET
###############

[azure:inventory:vnet]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[azure:vnet]
EXTRACT-vnet-subscription_id = \"id\" *\: *\"\/subscriptions\/(?P<subscription_id>[^\/]+)
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

###############
## Subscription
###############

[azure:subscription]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

###################
## Security Center
###################

[azure:securityCenter:task]
EXTRACT-sstask-subscription_id = \"id\" *\: *\"\/subscriptions\/(?P<subscription_id>[^\/]+)
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[azure:securityCenter:alert]
EXTRACT-ssalert-subscription_id = \"id\" *\: *\"\/subscriptions\/(?P<subscription_id>[^\/]+)
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[azure:resourcegroup]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
