[launcher]
version = 3.0.0
description = Splunk Add-on for Carbon Black
author = Splunk LLC.

[id]
version = 3.0.0
name = Splunk_TA_bit9-carbonblack

[install]
build = 4
is_configured = false
state = enabled

[package]
id = Splunk_TA_bit9-carbonblack
check_for_updates = true

[ui]
label = Splunk Add-on for Carbon Black
is_visible = false
docs_section_override = AddOns:released
