[hpp_msg_boot_code_corrupt]
search = index="printersec" device="printer" "Boot code corrupt"

[hpp_msg_code_sign_error]
search = index="printersec" device="printer" "Code sign error"

[hpp_msg_failed_to_initialize_intrusion_detection]
search = index="printersec" device="printer" "Failed to initialize intrusion detection"

[hpp_msg_intrusion_detection_disabled]
search = index="printersec" device="printer" "Intrusion detection disabled. Unable to scan for memory corruption."

[hpp_msg_invalid_boot_attempt]
search = index="printersec" device="printer" "Invalid boot attempt"

[hpp_msg_potential_intrusion]
search = index="printersec" device="printer" "Potential intrusion. Memory corruption detected."

[hpp_msg_upgrade_corrupt]
search = index="printersec" device="printer" "Upgrade corrupt"
