[DataFormater(1)]
args = DateField
definition = if(match($DateField$,"\+"),replace($DateField$,"(\d+)\+(\d+)\:(\d+)\:(\d+)","\1 Days "),replace($DateField$,"(\d+)\:(\d+)\:(\d+)","\1 Hrs "))
iseval = 0