
[admin:TA_moveit]
match = /
members = TA_moveit_account, TA_moveit_settings, TA_moveit_moveit_transfer_xferstatus, TA_moveit_moveit_automation_reports, TA_moveit_moveit_automation_assets, TA_moveit_moveit_transfer_filestorage, TA_moveit_moveit_transfer_config, TA_moveit_moveit_transfer_reports, TA_moveit_moveit_transfer_user_info, TA_moveit_moveit_transfer_logs

[admin_external:TA_moveit_account]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_moveit_settings]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_moveit_moveit_transfer_xferstatus]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_moveit_transfer_xferstatus.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_moveit_moveit_automation_reports]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_moveit_automation_reports.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_moveit_moveit_automation_assets]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_moveit_automation_assets.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_moveit_moveit_transfer_filestorage]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_moveit_transfer_filestorage.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_moveit_moveit_transfer_config]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_moveit_transfer_config.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_moveit_moveit_transfer_reports]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_moveit_transfer_reports.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_moveit_moveit_transfer_user_info]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_moveit_transfer_user_info.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_moveit_moveit_transfer_logs]
handlertype = python
python.version = python3
handlerfile = TA_moveit_rh_moveit_transfer_logs.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
