[d3_bubble]
label = D3 BUBBLE
description = a kind of 'Circular Packing Chart' as a custom viz. Using legacy D3 v3.5 (By GoAhead Inc.)
allow_user_selection = true
supports_trellis = false
supports_drilldown = true
supports_export = true
search_fragment = " | stats value_field by name_field, (optional)category_field"