[expose:Splunk_TA_Talos_Intelligence_account]
pattern = Splunk_TA_Talos_Intelligence_account
methods = POST, GET

[expose:Splunk_TA_Talos_Intelligence_account_specified]
pattern = Splunk_TA_Talos_Intelligence_account/*
methods = POST, GET, DELETE

[expose:Splunk_TA_Talos_Intelligence_settings]
pattern = Splunk_TA_Talos_Intelligence_settings
methods = POST, GET

[expose:Splunk_TA_Talos_Intelligence_settings_specified]
pattern = Splunk_TA_Talos_Intelligence_settings/*
methods = POST, GET, DELETE

[expose:Splunk_TA_Talos_Intelligence_rest_handler]
pattern = query_reputation
methods = POST
