# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 101

[launcher]
author = Netwrix Corporation
version = 2.0.0
description = Netwrix Threat Hunting solution enables organizations to target and hunt active cyber threats. Using the preconfigured Netwrix Threat Hunting App for Splunk, users can quickly understand all Threat Hunting as an incident response tool, it enables analysts to investigate the scope, impact, and root cause of an incident efficiently by analyzing patterns of activity indicative of account compromise and file system activity.Learn more about Netwrix at https://www.Netwrix.com/.

[ui]
is_visible = 1
label = Netwrix Threat Hunting App for Splunk
docs_section_override = AddOns:released

[package]
id = sb_th

[triggers]
reload.addon_builder = simple
reload.sb_th_account = simple
reload.sb_th_settings = simple
reload.passwords = simple

[author=Netwrix]
email = splunk@netwrix.com
company = Netwrix Corporation

