[windowstats-command]
syntax = windowstats (<windowstats-options>)* 
shortdesc = The windowstats command generate statistics for fixed window size
usage = public

[windowstats-options]
syntax = field=<field> | window="<string>" | style="<string>" | rename="<string>" | function="<string>" 
