[launcher]
version = 1.0.0
description = DataBee App For Splunk
author = Databee

[id]
version = 1.0.0
name = DataBeeAppForSplunk

[install]
build = 17
is_configured = false
state = enabled

[package]
id = DataBeeAppForSplunk
check_for_updates = true

[ui]
label = DataBee App For Splunk
is_visible = true

[triggers]
reload.databeeappforsplunk_settings = simple
reload.databeeappforsplunk_account = simple

