# db_connect endpoints
[expose:db_connect_dbxproxy]
methods = GET,POST,DELETE,PUT
pattern = db_connect/dbxproxy/**

[expose:dbx_settings]
methods = GET,POST
pattern = db_connect/settings

[expose:dbx_loglevel]
methods = GET,POST
pattern = db_connect/loglevel

[expose:dbx_health_check]
methods = GET
pattern = db_connect/health_check/**
