
[expose:xposedornot_settings]
pattern = xposedornot_settings
methods = POST, GET

[expose:xposedornot_settings_specified]
pattern = xposedornot_settings/*
methods = POST, GET, DELETE

[expose:xposedornot_xposedornot]
pattern = xposedornot_xposedornot
methods = POST, GET

[expose:xposedornot_xposedornot_specified]
pattern = xposedornot_xposedornot/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
