[view-admin-login]
search = EventType="VLSI_USERLOGGEDIN" sourcetype="vm:hzn:syslog"

[view-new-user-session]
search = EventType="AGENT_CONNECTED" sourcetype="vm:hzn:syslog"

[view-broker-user-login]
search = EventType="BROKER_USERLOGGEDIN" sourcetype="vm:hzn:syslog"

[view-api-login]
search = (EventType="REST_AUTH_LOGIN_SUCCESS" OR EventType="VLSI_USERLOGGEDIN_REST") sourcetype="vm:hzn:syslog"

[view-new-user-session-pending]
search = EventType="AGENT_PENDING" sourcetype="vm:hzn:syslog"

[view-new-user-session-pending-expired]
search = EventType="AGENT_PENDING_EXPIRED" sourcetype="vm:hzn:syslog"

[view-user-login-locked-out]
search = EventType="BROKER_USER_AUTHFAILED_ACCOUNT_LOCKED_OUT" sourcetype="vm:hzn:syslog"

[view-user-login-bad-pass]
search = EventType="BROKER_USER_AUTHFAILED_BAD_USER_PASSWORD" sourcetype="vm:hzn:syslog"

[view-application-error]
search = (EventType="BROKER_APPLICATION_MISSING" OR EventType="AGENT_APPLICATION_LAUNCH_FAILED") sourcetype="vm:hzn:syslog"
