[PhishMeUsers]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-cofense-phishme*.log*]
SHOULD_LINEMERGE = true
sourcetype = tacofensephishme:log

[source::...ta_cofense_phishme*.log*]
SHOULD_LINEMERGE = true
sourcetype = tacofensephishme:log

[PhishMeScenarios]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[PhishMeScenarioReports]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
