# Copyright (C) 2005-2021 Splunk Inc. All Rights Reserved.

[source::.../unix_installer.lo*]
sourcetype=unix_installer

## Dropdowns
[(?::){0}*]
LOOKUP-dropdowns = dropdownsLookup host OUTPUT unix_category unix_group