[default]
# Set property defaults
display.visualizations.custom.VisualOverlayApp.visual_overlay.toggleLegend = on
display.visualizations.custom.VisualOverlayApp.visual_overlay.legendContents = ''
display.visualizations.custom.VisualOverlayApp.visual_overlay.legendSize = 30px

display.visualizations.custom.VisualOverlayApp.visual_overlay.toggleValue = off
display.visualizations.custom.VisualOverlayApp.visual_overlay.valueSize = 100%
display.visualizations.custom.VisualOverlayApp.visual_overlay.valueOffset = 3
display.visualizations.custom.VisualOverlayApp.visual_overlay.valueSuffix = ''

display.visualizations.custom.VisualOverlayApp.visual_overlay.backgroundImage = https://i.picsum.photos/id/461/1800/1700.jpg?hmac=jCe9RSHOfiHWvm64-A1nHEwiYjhddqafTP3ulEPS-Rc

display.visualizations.custom.VisualOverlayApp.visual_overlay.pointSize = 1.5%
display.visualizations.custom.VisualOverlayApp.visual_overlay.includeLabels = off
display.visualizations.custom.VisualOverlayApp.visual_overlay.toggleLabels = off

display.visualizations.custom.VisualOverlayApp.visual_overlay.toggleAggregation = on
display.visualizations.custom.VisualOverlayApp.visual_overlay.aggregationRadius = 3.5

display.visualizations.custom.VisualOverlayApp.visual_overlay.toggleDrilldown = on
display.visualizations.custom.VisualOverlayApp.visual_overlay.includeObjectID = suffix
display.visualizations.custom.VisualOverlayApp.visual_overlay.drilldownUrl = /en-US/app/search