[admin:akamai_rest]
match = /splunk_ta_akamai
members = cp_codes

[admin_external:cp_codes]
handlertype = python
handlerfile = akamai_cp_code_rest_handler.py
handleractions = create,list,edit,remove
capability.post = cp_codes
capability.delete = cp_codes
capability.get= cp_codes
