[akamai-cp_codes-lookup_gen]
cron_schedule = */15 * * * *
description = Saved search which populates the CP code of Akamai
disabled = 1
dispatch.earliest_time = -5m
dispatch.latest_time = now
request.ui_dispatch_app = search
request.ui_dispatch_view = search
enableSched = 1
schedule_window = 5
search = `akamai_indexes` eventtype=akamai_general_web cp=* | dedup cp |rename cp as cp_code | eval _key=cp_code | table _key,cp_code,alias | join _key type=left [|inputlookup akamai_cp_code_tag] |  outputlookup akamai_cp_code_tag append=true
