[script:mltk_container_app]
match = /mltk-container/app
scripttype = python
python.version = python3
handler = app_handler.AppHandler
output_modes = json
passSystemAuth = true
capability = configure_mltk_container or admin_all_objects

[script:mltk_container_configure]
match = /mltk-container/configure
scripttype = python
python.version = python3
handler = configure_handler.ConfigureHandler
output_modes = json
passSystemAuth = true
capability = configure_mltk_container or admin_all_objects

[script:mltk_container_llmconfigure]
match = /mltk-container/llmconfigure
scripttype = python
python.version = python3
handler = llmconfigure_handler.LlmconfigureHandler
output_modes = json
passSystemAuth = true
capability = configure_mltk_container or admin_all_objects

[script:mltk_container_images]
match = /mltk-container/images
scripttype = python
python.version = python3
handler = images_handler.ImagesHandler
output_modes = json
passSystemAuth = true
capability = list_mltk_container or admin_all_objects

[script:mltk_container_transformersmodel]
match = /mltk-container/transformersmodel
scripttype = python
python.version = python3
handler = transformersmodel_handler.TransformersmodelHandler
output_modes = json
passSystemAuth = true
capability = list_mltk_container or admin_all_objects

[script:mltk_container_status]
match = /mltk-container/status
scripttype = python
python.version = python3
handler = status_handler.StatusHandler
output_modes = json
passSystemAuth = true
capability = list_mltk_container or admin_all_objects

[script:mltk_container_start]
match = /mltk-container/start
scripttype = python
python.version = python3
handler = start_handler.StartHandler
output_modes = json
passSystemAuth = true
capability = control_mltk_container or admin_all_objects

[script:mltk_container_stop]
match = /mltk-container/stop
scripttype = python
python.version = python3
handler = stop_handler.StopHandler
output_modes = json
passSystemAuth = true
capability = control_mltk_container or admin_all_objects

[script:mltk_container_sync]
match = /mltk-container/sync
scripttype = python
python.version = python3
handler = sync_handler.SyncHandler
output_modes = json
passSystemAuth = true
capability = control_mltk_container or admin_all_objects

[script:mltk_container_logs]
match = /mltk-container/logs/?
scripttype = python
python.version = python3
handler = logs_handler.LogsHandler
output_modes = json
passSystemAuth = true
capability = control_mltk_container or admin_all_objects
