[expose:mltk_container_app]
pattern = mltk-container/app
methods = GET

[expose:mltk_container_configure]
pattern = mltk-container/configure
methods = POST,GET

[expose:mltk_container_llmconfigure]
pattern = mltk-container/llmconfigure
methods = POST,GET

[expose:mltk_container_status]
pattern = mltk-container/status
methods = GET

[expose:mltk_container_transformersmodel]
pattern = mltk-container/transformersmodel
methods = POST,GET

[expose:mltk_container_start]
pattern = mltk-container/start
methods = POST

[expose:mltk_container_stop]
pattern = mltk-container/stop
methods = POST

[expose:mltk_container_logs]
pattern = mltk-container/logs/*
methods = GET