[launcher]
author = Benya Chongolnee, Burch Simon
description = Splunk Application that backups certain Splunk folder using either the Splunk diag command or Splunk local git commands. The app helps with versioning control.
version = 1.0.2

[ui]
label=Stateful Snapshot App for Splunk

[package]
id = stateful_snapshot

[install]
build = 1711488732