[token]
consumer_key =
consumer_secret =
access_token = 
access_secret = 

[security]
encryption = False
key = 

[listener]
filter = Splunk,JPEngineer,Apple
sentiment = false

[logs]
max_size_mb = 50
max_log_backup = 4
debug = false

[info]
app_version = 1.0.C
type = LTS

