
[expose:TA_crowdstrike_falcon_filevantage_account]
pattern = TA_crowdstrike_falcon_filevantage_account
methods = POST, GET

[expose:TA_crowdstrike_falcon_filevantage_account_specified]
pattern = TA_crowdstrike_falcon_filevantage_account/*
methods = POST, GET, DELETE

[expose:TA_crowdstrike_falcon_filevantage_settings]
pattern = TA_crowdstrike_falcon_filevantage_settings
methods = POST, GET

[expose:TA_crowdstrike_falcon_filevantage_settings_specified]
pattern = TA_crowdstrike_falcon_filevantage_settings/*
methods = POST, GET, DELETE

[expose:TA_crowdstrike_falcon_filevantage_crowdstrike_filevantage_json]
pattern = TA_crowdstrike_falcon_filevantage_crowdstrike_filevantage_json
methods = POST, GET

[expose:TA_crowdstrike_falcon_filevantage_crowdstrike_filevantage_json_specified]
pattern = TA_crowdstrike_falcon_filevantage_crowdstrike_filevantage_json/*
methods = POST, GET, DELETE
