[proxy]
proxy_enabled = 
proxy_url = 
proxy_port = 
proxy_username = 
proxy_password = 

[logging]
loglevel = INFO

[splunk_es_enrichment]
enable_splunk_es_saved_searches = 0
global_account = 
run_saved_searches_for = EVERY_THIRTY_MINUTES
