[install]
is_configured = false
state = enabled
allows_disable = false

[ui]
is_visible = false
label = onyphe

[launcher]
author = ONYPHE SAS
description = Official ONYPHE client to access the API
version = 1.1.2

[package]
id = TA-onyphe
check_for_updates = true
