[setupentity]
name_1 =
dns_1 =
controllerAIp_1 =
controllerBIp_1 =
username_1 =
password_1 =
allowInvalidSslCert_1 =

name_2 =
dns_2 =
controllerAIp_2 =
controllerBIp_2 =
username_2 =
password_2 =
allowInvalidSslCert_2 =

name_3 =
dns_3 =
controllerAIp_3 =
controllerBIp_3 =
username_3 =
password_3 =
allowInvalidSslCert_3 =
