[ipfix]
TRANSFORMS-SourceType = ziften:zflow:ipfix 


[ziften:zflow:ipfix]
SHOULD_LINEMERGE = false

#CIM
EVAL-src_ip = coalesce(sourceIPv4Address,sourceIPv6Address)
EVAL-dest_ip = coalesce(destinationIPv4Address,destinationIPv6Address)

FIELDALIAS-src_port = sourceTransportPort AS src_port
FIELDALIAS-dest_port = destinationTransportPort AS dest_port

FIELDALIAS-user = userName AS user 


