[launcher]
description = AI Toolkit
author = Splunk
version = 5.6.3

[package]
id = Splunk_ML_Toolkit

[install]
build = 1756729954688

[ui]
is_visible = 1
label = AI Toolkit
attribution_link = http://docs.splunk.com/Documentation/MLApp/latest/User/Thirdpartysoftwarecredits

[triggers]
reload.algos = simple
reload.experiments = simple
reload.mlspl = simple
reload.scorings = simple

[id]
version = 5.6.3
