# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = true
is_configured = 0
state = enabled
build = 9

[launcher]
author = Leonardo Armesto
version = 1.0.7
description = This Add-On enables Splunk to receive events directly from an Azure Event Hub.

[ui]
is_visible = 1
label = Azure Event Hubs Grabber
docs_section_override = AddOns:released

[package]
id = TA-azure-event-hubs-grabber

[triggers]
reload.addon_builder = simple
reload.ta_azure_event_hubs_grabber_account = simple
reload.ta_azure_event_hubs_grabber_settings = simple
reload.passwords = simple

