[as:account]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-bx-adaptive-shield-addon*.log*]
sourcetype = tabxadaptiveshieldaddon:log

[source::...ta_bx_adaptive_shield_addon*.log*]
sourcetype = tabxadaptiveshieldaddon:log

[as:integrations]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[as:alerts]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[as:security:checks]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[as:security:checks_enhanced]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[as:account_enhanced]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[as:integrations_enhanced]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[as:alerts_enhanced]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

