# Splunk app configuration file

[ui]
is_visible = true
label = Splunk for F5 Security

[launcher]
author = Splunk, Concanon & F5 Networks
description = Splunk for F5 Security is a colleciton of field extractions, saved searches, reports and dashboards for your F5 Access Security Manager and Protocol Security Manager<br>  Splunk and F5 are working together to provide real time reporting and intelligence across the F5 security products.<br> Splunk and F5 are working together to provide real time reporting and intelligence across the complete F5 product line. You rely on F5 Networks solutions like BigIP Global Traffic Manager, Local Traffic Manager, ASM, Firepass, WANOPT and ARX to keep your mission critical applications running and achieve IT agility. Your way.  Now you can rely on Splunk for F5 to search, alert, report and make decisions in real time. Pre-defined inputs, searches, alerts, reports, dashboards and actions make it quick to get started and with the power of Splunk you can customize Splunk for F5 to meet the specific needs of your agile IT environment.
version = 2.0


[package]
id = SplunkforF5Security

[install]
state = enabled
build = 2
install_source_checksum = 1ae41e1e000f33ba9486cea7379f4d54481f4962
