
#
# Modify default format
#
[asm_log]
SHOULD_LINEMERGE=false
TIME_PREFIX=\,date_time=\"
TRANSFORMS-check_for_psm = f5_check_for_psm1, f5_check_for_psm2
# 
EVAL-block_count = if(isnull(block_count), if(isnull(drop_count), dropped_requests, drop_count), block_count) 
EVAL-country = if(isnull(country), "N/A", country)
EVAL-drop_count = if(isnull(drop_count), dropped_requests, drop_count) 
EVAL-geo_location = if(isnull(geo_location), client_ip_geo_location, geo_location)
EVAL-unit_hostname = if(isnull(unit_hostname), hostname, unit_hostname)
EVAL-web_application_name = if(isnull(web_application_name), policy_name, web_application_name)
EXTRACT-source_ip = ,source_ip=\"(?<attacker_ip>[\d+\.\d+\.\d+\.\d+]+):(?<country>[^:]+):(?<drop_count>\d+):(?<block_count>\d+)\"
FIELDALIAS-ip_client = ip_client AS src_ip


[psm_log]
SHOULD_LINEMERGE=false
TIME_PREFIX=\,date_time=\"
#
EVAL-block_count = if(isnull(block_count), if(isnull(drop_count), dropped_requests, drop_count), block_count)
EVAL-country = if(isnull(country), "N/A", country)
EVAL-drop_count = if(isnull(drop_count), dropped_requests, drop_count)
EVAL-geo_location = if(isnull(geo_location), client_ip_geo_location, geo_location)
EVAL-unit_hostname = if(isnull(unit_hostname), hostname, unit_hostname)
EVAL-web_application_name = if(isnull(web_application_name), policy_name, web_application_name)
EXTRACT-source_ip = ,source_ip=\"(?<attacker_ip>[\d+\.\d+\.\d+\.\d+]+):(?<country>[^:]+):(?<drop_count>\d+):(?<block_count>\d+)\"
FIELDALIAS-ip_client = ip_client AS src_ip
