[eventtype=dell_sonicwall_sma]
network         = enabled
communicate     = enabled
vpn             = enabled

[eventtype=dell_sonicwall_sma_session_start]
authentication 	= enabled
session         = enabled
start           = enabled

[eventtype=dell_sonicwall_sma_session_end]
session         = enabled
end             = enabled

[eventtype=dell_sonicwall_sma_post_auth]
authentication 	= enabled

[eventtype=dell_sonicwall_sma_phase1_authentication_success]
authentication 	= enabled

[eventtype=dell_sonicwall_sma_web_proxy_service]
web             = enabled