[syncanalytics]
filename = sync_command.py
chunked = true
python.version = python3

[submitanalytichits]
filename = submit_command.py
chunked = true
python.version = python3

[jobrunner]
filename = jobrunner_command.py
chunked = true
python.version = python3

[jobscheduler]
filename = scheduler_command.py
chunked = true
python.version = python3