# [searchbnf.conf](http://docs.splunk.com/Documentation/Splunk/latest/Admin/Searchbnfconf)

[qsentryfeed-command]
syntax = qsentryfeed ip_field=<ip_address_field_name>
shortdesc = Retrieves Proxy Intel from local QSentry Feed
example1 = | qsentryfeed ip_field=src_ip
category = generating
appears-in = 1.0.0
maintainer = Qintel
usage = public
tags = qintel
