# Note to TruSTAR Developers (users can ignore):
#
#    Spec for inputs.conf:
#
#       https://docs.splunk.com/Documentation/Splunk/8.1.3/Admin/Inputsconf
#
#    This file is created by Splunk's Addonbuilder but TruSTAR modifies it
#    because we need to be able to specify "interval = 0" because the modinput
#    can potentially run for hours (while downloading whitelist from TruSTAR)
#    (exact time unpredictable) without being able to checkpoint itself, so
#    we can't rely on Splunk's "interval" timing / script launching feature
#    to launch and terminate the script every X minutes.  Specifically, we
#    don't want Splunk's controller terminating the script.
#
#
#    This file needs to be updated in TruSTAR's source code every time TruSTAR
#    makes modifications to the Addonbuilder project file.  Developer needs to
#    merge differences between the version produced by the AOB and the version in
#    TruSTAR's repo's "src/modified_aob_files/default/" dir.


[trustar_observables_to_kvstores]
# the "kvstore group" input setting maps to "index" in "globalConfig.json",
# so "default" will be overwritten with either "trustar" or "splunk_es".
index = default

start_by_shell = false
python.version = python3
sourcetype = trustar_observables_to_kvstores

# want the script to be allowed to run continuously.
# we put a "sleep" at the end of the script.
interval = 0

ioc_types = ['EMAIL_ADDRESS', 'IP', 'MD5', 'SHA1', 'SHA256', 'SOFTWARE', 'REGISTRY_KEY', 'URL', 'DOMAIN']
expiration_days = 30
