[trustar_observables_to_kvstores]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...trustar_unified*.log*]
SHOULD_LINEMERGE = true
sourcetype = trustarunified:log

[source::...trustar_enrich_threat_activity_modalert.log*]
SHOULD_LINEMERGE = true
sourcetype = trustarunified:log

[source::...trustar_submit_event_modalert.log*]
SHOULD_LINEMERGE = true
sourcetype = trustarunified:log
