#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 0
label = Industrial Defender Add-on for Splunk

[launcher]
author = Industrial Defender
description = Modular input for Industrial Defender REST API
version = 2.1.0

[package]
id = asm_modular_input
check_for_updates = 1 

