[install]
state_change_requires_restart = true
is_configured = 0
state = enabled
build = 3

[launcher]
author = Whois API, Inc.
version = 1.0.3
description = Get detailed information about the IP range a particular IP belongs to

[ui]
is_visible = 1
label = Whois XML IP Netblocks API for Splunk
docs_section_override = AddOns:released
setup_view = setup

[id]
name = TA_whois_xml_ip_netblocks_api
version = 1.0.3

[package]
id = TA_whois_xml_ip_netblocks_api

[triggers]
reload.whoisxmlapi_ip_netblocks = simple
