
[admin:TA_add_on_for_bluecat_ipam]
match = /
members = TA_add_on_for_bluecat_ipam_account, TA_add_on_for_bluecat_ipam_settings, TA_add_on_for_bluecat_ipam_get_ipam_data

[admin_external:TA_add_on_for_bluecat_ipam_account]
handlertype = python
handlerfile = TA_add_on_for_bluecat_ipam_rh_account.py
handleractions = edit, list, remove, create
python.version = python3

[admin_external:TA_add_on_for_bluecat_ipam_settings]
handlertype = python
handlerfile = TA_add_on_for_bluecat_ipam_rh_settings.py
handleractions = edit, list
python.version = python3

[admin_external:TA_add_on_for_bluecat_ipam_get_ipam_data]
handlertype = python
handlerfile = TA_add_on_for_bluecat_ipam_rh_get_ipam_data.py
handleractions = edit, list, remove, create
python.version = python3
