[vmware_edr_deeplink_sensor]
label = View sensor $sensor_id$ in VMware CB EDR
fields = link_sensor
link.uri = https://$!link_sensor$
type = link

[vmware_edr_deeplink_target]
fields = link_target
label = View process target in VMware CB EDR
link.uri = https://$!link_target$
type = link

[vmware_edr_deeplink_parent]
fields = link_parent
label = View Parent Process in VMware CB EDR
link.uri = https://$!link_parent$
type = link

[vmware_edr_deeplink_child]
fields = link_child
label = View child in VMware CB EDR
link.uri = https://$!link_child$
type = link

[vmware_edr_deeplink_process]
fields = link_process
label = View Process Analysis in VMware CB EDR
link.uri = https://$!link_process$
type = link

[vmware_edr_deeplink_md5]
fields = link_md5
label = View Binary Information in VMware CB EDR
link.uri = https://$!link_md5$
type = link

[vmware_edr_sensor_info_by_ip]
display_location = field_menu
fields = src_ip, dest_ip, dest_translated_ip, local_ip, remote_ip, ipv4
label = Find VMware Carbon Black EDR sensors associated with IP $@field_value$
link.method = get
link.target = blank
link.uri = /app/$@namespace$/vmware_edr_sensor_search?earliest=0&latest=&form.sensor_search=ip:$@field_value$
type = link
disabled = 0

[vmware_ipsearch]
display_location = field_menu
fields = src_ip, dest_ip, local_ip, remote_ip, ipv4
label = Search VMware Carbon Black EDR for processes contacting $@field_value$
link.method = get
link.target = blank
link.uri = /app/$@namespace$/vmware_edr_process_search?form.process_search=ipaddr:$@field_value$
type = link
disabled = 0

[vmware_md5binarysearch]
display_location = field_menu
fields = md5, file_hash, process_md5
label = VMware Carbon Black EDR Binary Search by MD5 hash $@field_value$
link.method = get
link.target = blank
link.uri = /app/$@namespace$/vmware_edr_binary_search?form.binary_search=md5:$@field_value$
type = link
disabled = 0

[vmware_md5processsearch]
display_location = field_menu
fields = md5, file_hash
label = Search VMware Carbon Black EDR for processes related to MD5 $@field_value$
link.method = get
link.target = blank
link.uri = /app/$@namespace$/vmware_edr_process_search?form.process_search=md5:$@field_value$
type = link
disabled = 0

[vmware_search_process_netconn]
display_location = both
fields = dvc, dest_ip, dest_port
label = Search VMware Carbon Black EDR for this specific network connection
link.method = get
link.target = blank
link.uri = /app/$@namespace$/vmware_edr_process_search?form.process_search=ipport:$dest_port$%20ipaddr:$dest_ip$%20hostname:$dvc$
type = link
disabled = 0

[vmware_search_process_file_name]
display_location = field_menu
fields = file_name, file_path
label = Search VMware Carbon Black EDR for processes modifying $filename$
link.method = get
link.target = blank
link.uri = /app/$@namespace$/vmware_edr_process_search?form.process_search=filemod:$@field_value$
type = link
disabled = 0

[vmware_search_process_domain]
display_location = both
fields = domain
label = Search VMware Carbon Black EDR for processes contacting $domain$
link.method = get
link.target = blank
link.uri = /app/$@namespace$/vmware_edr_process_search?form.process_search=domain:$domain$
type = link
disabled = 0