
[admin:OB_trellix_etp]
match = /
members = OB_trellix_etp_settings, OB_trellix_etp_ob_etp_alert_summary, OB_trellix_etp_ob_etp_alert_summary_outbound, OB_trellix_etp_ob_etp_email_trace, OB_trellix_etp_ob_etp_email_trace_outbound, OB_trellix_etp_ob_etp_audit_log

[admin_external:OB_trellix_etp_settings]
handlertype = python
python.version = python3
handlerfile = OB_trellix_etp_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:OB_trellix_etp_ob_etp_alert_summary]
handlertype = python
python.version = python3
handlerfile = OB_trellix_etp_rh_ob_etp_alert_summary.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:OB_trellix_etp_ob_etp_alert_summary_outbound]
handlertype = python
python.version = python3
handlerfile = OB_trellix_etp_rh_ob_etp_alert_summary_outbound.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:OB_trellix_etp_ob_etp_email_trace]
handlertype = python
python.version = python3
handlerfile = OB_trellix_etp_rh_ob_etp_email_trace.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:OB_trellix_etp_ob_etp_email_trace_outbound]
handlertype = python
python.version = python3
handlerfile = OB_trellix_etp_rh_ob_etp_email_trace_outbound.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:OB_trellix_etp_ob_etp_audit_log]
handlertype = python
python.version = python3
handlerfile = OB_trellix_etp_rh_ob_etp_audit_log.py
handleractions = edit, list, remove, create
handlerpersistentmode = true