[itsi_csv_import://DA-ITSI-MAINFRAME_ZOS-Mainframe_CICS_System_Entity_Search]
entity_identifier_fields = JOBNAME
entity_informational_fields = mainframe_role,itsi_role
entity_title_field = JOBNAME
import_from_search = 1
index_earliest = -60m
index_latest = now
search_string = index=* MFSOURCETYPE=SMF110 | eval mainframe_role="cics" | eval itsi_role="mainframe" | dedup JOBNAME | sort JOBNAME | table JOBNAME, mainframe_role, itsi_role
update_type = UPSERT

[itsi_csv_import://DA-ITSI-MAINFRAME_ZOS-Mainframe_LPAR_Entity_Search]
entity_identifier_fields = RMFSystem
entity_informational_fields = mainframe_role,itsi_role
entity_title_field = RMFSystem
import_from_search = 1
index_earliest = -60m
index_latest = now
search_string = index=* RMFResource="MVS_IMAGE" | eval mainframe_role="lpar" | eval itsi_role="mainframe" | dedup RMFSystem | sort RMFSystem | table RMFSystem, mainframe_role, itsi_role
update_type = UPSERT

[itsi_csv_import://DA-ITSI-MAINFRAME_ZOS-Mainframe_CICS_Transaction_Entity_Search]
entity_identifier_fields = TRAN
entity_informational_fields = mainframe_role,itsi_role
entity_title_field = TRAN
import_from_search = 1
index_earliest = -60m
index_latest = now
search_string = index=* MFSOURCETYPE=SMF110 TRAN!="" | eval mainframe_role="cics_transaction" | eval itsi_role="mainframe" | dedup TRAN | sort TRAN | table TRAN, mainframe_role, itsi_role
update_type = UPSERT

[itsi_csv_import://DA-ITSI-MAINFRAME_ZOS-Mainframe_CPC_Entity_Search]
entity_identifier_fields = RMFSystem
entity_informational_fields = mainframe_role,itsi_role
entity_title_field = RMFSystem
import_from_search = 1
index_earliest = -60m
index_latest = now
search_string = index=* RMFResource="SYSPLEX" | eval mainframe_role="cpc" | eval itsi_role="mainframe" | dedup RMFSystem | table RMFSystem, mainframe_role, itsi_role
update_type = UPSERT

[itsi_csv_import://DA-ITSI-MAINFRAME_ZOS-Mainframe_DB2_System_Entity_Search]
entity_identifier_fields = DB2_SUBSYSTEM
entity_informational_fields = mainframe_role,itsi_role
entity_title_field = DB2_SUBSYSTEM
import_from_search = 1
index_earliest = -60m
index_latest = now
search_string = index=* MFSOURCETYPE=SMF101 | eval mainframe_role="db2" | eval itsi_role="mainframe" | dedup DB2_SUBSYSTEM | sort DB2_SUBSYSTEM | table DB2_SUBSYSTEM, mainframe_role, itsi_role
update_type = UPSERT
