
[admin:TA_bitwarden_add_on_for_splunk]
match = /
members = TA_bitwarden_add_on_for_splunk_account, TA_bitwarden_add_on_for_splunk_settings, TA_bitwarden_add_on_for_splunk_policies, TA_bitwarden_add_on_for_splunk_members, TA_bitwarden_add_on_for_splunk_events, TA_bitwarden_add_on_for_splunk_group, TA_bitwarden_add_on_for_splunk_collection

[admin_external:TA_bitwarden_add_on_for_splunk_account]
handlertype = python
python.version = python3
handlerfile = TA_bitwarden_add_on_for_splunk_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_bitwarden_add_on_for_splunk_settings]
handlertype = python
python.version = python3
handlerfile = TA_bitwarden_add_on_for_splunk_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_bitwarden_add_on_for_splunk_policies]
handlertype = python
python.version = python3
handlerfile = TA_bitwarden_add_on_for_splunk_rh_policies.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_bitwarden_add_on_for_splunk_members]
handlertype = python
python.version = python3
handlerfile = TA_bitwarden_add_on_for_splunk_rh_members.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_bitwarden_add_on_for_splunk_events]
handlertype = python
python.version = python3
handlerfile = TA_bitwarden_add_on_for_splunk_rh_events.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_bitwarden_add_on_for_splunk_group]
handlertype = python
python.version = python3
handlerfile = TA_bitwarden_add_on_for_splunk_rh_group.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_bitwarden_add_on_for_splunk_collection]
handlertype = python
python.version = python3
handlerfile = TA_bitwarden_add_on_for_splunk_rh_collection.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
