#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 0
label = Centrify Add-on for Splunk

[launcher]
author = Centrify Corporation
description = The Centrify Add-on for Splunk collects data from Centrify environment and normalize it for follow-up data analysis.
version = 2.4.0

[package]
id = TA-centrify
