[ui]
is_visible = 1
label = Splidgets - Splunkpad

[launcher]
author = Kris Hutchinson
description = Splidget? What's that? Well... its not an app per say but widgets and gadgets that provide useful functionality to your Splunk instance. This one is a repository for any text snippets you would like to save in a convenient Splunk app.
version = 1.2.5

[package]
check_for_updates = 1
id = spgt_splunkpad

[install]
state = enabled
