[source::...ta-fullhunt*.log*]
sourcetype = tafullhunt:log

[source::...ta_fullhunt*.log*]
sourcetype = tafullhunt:log

[fullhunt:organizations]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[fullhunt:domain]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[fullhunt:subdomains]
KV_MODE = json
MAX_TIMESTAMP_LOOKAHEAD = 12
SHOULD_LINEMERGE = 0
TIME_PREFIX = timestamp\"\:
TRUNCATE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
#TRANSFORMS-subdomain_host = set_host

[fullhunt:alerts]
KV_MODE = json
LINE_BREAKER = (\,)\{\"host
MAX_TIMESTAMP_LOOKAHEAD = 12
SEDCMD-remove_footer = s/(\])//g
SEDCMD-remove_header = s/(\[)//g
SEDCMD-rename_host = s/\"host\"\:/"f_host":/g
SHOULD_LINEMERGE = 0
TIME_PREFIX = timestamp\"\:
category = Splunk App Add-on Builder
pulldown_type = 1

[fullhunt:vulnerabilities]
KV_MODE = json
MAX_TIMESTAMP_LOOKAHEAD = 12
SEDCMD-rename_host = s/\"host\"\:/"f_host":/g
SEDCMD-rename_host_type = s/\"host_type\"\:/"f_host_type":/g
SHOULD_LINEMERGE = 0
TIME_PREFIX = identification_date\"\:\s+
category = Splunk App Add-on Builder
pulldown_type = 1

