[default]
[install]
is_configured = True
install_source_checksum = 026c4b89f70794d5c3d26f838f62485086b52b9d
build = 14

[launcher]
version = 2.0
description = Splunk App to receive events from the Cognia Cloud Platform
author = Nick Hills nick.hills@cognia.com

[package]
check_for_updates = 1
id = cognia-receiver

[ui]
label = Cognia Event Receiver
is_visible = 1

