[wso2carbon]
search = sourcetype=log4j TID=* message=* level=* function=*

[wso2audit]
search = sourcetype=log4j log_source=AUDIT_LOG Data=*

[wso2audit_auth]
search = Action=Login OR Action=Logout

[wso2audit_add_user]
search = Action="Add User" Target=*

[wso2audit_add_user]
search = Action="Add User" Target=*

[wso2audit_login_success]
search = Action=Login Result=Success

[wso2audit_update_success]
search = Action=Update Result=Success

[wso2audit_create_success]
search = Action=Create Result=Success

[wso2audit_update_org]
search = Action=Update Target_Org=*

[wso2audit_update_user]
search = Action=Update Target_User=*

[wso2audit_update]
search = Action=Update

[wso2audit_create]
search = Action=Create

[wso2audit_create_org]
search = Action=Create Target_Org=*

[wso2audit_change_password]
search = Action="Change Password*" Target=*

[wso2audit_privledged]
search = Action=* SSO_Domain="carbon.super"