#
# Splunk app configuration file
#

[package]
id = violin-app-fsp

[install]
is_configured = 0
build = 5

[ui]
is_visible = 1
label = Violin FSP App for Splunk

[launcher]
author = Crest Data System
description = This App builds dashboards on indexed data provided by Add-On app
version = 1.0.1

