
[expose:TA_armis_account]
pattern = TA_armis_account
methods = POST, GET

[expose:TA_armis_account_specified]
pattern = TA_armis_account/*
methods = POST, GET, DELETE

[expose:TA_armis_settings]
pattern = TA_armis_settings
methods = POST, GET

[expose:TA_armis_settings_specified]
pattern = TA_armis_settings/*
methods = POST, GET, DELETE

[expose:TA_armis_armis_alerts]
pattern = TA_armis_armis_alerts
methods = POST, GET

[expose:TA_armis_armis_alerts_specified]
pattern = TA_armis_armis_alerts/*
methods = POST, GET, DELETE

[expose:TA_armis_armis_api_alerts]
pattern = TA_armis_armis_api_alerts
methods = POST, GET

[expose:TA_armis_armis_api_alerts_specified]
pattern = TA_armis_armis_api_alerts/*
methods = POST, GET, DELETE

[expose:TA_armis_armis_device]
pattern = TA_armis_armis_device
methods = POST, GET

[expose:TA_armis_armis_device_specified]
pattern = TA_armis_armis_device/*
methods = POST, GET, DELETE

[expose:TA_armis_armis_vulnerability]
pattern = TA_armis_armis_vulnerability
methods = POST, GET

[expose:TA_armis_armis_vulnerability_specified]
pattern = TA_armis_armis_vulnerability/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
