
[expose:BeyondTrust_PMCloud_Integration_settings]
pattern = BeyondTrust_PMCloud_Integration_settings
methods = POST, GET

[expose:BeyondTrust_PMCloud_Integration_settings_specified]
pattern = BeyondTrust_PMCloud_Integration_settings/*
methods = POST, GET, DELETE

[expose:BeyondTrust_PMCloud_Integration_beyondtrust_pm_cloud_rest_api_client_events]
pattern = BeyondTrust_PMCloud_Integration_beyondtrust_pm_cloud_rest_api_client_events
methods = POST, GET

[expose:BeyondTrust_PMCloud_Integration_beyondtrust_pm_cloud_rest_api_client_events_specified]
pattern = BeyondTrust_PMCloud_Integration_beyondtrust_pm_cloud_rest_api_client_events/*
methods = POST, GET, DELETE

[expose:BeyondTrust_PMCloud_Integration_beyondtrust_pm_cloud_rest_api_audit_data]
pattern = BeyondTrust_PMCloud_Integration_beyondtrust_pm_cloud_rest_api_audit_data
methods = POST, GET

[expose:BeyondTrust_PMCloud_Integration_beyondtrust_pm_cloud_rest_api_audit_data_specified]
pattern = BeyondTrust_PMCloud_Integration_beyondtrust_pm_cloud_rest_api_audit_data/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET

