[script://$SPLUNK_HOME/etc/apps/strikereadyapp/bin/database.py]
disabled = 0
python.version = python3
index = strikeready
interval = -1
sourcetype = _json
passAuth = splunk-system-user

[taxii_feed]
python.version = python3
interval = 3600
index = strikeready_taxii2.1
sourcetype = _json
verify_ssl = 0
disabled = 0



# [script://$SPLUNK_HOME/etc/apps/Strikereadyapp/bin/retro.py]
# disabled = 0
# interval = 1800
# passAuth = splunk-system-user