[script:strikereadyapp]
match                 = /strikeready
script                = resthandler.py
passPayload           = true
scripttype            = persist
handler               = application.StrikeReady
requireAuthentication = true
output_modes          = json
passHttpHeaders       = true
passHttpCookies       = true
python.version = python3



[script:indexs]
match                 = /indexes
script                = indexes.py
scripttype            = persist
handler               = indexes.Indexes
requireAuthentication = true
output_modes          = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true
python.version = python3

[script:deploy]
match                 = /deploy
script                = deploy_ioc.py
scripttype            = persist
handler               = deploy_ioc.DeployIoc
requireAuthentication = true
output_modes          = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true
python.version = python3

[script:searchresults]
match                 = /searchresults
script                = searchresults.py
scripttype            = persist
handler               = searchresults.SearchResults
requireAuthentication = true
output_modes          = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true
python.version = python3