[default]
# Set property defaults
display.visualizations.custom.SA_GVZ.graphviz_plan.grouping = expanded
display.visualizations.custom.SA_GVZ.graphviz_plan.timeSpan = 5
display.visualizations.custom.SA_GVZ.graphviz_plan.hourPivot = 14
display.visualizations.custom.SA_GVZ.graphviz_plan.alignment = end
