# Copyright (C) 2005-2016 Splunk Inc. All Rights Reserved.

# DO NOT EDIT THIS FILE
# This file configuration file must not be edited manually because others files
# must be updated to apply the modifications such as server.vmopts and commands.conf.
# This file is edited by dbx_settings.py. Please use the UI or the API to apply
# some modifications on stanzas defined below.


[java]
javaHome = <string>
# optional
# Specifies the path to Java home. The path defined will be used to resolve the
# java command location. Typically, the /bin/java or \bin\java.exe will be
# appended to this path to resolve the command location on *nix and windows
# respectively.
# If not specified the JAVA_HOME environment variable is used.
# If JAVA_HOME is also undefined, java command is directly used. In that case,
# java command must be defined in the PATH environment variable.

queryServerSocketTimeout = <integer>
# The timeout (in seconds) for socket communication between the Python process and the Java-based Query Server. This controls how long the system waits when reading from or writing to the server.
# Default is 300 seconds (5 minutes).
# 0 means no timeout.

queryServerStdinTimeout = <integer>
# The timeout (in seconds) for receiving data through standard input. This determines how long the system waits for input before the command times out.
# Default is 60 seconds (1 minute).
# 0 means no timeout.

[loglevel]
dbxquery = [TRACE | DEBUG | INFO | WARN | ERROR]
# set the log level for dbxquery command

dbxoutput = [TRACE | DEBUG | INFO | WARN | ERROR]
# set the log level for dbxoutput command

dbxlookup = [TRACE | DEBUG | INFO | WARN | ERROR]
# set the log level for dbxlookup command

input = [TRACE | DEBUG | INFO | WARN | ERROR]
# set the log level for db inputs

output = [TRACE | DEBUG | INFO | WARN | ERROR]
# set the log level for db outputs

connector = [TRACE | DEBUG | INFO | WARN | ERROR]
# set the log level for all the interactions with DBs

processor = [TRACE | DEBUG | INFO | WARN | ERROR]
# set the log level for all the interactions involving HEC

other = [TRACE | DEBUG | INFO | WARN | ERROR]
# Set the log level for others features

[hec]
# when HEC failed to forward data to Splunk Indexer, it will return 503 error,
# then DBX will retry 3 times by default with exponential backoff
maxRetryWhenHecUnavailable = <integer>

# maxHecContentLength setup max event size, default is 10MB
maxHecContentLength = <integer>

# Comma separated HEC URIs: https://<idx-host1>:8088,https://<idx-host2>:8088,...
hecUris = <string>

# Comma separated HEC token per HEC URIs
# In case a single token is provided, then it will be used for each HEC
hecToken = <string>

# Lower case field name for backward compatibility with dbx 1.x
# By default it is false
hecFieldNameLowerCase = <true|false>

[security]
denylist = <string>
# Comma separated IP addresses or domain names to be denied when configuring HEC URIs or others

[synchronizer]
enabled = <true|false>
# Enable/disable synchronization between KV Store and local files
# By default is true

[telemetry]
enabled = <true|false>
# Enable/disable telemetry data collection from the API
# By default is true

[cluster]
hosts = <string>
# Comma separated IP addresses and ports of the cluster members

user = <string>

password = <string>
# The encrypted value of the password

tlsEnabled = <true|false>
# Enable/disable TLS
# By default is false

[splunkbase_api]
url = <string>
# Base URL for Splunkbase API.
