[monitor:///opt/splunk/etc/apps/MaX/ExchangeLog_2003]
#/opt/splunk/etc/apps/SplunkforExchange/ExchangeLog_2003
sourcetype=exchangelog2003


[monitor:///opt/splunk/etc/apps/MaX/ExchangeLog_2007]
sourcetype=exchangelog2007
