[default]
[script://$SPLUNK_HOME/etc/apps/sentinelone_TA/bin/activity.py]
start_by_shell = false
disabled = 0
index = sentinelone
sourcetype = activity
interval = 60

[script://$SPLUNK_HOME/etc/apps/sentinelone_TA/bin/activity_type.py]
start_by_shell = false
disabled = 0
sourcetype = activity_type
interval = 60

[script://$SPLUNK_HOME/etc/apps/sentinelone_TA/bin/agent.py]
start_by_shell = false
disabled = 0
index = sentinelone
sourcetype = agent
interval = 60

[script://$SPLUNK_HOME/etc/apps/sentinelone_TA/bin/group.py]
start_by_shell = false
disabled = 0
index = sentinelone
sourcetype = group
interval = 60

[script://$SPLUNK_HOME/etc/apps/sentinelone_TA/bin/policy.py]
start_by_shell = false
disabled = 0
index = sentinelone
sourcetype = policy
interval = 60

[script://$SPLUNK_HOME/etc/apps/sentinelone_TA/bin/threat.py]
start_by_shell = false
disabled = 0
index = sentinelone
sourcetype = threat
interval = 60

