# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 9

[launcher]
author = fdse@splunk.com
version = 1.1.6
description = Splunk Add-on for Canvas API. (Version 1.0.0 contains the following:Published Courses,Total Teachers,Total Students,Total Users,File Uploaded,File Storage,Media Uploaded,Media Storage)Please reach out to FSDE@splunk.com for further development.

[ui]
is_visible = 1
label = Canvas Add-on for Splunk
docs_section_override = AddOns:released

[package]
id = canvas-add-on-for-splunk

[triggers]
reload.addon_builder = simple
reload.canvas_add_on_for_splunk_account = simple
reload.canvas_add_on_for_splunk_settings = simple
reload.passwords = simple

