# Splunk app configuration file
[package]
id = adguardhome

[install]
is_configured = 0

[ui]
is_visible = 1
label = AdGuardHome

[launcher]
author = kyzdra
description = Dashboard AdGuardHome
version = 0.1.1

[id]
name = adguardhome
version = 0.1.1

