[crogl_health_check]
start_by_shell = false
python.version = python3
sourcetype = crogl:healthcheck
interval = 30
base_url = https://127.0.0.1
disabled = 0

[crogl_health_check://croglhealthchecker]
base_url = https://demo.crogl.com
interval = 60

