
[admin:canvas_add_on_for_splunk]
match = /
members = canvas_add_on_for_splunk_account, canvas_add_on_for_splunk_settings, canvas_add_on_for_splunk_published_courses, canvas_add_on_for_splunk_total_teachers, canvas_add_on_for_splunk_total_students, canvas_add_on_for_splunk_total_users, canvas_add_on_for_splunk_file_uploaded, canvas_add_on_for_splunk_file_storage, canvas_add_on_for_splunk_media_uploaded, canvas_add_on_for_splunk_media_storage

[admin_external:canvas_add_on_for_splunk_account]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_settings]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_published_courses]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_published_courses.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_total_teachers]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_total_teachers.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_total_students]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_total_students.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_total_users]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_total_users.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_file_uploaded]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_file_uploaded.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_file_storage]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_file_storage.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_media_uploaded]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_media_uploaded.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:canvas_add_on_for_splunk_media_storage]
handlertype = python
python.version = python3
handlerfile = canvas_add_on_for_splunk_rh_media_storage.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
