[test_traces_stream]
python.version = python3
python.required = 3.9, 3.13
index = default
related_paths = 0
sourcetype = cisco:thousandeyes:trace

[test_metrics_stream]
python.version = python3
index = default
interval = 300
python.required = 3.9, 3.13
related_paths = 0
sourcetype = cisco:thousandeyes:path-vis

[event]
python.version = python3
index = default
interval = 3600
python.required = 3.9, 3.13
sourcetype = cisco:thousandeyes:event

[activity_logs_stream]
python.version = python3
python.required = 3.9, 3.13
index = default
sourcetype = cisco:thousandeyes:activity

[alerts_stream]
python.version = python3
python.required = 3.9, 3.13
index = default
sourcetype = cisco:thousandeyes:alerts

[thousandeyes_refresh_tokens]
python.version = python3
python.required = 3.9, 3.13

[thousandeyes_refresh_tokens://default]
python.version = python3
python.required = 3.9, 3.13
index = default
disabled = false
interval = 604800
account_refresh_sleep_interval = 60
dry_run = false

[monitor://$SPLUNK_HOME/var/log/splunk/thousandeyes_refresh_tokens.log]
python.version = python3
disabled = false
index = _internal
sourcetype = cisco:thousandeyes:refresh-tokens
