[eventtype=omnis_dns]
network = enabled
resolution = enabled
dns = enabled

[eventtype=omnis_icmp]
network = enabled
communicate = enabled

[eventtype=omnis_smb]
network = enabled
communicate = enabled

[eventtype=omnis_http]
web = enabled

[eventtype=omnis_https]
web = enabled

[eventtype=omnis_base]
network = enabled
communicate = enabled

[eventtype=omnis_certificate]
certificate = enabled
ssl = enabled

[eventtype=omnis_pop]
email = enabled

[eventtype=omnis_imap]
email = enabled

[eventtype=omnis_smtp]
email = enabled


