[alarms]
search = sourcetype="grid:rest:api" endpoint="Alarms"
# tag = alert

[available_memory]
search = sourcetype="grid:rest:api" endpoint="Available_Memory"
# tag = performance tag=memory

[average_ilm_evaluation_time]
search = sourcetype="grid:rest:api" endpoint="Average_ILM_Evaluation_Time"

[average_query_latency]
search = sourcetype="grid:rest:api" endpoint="Average_Query_Latency"
# tag = performance tag=storage

[cpu_load]
search = sourcetype="grid:rest:api" endpoint="CPU_Load"
# tag = performance tag=cpu

[health_topology_depth_component]
search = sourcetype="grid:rest:api" endpoint="Health_topology_depth_component"
# tag = alert

[health_topology_depth_node]
search = sourcetype="grid:rest:api" endpoint="Health_topology_depth_node"
# tag = alert

[installed_storage_capacity]
search = sourcetype="grid:rest:api" endpoint="Installed_Storage_Capacity"
# tag = performance tag=storage

[total_storage_capacity]
search = sourcetype="grid:rest:api" endpoint="Total_Storage_Capacity"
# tag = performance tag=storage

[usable_storage_capacity]
search = sourcetype="grid:rest:api" endpoint="Usable_Storage_Capacity"
# tag = performance tag=storage

[used_storage_capacity_databytes]
search = sourcetype="grid:rest:api" endpoint="Used_Storage_Capacity_DataBytes"
# tag = performance tag=storage

[used_storage_capacity_metabytes]
search = sourcetype="grid:rest:api" endpoint="Used_Storage_Capacity_MetaBytes"
# tag = performance tag=storage
