[eventtype=alarms]
alert = enabled

[eventtype=available_memory]
performance = enabled
memory = enabled

[eventtype=average_query_latency]
performance = enabled
storage = enabled

[eventtype=cpu_load]
performance = enabled
cpu = enabled

[eventtype=health_topology_depth_component]
alert = enabled

[eventtype=health_topology_depth_node]
alert = enabled

[eventtype=installed_storage_capacity]
performance = enabled
storage = enabled

[eventtype=total_storage_capacity]
performance = enabled
storage = enabled

[eventtype=usable_storage_capacity]
performance = enabled
storage = enabled

[eventtype=used_storage_capacity_databytes]
performance = enabled
storage = enabled

[eventtype=used_storage_capacity_metabytes]
performance = enabled
storage = enabled
