[gigamon_ipfix_idx]
search = index=main

[gigamon_sourcetype]
search = sourcetype=stream:netflow

[ipfix_events]
search = eventtype=gigamon_ipfix_idx eventtype=gigamon_sourcetype

[gigamon_base_errors]
search = index=_internal  sourcetype=streamfwd* OR sourcetype=splunk_app_stream*

[gigamon_bad_vocab]
search = eventtype=gigamon_base_errors FATAL Failed to start streamfwd gigamon

[gigamon_no_fwd_start]
search = eventtype=gigamon_base_errors FATAL Unable to start

[gigamon_vocab_mapping]
search = eventtype=gigamon_base_errors Ignoring NetFlow Element Id, Vocabulary Term mapping for Element Id ERROR

[gigamon_unknown_event_type]
search = eventtype=gigamon_base_errors Unable to update streams config unknown event type ERROR

[ipfix_http_events]
search = eventtype=ipfix_events dest_port{}=80 OR dest_port{}=443

[ipfix_dns_events]
search = eventtype=ipfix_events dest_port{}=53

[gigamon_invalid_stream]
search = eventtype=gigamon_base_errors Invalid Stream definition for stream
