[admin:safezone_audit_configuration]
match = /
members = safezone_audit_account, safezone_audit_settings

[admin:safezone_audit_inputs]
match = /
members = safezone_audit_safezone_audit

[admin_external:safezone_audit_account]
handlertype = python
python.version = python3
handlerfile = safezone_audit_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:safezone_audit_settings]
handlertype = python
python.version = python3
handlerfile = safezone_audit_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:safezone_audit_safezone_audit]
handlertype = python
python.version = python3
handlerfile = safezone_audit_rh_safezone_audit.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
