# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 7

[launcher]
author = John Barnett
version = 1.0.0
description = TA containing the shell scripts that were bundled with the freenas app

[ui]
is_visible = 0
label = Freenas TA
docs_section_override = AddOns:released

[package]
id = TA-freenas

[triggers]
reload.addon_builder = simple
reload.ta_freenas_account = simple
reload.ta_freenas_settings = simple
reload.passwords = simple

