[sysdig_secure_vulnerabilities]
start_by_shell = false
python.version = python3
python.required = 3.9, 3.13
sourcetype = sysdig:secure:vulnerabilities
interval = 86400
vulnerability_details = ['package_data']
disabled = 0

