
[admin:TA_assetnote]
match = /
members = TA_assetnote_account, TA_assetnote_settings, TA_assetnote_assetnote_assetgroups_download, TA_assetnote_assetnote_triagestatistics_download, TA_assetnote_assetnote_auditlogs_download, TA_assetnote_assetnote_usereventlogs_download, TA_assetnote_assetnote_assets_download, TA_assetnote_assetnote_exposures_download

[admin_external:TA_assetnote_account]
handlertype = python
handlerfile = TA_assetnote_rh_account.py
handleractions = edit, list, remove, create
python.version = python3
python.required = 3.9

[admin_external:TA_assetnote_settings]
handlertype = python
handlerfile = TA_assetnote_rh_settings.py
handleractions = edit, list
python.version = python3
python.required = 3.9

[admin_external:TA_assetnote_assetnote_assetgroups_download]
handlertype = python
handlerfile = TA_assetnote_rh_assetnote_assetgroups_download.py
handleractions = edit, list, remove, create
python.version = python3
python.required = 3.9

[admin_external:TA_assetnote_assetnote_triagestatistics_download]
handlertype = python
handlerfile = TA_assetnote_rh_assetnote_triagestatistics_download.py
handleractions = edit, list, remove, create
python.version = python3
python.required = 3.9

[admin_external:TA_assetnote_assetnote_auditlogs_download]
handlertype = python
handlerfile = TA_assetnote_rh_assetnote_auditlogs_download.py
handleractions = edit, list, remove, create
python.version = python3
python.required = 3.9

[admin_external:TA_assetnote_assetnote_usereventlogs_download]
handlertype = python
handlerfile = TA_assetnote_rh_assetnote_usereventlogs_download.py
handleractions = edit, list, remove, create
python.version = python3
python.required = 3.9

[admin_external:TA_assetnote_assetnote_assets_download]
handlertype = python
handlerfile = TA_assetnote_rh_assetnote_assets_download.py
handleractions = edit, list, remove, create
python.version = python3
python.required = 3.9

[admin_external:TA_assetnote_assetnote_exposures_download]
handlertype = python
handlerfile = TA_assetnote_rh_assetnote_exposures_download.py
handleractions = edit, list, remove, create
python.version = python3
python.required = 3.9

