[ui]
is_visible = 1
label = Phishing Lookup

[launcher]
author = Nimish Doshi
description = Uses phishtank data store to correlate known phishing sites with indexed events
version=1.1

[package]
id=phishing
