[update_repdata]
index = default
start_by_shell = false
python.version = python3
sourcetype = etintel:repdata

[update_repdata://update_repdata]
check_file_integrity = 1
interval = 3600
disabled = 1
python.version = python3

[threatlist]
python.version = python3

[threatlist://etintel_ip_repdata]
description = Proofpoint ETIntel IP Reputation Data
fields = ip:$1,description:"$8"
type = Emerging Threats
url = lookup://et_ip_repdata
delim_regex = ,
ignore_regex = (^#|^\s*$)
interval = 600
retries = 3
retry_interval = 60
skip_header_lines = 1
timeout = 30
weight = 100
python.version = python3

[threatlist://etintel_domain_repdata]
description = "Proofpoint ETIntel Domain Reputation Data"
disabled = 0
fields = domain:"$1",description:"$8"
type = Emerging Threats
url = lookup://et_domain_repdata
delim_regex = ,
ignore_regex = (^#|^\s*$)
interval = 600
retries = 3
retry_interval = 60
skip_header_lines = 1
timeout = 30
weight = 100
python.version = python3
