[admin:check_point_block_config]
match = /
members= check_point_block_config

[admin_external:check_point_block_config]
handlertype = python
python.version = python3
handlerfile = check_point_block_config.py
handleractions = list, edit