
[admin:TA_claroty_add_on_for_splunk]
match = /
members = TA_claroty_add_on_for_splunk_account, TA_claroty_add_on_for_splunk_settings, TA_claroty_add_on_for_splunk_alerts_, TA_claroty_add_on_for_splunk_baselines_, TA_claroty_add_on_for_splunk_events_, TA_claroty_add_on_for_splunk_assets_

[admin_external:TA_claroty_add_on_for_splunk_account]
handlertype = python
python.version = python3
handlerfile = TA_claroty_add_on_for_splunk_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_claroty_add_on_for_splunk_settings]
handlertype = python
python.version = python3
handlerfile = TA_claroty_add_on_for_splunk_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_claroty_add_on_for_splunk_alerts_]
handlertype = python
python.version = python3
handlerfile = TA_claroty_add_on_for_splunk_rh_alerts_.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_claroty_add_on_for_splunk_baselines_]
handlertype = python
python.version = python3
handlerfile = TA_claroty_add_on_for_splunk_rh_baselines_.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_claroty_add_on_for_splunk_events_]
handlertype = python
python.version = python3
handlerfile = TA_claroty_add_on_for_splunk_rh_events_.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_claroty_add_on_for_splunk_assets_]
handlertype = python
python.version = python3
handlerfile = TA_claroty_add_on_for_splunk_rh_assets_.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
