[eventtype=claroty_cef_Alert]
alert = enabled

[eventtype=claroty_assets]
ot_asset = enabled
ot_assets = disabled
ot_sw_asset = disabled
ot_asset_sw = disabled

[eventtype=claroty_events]
alert = enabled

[eventtype=claroty_alerts]
alert = enabled

[eventtype=claroty_cef_Event]
alert = enabled

[eventtype=claroty_baselines]
communicate = enabled
network = enabled

[eventtype=claroty_cef_Insight]
vulnerability = enabled
report = enabled

[eventtype=claroty_cef_HealthCheck]
performance = enabled
cpu = enabled
OR = disabled
facilities = enabled
memory = enabled
storage = enabled
network = enabled
(os = enabled
(uptime = enabled
(time = enabled
synchronize))) = enabled
(cpu = enabled
synchronize)))) = enabled
os = enabled

[eventtype=claroty_cef_ActivityLog]
modaction = disabled
change = enabled
audit = enabled

[eventtype=claroty_cef_Vulnerability]
vulnerability = enabled
report = enabled

