[default]

[install]
is_configured = 0

[id]
name = hydroquebec_pannes_et_interruptions
version = 3.2.2

[launcher]
author = alexandre@argeris.net
description = Application de surveillance des pannes, interruptions planifiées et demande d'électricité en temps réel d'Hydro-Québec
version = 3.2.2

[package]
id = hydroquebec_pannes_et_interruptions

[ui]
is_visible = 1
label = Hydro-Québec

