[json:blueprism]
SHOULD_LINEMERGE = false
KV_MODE = json
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%6N%z
TIME_PREFIX = StartDate":"
TRANSFORMS-bp_st_fixup = blueprism_sourcetype
FIELDALIAS-EventDataA = EventData.PageName AS page_name EventData.StageName AS stage_name EventData.SessionNumber AS session_id 
FIELDALIAS-EventDataB = EventData.StageType AS stage_type EventData.ProcessName AS process_name EventData.Result AS result
EVAL-process_name = case(match(process_name, "^$"), "NA", isnull(process_name), "NA", true(), process_name)

[json:blueprism:epoch]
SHOULD_LINEMERGE = false
KV_MODE = json
TIME_PREFIX = ,\d{10}$
TIME_FORMAT = %s
EVAL-process_name = case(match(process_name, "^$"), "NA", isnull(process_name), "NA", true(), process_name)



