[launcher]
version = 1.0.0
description = Team Cymru Feed App For Splunk
author = Team Cymru

[id]
version = 1.0.0
name = TeamCymruFeedAppForSplunk

[install]
is_configured = false
state = enabled

[package]
id = TeamCymruFeedAppForSplunk
check_for_updates = true

[ui]
label = Team Cymru Feed App For Splunk
supported_themes = light, dark
is_visible = true

[triggers]
reload.TeamCymruFeedAppForSplunk_settings = simple
reload.TeamCymruFeedAppForSplunk_account = simple
