# header can't be extracted because of the delimiter is '|'

# host special fields

[extract_rt]
REGEX = rt=(?<rt_val>\d+)

[extract_device_mac_address]
REGEX = dvc_mac_address=(?<device_mac_address_val>[a-fA-F0-9:]+)

[extract_dvc]
REGEX = dvc=(?<dvc_val>[0-9.]+)

[extract_dvc_host]
REGEX = dvchost=(?<dvchost_val>[^\s]+)  

# event special fields
# dvc=(?P<dvc>[0-9.]+)cnt=(?P<cnt>[0-9]+)( cs1=(?P<cs1>[^ ]+))?( cs1Label=(?P<cs1Label>.+))?( cs2=(?P<cs2>[^ ]+))?( cs2Label=(?P<cs2Label>.+))? rt=(?P<rt>\d+) src=(?P<src>[0-9.]+) dst=(?P<dst>[0-9.]+) app=(?P<app>.+) cn1=(?P<cn1>[0-9.]+) cn1Label=(?P<cn1Label>.+) cat=(?P<cat>\w+) ExternalID=(?P<ExternalID>.+) dvchost=(?P<dvchost>[^ ]+) cfp1=(?P<cfp1>[0-9.]+) cfp1Label=(? P <cfp1Label> [^ ] + ) ? ( cs4 = ( ? P <cs4> \ w + ) ) ? ( cs4Label = ( ? P <cs4Label> \ w + ) ) ? ( cs5 = ( ? P <cs5> \ w + ) ) ? ( cs5Label = ( ? P <cs5Label> \ w + ) ) ? ( type = ( ? P <type> \ w + ) ) )
[extract_dvc]
REGEX = dvc=(?<dvc_val>[0-9.]+)

[extract_cnt]
REGEX = cnt=(?<cnt_val>[0-9]+)

[extract_cs1]
REGEX = cs1=(?<cs1_val>[^\s]+)

[extract_cs1Label]
REGEX = cs1Label=(?<cs1_label>.*?)(?=\s\w+=|$)

[extract_cs2]
REGEX = cs2=(?<cs2_val>[^\s]+)

[extract_cs2Label]
REGEX = cs2Label=(?<cs2_label>.*?)(?=\s\w+=|$)

[extract_rt]
REGEX = rt=(?<rt_val>\d+)

[extract_smac]
REGEX = smac=(?<smac_val>[a-fA-F0-9:]+)

[extract_dmac]
REGEX = dmac=(?<dmac_val>[a-fA-F0-9:]+)
[extract_src]
REGEX = src=(?<src_ip>[0-9.]+)

[extract_dst]
REGEX = dst=(?<dst_ip>[0-9.]+)

[extract_app]
#REGEX = app=(?<app_val>.*?)(?=\s\w+=|$)
REGEX = app=(?<app_val>.*?)(?= cn1=|$)

[extract_cn1]
REGEX = cn1=(?<cn1_val>[0-9.]+)

[extract_cn1Label]
REGEX = cn1Label=(?<cn1_label>.*?)(?=\s\w+=|$)

[extract_cat]
REGEX = cat=(?<cat_val>\w+)

[extract_ExternalID]
REGEX = ExternalID=(?<ExternalID_val>.*?)(?=\s\w+=|$)

[extract_dvchost]
REGEX = dvchost=(?<dvchost_val>[^\s]+)

[extract_cfp1]
REGEX = cfp1=(?<cfp1_val>[0-9.]+)

[extract_cfp1Label]
REGEX = cfp1Label=(?<cfp1_label>.*?)(?=\s\w+=|$)

[extract_cs4]
REGEX = cs4=(?<cs4_val>\w+)

[extract_cs4Label]
REGEX = cs4Label=(?<cs4_label>\w+)

[extract_cs5]
REGEX = cs5=(?<cs5_val>\w+)

[extract_cs5Label]
REGEX = cs5Label=(?<cs5_label>\w+)

[extract_type]
REGEX = type=(?<type_val>\w+)
