
[expose:TA_pingone_advanced_identity_cloud_settings]
pattern = TA_pingone_advanced_identity_cloud_settings
methods = POST, GET

[expose:TA_pingone_advanced_identity_cloud_settings_specified]
pattern = TA_pingone_advanced_identity_cloud_settings/*
methods = POST, GET, DELETE

[expose:TA_pingone_advanced_identity_cloud_tenant]
pattern = TA_pingone_advanced_identity_cloud_tenant
methods = POST, GET

[expose:TA_pingone_advanced_identity_cloud_tenant_specified]
pattern = TA_pingone_advanced_identity_cloud_tenant/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
