[claroty_ot_assets_collector]
action.email.useNSSubject = 1
action.email.use_ssl = 1
action.keyindicator.invert = 0
action.makestreams.param.verbose = 0
action.nbtstat.param.verbose = 0
action.notable.param.verbose = 0
action.nslookup.param.verbose = 0
action.ping.param.verbose = 0
action.risk.forceCsvResults = 1
action.risk.param.verbose = 0
action.send2uba.param.verbose = 0
action.threat_add.param.verbose = 0
action.webhook.enable_allowlist = 0
alert.track = 0
cron_schedule = */5 * * * *
dispatch.index_earliest = -5m@m
dispatch.index_latest = now
display.general.timeRangePicker.show = 0
search = tag=ot_asset\
\
| makemv ip delim="|"\
\
| mvexpand ip ```split multiple ip's into multiple records```\
\
| eval ip=if(ip="null", "", ip), nt_host=if(nt_host="null", "", nt_host), dns=if(dns="null", "", dns), mac=if(mac="null", "", mac) ```remove any null string values```\
\
| rex field=ip ".*?(?<ip>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}).*?"\
\
| eval ip=if(match(ip, "^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$"), ip, "") ```check to verify ip is an actual ip - if you are using IPv6 you need to change this```\
\
| fillnull ip, dns, nt_host, mac value=""\
\
| makemv mac delim="|"\
\
| mvexpand mac  ```split multiple macs into multiple records```\
\
| eventstats count as mac_count by mac ```this eliminates any questionable mac's that may be repeated```\
\
| eval mac=if(mac_count > 1, "", mac)\
\
| dedup ip, dns, nt_host, mac\
\
| eval last_updated=strftime(_time, "%Y-%m-%dT%H:%M:%S.%3N")\
\
| table last_updated, asset_id, asset_model, asset_status, asset_system, asset_type, asset_vendor, asset_version, asset_criticality, bunit, category, city, classification, country, description, dns, end_of_support, exposure,ip, is_expected, lat, long, location, mac, nt_host, owner, parent_asset_id, pci_domain, priority, requires_av, serial, should_timesync, should_update, site_id, vlan, zone\
\
| append [inputlookup claroty_ot_assets_lookup]\
\
| sort - last_updated\
\
| dedup asset_id\
\
| outputlookup create_context=app claroty_ot_assets_lookup\

