
[bitwarden_userStatus_lookup]
default_match = Unknown
filename = bitwarden_userStatus.csv

[bitwarden_userType_lookup]
default_match = Unknown
filename = bitwarden_userType.csv

[bitwarden_signature_lookup]
default_match = Unknown
filename = bitwarden_signatures.csv

[bitwarden_deviceType_lookup]
default_match = Unknown
filename = bitwarden_deviceType.csv

[bitwarden_users]
collection = bitwarden_users
external_type = kvstore
fields_list = _time,user_bitwarden_id,user_email,user_name,user_bitwarden_groups,user_bitwarden_risk,user_bitwarden_type

[bitwarden_groups]
collection = bitwarden_groups
external_type = kvstore
fields_list = _time,id,group_bitwarden_id,group_name,group_risk,user_bitwarden_id
