[code42_api_errors]
title = Code42 API Errors
category = API
tags = api
description = This checks whether there are errors reaching the Code42 API.
failure_text = API calls to Code42 API are failing.
suggested_action = Check the Code42 error message for possible cause of failure.
search = `code42_mc_health_check_api`