#
# Splunk app configuration file
#
[package]
id = VTThreatIntelligence
check_for_updates = 1

[install]
is_configured = 0

[ui]
is_visible = 1
label = VTThreatIntellIgence

[launcher]
author = Manuel Bermudez
description = Analice your virustotal Intelligence hunting. Hunting malware like sir
version = 2.1
