[launcher]
version = 1.1.0
description = OpenCTI for Splunk Enterprise
author = Filigran

[id]
version = 1.1.0
name = TA-opencti-for-splunk-enterprise

[install]
build = 1780351974
is_configured = false
state = enabled

[package]
id = TA-opencti-for-splunk-enterprise
check_for_updates = true

[ui]
label = OpenCTI for Splunk Enterprise
supported_themes = light, dark
is_visible = true

[triggers]
reload.ta-opencti-for-splunk-enterprise_settings = simple
