
[admin:TA_radware_csms_ddos_events_collector]
match = /
members = TA_radware_csms_ddos_events_collector_settings, TA_radware_csms_ddos_events_collector_csms_radware_ddos_api

[admin_external:TA_radware_csms_ddos_events_collector_settings]
handlertype = python
python.version = python3
handlerfile = TA_radware_csms_ddos_events_collector_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_radware_csms_ddos_events_collector_csms_radware_ddos_api]
handlertype = python
python.version = python3
handlerfile = TA_radware_csms_ddos_events_collector_rh_csms_radware_ddos_api.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
