# Declare shared visualizations
#

[sankey-viz]
label = Sankey Viz
description = Show metric flow between categories.
search_fragment =... | stats count by category1, category2, category3
allow_user_selection = true
disabled = 0
supports_trellis = false
supports_drilldown = true
