[jobinfo]
LINE_BREAKER=([\r\n]+)Job Name
CHARSET=UTF-8
MAX_TIMESTAMP_LOOKAHEAD=50
SHOULD_LINEMERGE=false
TIME_FORMAT=%a %b %d %H:%M:%S %Y
TIME_PREFIX=Last Run Time\s*\:\s*
TRUNCATE=999999
REPORT-field_extractions  =     jobinfo-extractions-1,jobinfo-extractions-2
EVAL-Time_Taken_Seconds= round(strptime(Last_Run_Time,"%a %b %d %H:%M:%S %Y") - strptime(Job_Start_Time,"%a %b %d %H:%M:%S %Y"))
EXTRACT-job_name = .*/(?<Job_Name>.*)?_\d+\.JobInfo in source
EXTRACT-runtime_from_source =  \w+\_(?<filedatetime>\d+)\.JobInfo in source

[dstagexml]
BREAK_ONLY_BEFORE = \<Stage\sName
NO_BINARY_CHECK = true
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
TIME_PREFIX = StartDateTime\=
KV_MODE = xml
category = Custom
disabled = false
pulldown_type = true
MUST_BREAK_AFTER = </Stage>
TRANSFORMS-changesourcetype = set_sourcetype
SEDCMD-removeunwanted1 = s/\<\/ComponentSet\>//
SEDCMD-removeunwanted2 = s/\<\/Job\>//
SEDCMD-removeunwanted3 = s/\<ComponentSet\>//
SEDCMD-removeunwanted4 = s/\<\?.*\n\<.*\n\s*Desc.*\n\s*Status.*\n\s*WaveNo.*\n\s*StartDate.*\n\s*EndDate.*\n\s*Elapsed.*\n\s*Elapsed.*\n//
EXTRACT-job_name = .*/(?<Job_Name>.*)?_\d+\.XML in source
EXTRACT-runtime_from_source =  \w+\_(?<filedatetime>\d+)\.XML in source
EVAL-Last_Run_Time=strftime(round(strptime(filedatetime,"%Y%m%d%H%M%S")),"%a %b %d %H:%M:%S %Y")
FIELDALIAS-Stage_Name = "Stage{@Name}" AS Stage_Name



[logsum]
TIME_PREFIX = ^\d+\s+\w+\s
TIME_FORMAT = %a %b %d %H:%M:%S %Y
MAX_TIMESTAMP_LOOKAHEAD = 25
SHOULD_LINEMERGE = true
#LINE_BREAKER = ([\n\r]+)
TRUNCATE = 10000
KV_MODE = none
BREAK_ONLY_BEFORE_DATE = true
EXTRACT-field_all = ^(?P<event_number>\d+)\s*(?P<log_type>\w*)\t(?P<date>[\w \:]+)\n\s*((?P<Stage_Name>.*?:)?)(?P<description>.*)
EXTRACT-field_time = ^\d*\t\w*\t\w*\s\w*\s\d*\s(?P<time>\d{2}:\d{2}:\d{2})
EXTRACT-job_name = .*/(?<Job_Name>.*)?_\d+\.LogSum in source
EXTRACT-runtime_from_source =  \w+\_(?<filedatetime>\d+)\.LogSum in source
EVAL-description=replace(description, "\"", "")