[madprops_sourcetypes_whitelist_lookup_base]
filename = madprops_sourcetypes_whitelist_lookup_base.csv

[madprops_parameters_whitelist_lookup_base]
filename = madprops_parameters_whitelist_lookup_base.csv

[madprops_apps_whitelist_lookup_base]
filename = madprops_apps_whitelist_lookup_base.csv

[madprops_sourcetypes_whitelist_lookup]
filename = madprops_sourcetypes_whitelist_lookup.csv

[madprops_parameters_whitelist_lookup]
filename = madprops_parameters_whitelist_lookup.csv

[madprops_apps_whitelist_lookup]
filename = madprops_apps_whitelist_lookup.csv

[madprops_active_sourcetypes_lookup]
filename = madprops_active_sourcetypes_lookup.csv
