[manufacturer-command]
syntax = manufacturer (<manufacturer-options>)+
shortdesc = Search for matching manufacturer and output the common format
description = Search for matching manufacturer in lookup bah_manufacturers and output the common format of the name. Must specify the field that contains the manufacturer.
usage = public
example1 = manufacturer field=vendor
comment1 = Uses the value of the field 'vendor' to lookup a matching manufacturer name
related = 
tags = manufacturer

[manufacturer-options]
syntax = field=<field> | threshold=<decimal>
description = The manufacturer command takens a given field with a manufacturer\
and looks up the name in bah_manufacturers to determine the best matching name\
to output the manufacturer in standard format.

[searchtrigger-command]
syntax = searchtrigger (<searchtrigger-options>)+
shortdesc = Run a follow on search with various parameters.
description = Run the named saved search, overriding any tokens desired.
usage = public
example1 = searchtrigger search_name="New Search Name" field:override
comment1 = Runs search "New Search Name", overriding the token $args.field$ with the value of the\
field "override" in the current search
related = 
tags = manufacturer

[searchtrigger-options]
syntax = search_name=<string> | use_all_values=<bool> | mvdelim=<string>
description = The manufacturer command takens a given field with a manufacturer\
and looks up the name in bah_manufacturers to determine the best matching name\
to output the manufacturer in standard format.
