# Investigate configuration

[data-fields]
disabled = 0
fields = 

[user-exclusion-list]
disabled = 0
excluded-entities =

[umbrella-exclusion-list]
disabled = 0
umbrella-top-limit =

[scheduled-report]
disabled = 0
report-name =

[timestamp-pruning]
disabled = 0
time-modifier =

[size-pruning]
disabled = 0
size-pruning-max =

[proxy]
disabled = 0
proxy-address =

[network]
host = localhost
port = 8089
