[ccx_rapid7_vulnerability_cve_lookup]
batch_index_query = 0
case_sensitive_match = 1
filename = ccx_rapid7_vulnerability_cve_lookup.csv

[ccx_rapid7_vulnerability_id_lookup]
batch_index_query = 0
case_sensitive_match = 1
filename = ccx_rapid7_vulnerability_id_lookup.csv
