[hdsi_win_bad_password]
search = source=*wineventlog:security Sub_Status=0xC000006A OR SubStatus=0xC000006A OR Result_Code=0x18 OR ResultCode=0x18 OR Error_Code=0xC000006A OR ErrorCode=0xC000006A OR Failure_Code=0x18 OR FailureCode=0x18
