
[forward_source]
DATETIME_CONFIG = 
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Custom
pulldown_type = 1

[remote]
DATETIME_CONFIG = 
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Custom
pulldown_type = 1

[commvaultlogs]
EXTRACT-ptid = ^(?P<processid>\d+)\s+(?P<threadid>[^ ]+)
EXTRACT-jid = ^(?:[^:\n]*:){2}\d+\s+(?P<jobid>\d+)
LOOKUP-cvexternlookup = cvexternlookup source AS source index AS index host AS host OUTPUT commserver AS commserver machine AS machine module AS module ostype AS ostype version AS version

[rdfg]
DATETIME_CONFIG = 
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Custom
pulldown_type = true
