#
# Splunk app configuration file
#

[ui]
is_visible = 1
label = dhcpd (posix)

[launcher]
author = araitz@splunk.com
description = Splunk for dhcpd helps you gain insight into your environment by building dhcp inventories, identifying new hosts, and visualizing trends and anomalies
version=1.3

[package]
id=dhcpd
