
[expose:TA_proofpoint_digital_risk_app_for_splunk_account]
pattern = TA_proofpoint_digital_risk_app_for_splunk_account
methods = POST, GET

[expose:TA_proofpoint_digital_risk_app_for_splunk_account_specified]
pattern = TA_proofpoint_digital_risk_app_for_splunk_account/*
methods = POST, GET, DELETE

[expose:TA_proofpoint_digital_risk_app_for_splunk_settings]
pattern = TA_proofpoint_digital_risk_app_for_splunk_settings
methods = POST, GET

[expose:TA_proofpoint_digital_risk_app_for_splunk_settings_specified]
pattern = TA_proofpoint_digital_risk_app_for_splunk_settings/*
methods = POST, GET, DELETE

[expose:TA_proofpoint_digital_risk_app_for_splunk_proofpoint_digital_risk_audit_input]
pattern = TA_proofpoint_digital_risk_app_for_splunk_proofpoint_digital_risk_audit_input
methods = POST, GET

[expose:TA_proofpoint_digital_risk_app_for_splunk_proofpoint_digital_risk_audit_input_specified]
pattern = TA_proofpoint_digital_risk_app_for_splunk_proofpoint_digital_risk_audit_input/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
