[protocol_lookup]
filename = protocols.csv
max_matches = 1
min_matches = 1
default_match = unknown

[port_lookup]
filename = services.csv
max_matches = 1
min_matches = 1
default_match = unknown

[sampling_lookup]
filename = sampling.csv
max_matches = 1
min_matches = 0

[ddos_indicators_lookup]
filename = ddos-indicators.csv
max_matches = 1
min_matches = 1
default_match = unknown

[SRCIP6Extraction]
REGEX = (?i) src_ip6=(?P<src_ip>[^ ]+)
WRITE_META = true
FORMAT = src_ip::$1

[DESTIP6Extraction]
REGEX = (?i) dest_ip6=(?P<dest_ip>[^ ]+)
WRITE_META = true
FORMAT = dest_ip::$1

[my_subnets_lookup]
filename = my-subnets.csv
max_matches = 1
min_matches = 1
default_match = external
match_type = CIDR(subnet)

[nfo_exp_lookup]
filename = nfo_exp.csv
max_matches = 1
min_matches = 1
default_match = unknown

[interfaces_20003_lookup]
filename = interfaces_20003.csv
max_matches = 1
min_matches = 1
default_match = unknown
