[source::...ta-gitlab-auditor*.log*]
sourcetype = tagitlabauditor:log

[source::...ta_gitlab_auditor*.log*]
sourcetype = tagitlabauditor:log

[gitlabapi]
MAX_TIMESTAMP_LOOKAHEAD = 300
SHOULD_LINEMERGE = 0
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%f
pulldown_type = 1

