
[admin:TA_gitlab_auditor]
match = /
members = TA_gitlab_auditor_settings, TA_gitlab_auditor_gitlabapi

[admin_external:TA_gitlab_auditor_settings]
handlertype = python
python.version = python3
handlerfile = TA_gitlab_auditor_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_gitlab_auditor_gitlabapi]
handlertype = python
python.version = python3
handlerfile = TA_gitlab_auditor_rh_gitlabapi.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
