[switch_properties]
Health_Interval = 60
Health_Log_File = /opt/splunk/etc/apps/lenovo_network_advisor/logs/lenovo_cnos_system_health.log

Traffic_Interval = 120
Traffic_Log_File = /opt/splunk/etc/apps/lenovo_network_advisor/logs/lenovo_cnos_traffic.log

Congestion_Interval = 60
Congestion_Log_File = /opt/splunk/etc/apps/lenovo_network_advisor/logs/lenovo_cnos_congestion.log

Buffutil_Interval = 60
Buffutil_Log_File = /opt/splunk/etc/apps/lenovo_network_advisor/logs/lenovo_cnos_bstreport.log
