[to]
TOKENIZER = (\w[\w\.\-]*@[\w\.\-]*)

[from]
TOKENIZER = (\w[\w\.\-]*@[\w\.\-]*)

[cc]
TOKENIZER = (\w[\w\.\-]*@[\w\.\-]*)

[rcpt_to]
TOKENIZER = (\w[\w\.\-]*@[\w\.\-]*)

[mail_from]
TOKENIZER = (\w[\w\.\-]*@[\w\.\-]*)
