[kitco_quotes]
start_by_shell = false
sourcetype = kitco:quotes
interval = 300
precious_metals = [u'GOLD', u'PLATINUM', u'PALLADIUM', u'RHODIUM', u'SILVER']
base_metals = [u'ALUMINUM', u'COPPER', u'NICKEL', u'LEAD', u'ZINC']
currencies = [u'BRL', u'AUD', u'CHF', u'CAD', u'CNY', u'EUR', u'HKD', u'GBP', u'INR', u'JPY', u'MXN', u'RUB', u'ZAR']
other = [u'OIL', u'DJIA', u'USDX', u'SP500', u'NYSE', u'NIKKEI', u'HUI', u'TSX', u'XAU']
disabled = 0

[kitco_quotes://test]
other = OIL~DJIA~USDX~SP500~NYSE~NIKKEI~HUI~TSX~XAU
precious_metals = GOLD~PLATINUM~PALLADIUM~RHODIUM~SILVER
base_metals = ALUMINUM~COPPER~NICKEL~LEAD~ZINC
currencies = BRL~AUD~CHF~CAD~CNY~EUR~HKD~GBP~INR~JPY~MXN~RUB~ZAR
interval = 60

