[default]

[install]
is_configured = 0
install_source_checksum = 73d502624c8dbd61da0789374c20dfb328d4e0d7

[launcher]
author = CloudFabrix Software Inc.
description = CFX Unified Network Observability App
version = 3.5.2

[ui]
is_visible = 1
label = CFX Unified Network Observability App


[id]
version = 3.5.2
name = cfxuno


[package]
version = 3.5.2
id = cfxuno
