[emailcsvs]
filename = emailcsvs.py
retainsevents = false
overrides_timeorder = true
run_in_preview = false
streaming = false
passauth = true
required_fields = to,csvs

[matchfieldfromcsv]
filename = match_field_from_csv.py
run_in_preview = true
retainsevents = true
streaming = true

