#[monitor://$SPLUNK_HOME/var/log/splunk/scm-framework.log]
#index = _internal
#sourcetype = scm_framework_log

[batch://$SPLUNK_HOME/var/spool/splunk/...stash_scm_signals/*.csv]
disabled = false
index=scm_signal
sourcetype = scm_signal
move_policy = sinkhole
crcSalt = <SOURCE>
