#  Please note, these configurations are protoyped and open for change by the end user

input {
  exec {
    command => "/usr/bin/bv-splunk-metrics --hostname ${HOSTNAME} performance ${SPLUNKFREQ}"
    interval => "${SPLUNKFREQ}"
    tags => ["health"]
  }
  exec {
    command => "/usr/bin/bv-splunk-metrics --hostname ${HOSTNAME} health"
    interval => "${SPLUNKFREQ}"
    tags => ["health"]
  }
  file {
    path => "/opt/var/metrics/content_hourly.log"
    path => "/opt/var/metrics/events_hourly.log"
    path => "/opt/var/metrics/status_changes.log"
    sincedb_path => "/opt/bvintegration/logstash/.sincedb_metrics"
    tags => ["health"]
  }
}

filter {
  if "health" in [tags] {
    if [path] {
      date {
        match => [ "timestamp", "yyyy-MM-dd HH:mm:ss.SSSSSS" ]
        timezone => "UTC"
      }
      mutate { gsub => [ "message", "= ", "=null", "message", "(\S+=)", "; \1"] }
      kv { 
        field_split_pattern => ";"
        remove_char_key => "\s"
        trim_value => "\s"
      }
      mutate { 
        add_field => { "hostname" => "${HOSTNAME}" }
        remove_field => [ "message", "host" ] 
        gsub => [ "flags", "u'", "'", "flags", "[\[\]' ]", "" ]
        split => [ "flags", "," ]
        convert => {
          "bv_event_type" => "integer"
          "count" => "integer"
          "filesize" => "integer"
        }
      }
    }
  }  
  if [path] =~ "content_hourly.log" {
    mutate { add_field => { "type" => "content_hourly" } }
  }

  if [path] =~ "events_hourly.log" {
    mutate { add_field => { "type" => "events_hourly" } }
  }

  if [path] =~ "status_changes.log" {
    mutate { add_field => { "type" => "status_changes" } }
  }
}

output {
if "health" in [tags]{
    if [path] {
      tcp {
        host => "${SPLUNKHOST}"
        port => "${SPLUNKPORT}"
        codec => "json_lines"
      }
    } else {
      tcp {
        host => "${SPLUNKHOST}"
        port => "${SPLUNKPORT}"
        codec => plain { format => "%{message}" }
      }
    }
  }
}
