[macos_screen_unlocked]
search = eventtype=macos_event com.apple.sessionagent.screenIsUnlocked logd_processImagePath="*loginwindow" user_id=*

[macos_authentication_ssh]
search = eventtype=macos_event pam logd_processImagePath="/usr/sbin/sshd"

[macos_change_users]
search = eventtype=macos_event logd_subsystem="com.apple.loginwindow.logging" LWAccountTracking User added handleUserListChangeNotification was

[macos_application_launched]
search = eventtype=macos_event logd_subsystem="com.apple.launchservices" NotifyAboutLaunchedApplication

[macos_change_password]
search = eventtype=macos_event logd_subsystem="com.apple.opendirectoryd" sourcetype=logd "Password changed"

[macos_event]
search = index=macos sourcetype=logd

[macos_authentication_biometric_success]
search = eventtype=macos_event "BKMatchOperation::matchResult:withDictionary" userID

[macos_authentication_user_logged_in]
search = eventtype=macos_event logd_processImagePath="*/apsd" "Changing status for uid" "from logged out to logged in"

[macos_sandbox_deny]
search = (eventtype=macos_event (Sandbox OR "System Policy") sandbox_action=deny)

[macos_authentication_local_failed]
search = (eventtype=macos_event "Failed to authenticate user" logd_subsystem="com.apple.Authorization")

[macos_authentication_kerberos_failed]
search = (eventtype=macos_event "Failed kerberos password verification" logd_subsystem="com.apple.opendirectoryd")

[macos_authentication_kerberos_success]
search = (eventtype=macos_event "Successful kerberos password verification" logd_subsystem="com.apple.opendirectoryd")

[macos_sudo_command]
search = (eventtype=macos_event COMMAND TTY USER)

