#
# ################################################################################
#
#  Copyright (C) 2018 Splunk Inc.
#
#  You should have received a copy of the Splunk Software Licese agreement
#  along with TA-Siebel_Server.  If not, see:
#  <http://www.splunk.com/en_us/legal/splunk-software-license-agreement.html>
#
# #################################################################################
#
#

[event_type_alias]
INDEXED=true
[event_subtype]
INDEXED=true
[severity]
INDEXED=true
[saramid]
INDEXED=true
