#
# ################################################################################
#
#  Copyright (C) 2018 Splunk Inc.
#
#  You should have received a copy of the Splunk Software Licese agreement
#  along with TA-Siebel_Server.  If not, see:
#  <http://www.splunk.com/en_us/legal/splunk-software-license-agreement.html>
#
# #################################################################################
#

[ta_siebel_server_header]
REGEX = ^([^\s]+)\s(.+?(?=\s\d\s))\s(\d)\s([^\s])\s\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\s
WRITE_META = true
FORMAT = event_type_alias::"$1" event_subtype::"$2" severity::"$3" saramid::"$4"

[ta_siebel_server_source]
DEST_KEY = MetaData:Source
REGEX = ^([^\s]+)\s(.+?(?=\s\d\s))\s
FORMAT = source::$1:$2

[ta_siebel_server_raw]
REGEX = ^[^\s]+\s.+?(?=\s\d\s)\s\d\s[^\s]+\s\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\s(.*)
FORMAT = $1
DEST_KEY = _raw
