# #::HDR:: ;; # App: google_workspace_for_splunk ;; # File: alert_actions.conf ;; # Updated: 2025-09-17 17:46:28

[googleworkspace-pubsub]
disabled       = 0
python.version = python3.9
is_custom      = 1
icon_path      = appIcon_2x.png
payload_format = json
command        = sendalert $action_name$ results_file="$results.file$" results_link="$results.url" param.action_name=$action_name$ | stats count
label          = GCP Pub Sub Alert Action
description    = GCP Pub Sub Alert Action
param._cam     = {"category":["Information Conveyance"],"task":["create"],"subject":["site"],"technology":[{"vendor":"google_workspace_for_splunk","product":"google_workspace_for_splunk"}],"supports_adhoc":true}

[googleworkspace-vault-matter]
disabled       = 1
python.version = python3.9
is_custom      = 1
icon_path      = appIcon_2x.png
payload_format = json
command        = sendalert $action_name$ results_file="$results.file$" results_link="$results.url" param.action_name=$action_name$ | stats count
label          = Google Vault Matter Alert Action
description    = Google Vault Matter Alert Action
param._cam     = {"category":["Information Integrity"],"task":["create,modify,update,delete"],"subject":["site"],"technology":[{"vendor":"google_workspace_for_splunk","product":"google_workspace_for_splunk"}],"supports_adhoc":true}

[googleworkspace-write-big-query]
disabled               = 0
python.version         = python3.9
is_custom              = 1
icon_path              = appIcon_2x.png
payload_format         = json
command                = sendalert $action_name$ results_file="$results.file$" results_link="$results.url" param.action_name=$action_name$ | stats count
label                  = GCP BigQuery Write Table Action
description            = GCP BigQuery Write Table Action
adaptive_results_spl   = eventtype=google_workspace sourcetype=googleworkspace:alert_action:
param._cam             = {"category":["Information Conveyance"],"task":["create"],"subject":["site"],"technology":[{"vendor":"google_workspace_for_splunk","product":"google_workspace_for_splunk"}],"supports_adhoc":true}
param.project_id       = 
param.dataset_id       = 
param.table_id         = 
param.write_preference = WRITE_EMPTY
param.credential       = 

[googleworkspace-alert-action-gmail-send]
disabled            = 0
python.version      = python3
is_custom           = 1
icon_path           = appIcon_2x.png
payload_format      = json
command             = sendalert $action_name$ results_file="$results.file$" results_link="$results.url" param.action_name=$action_name$ | stats count
label               = Google Send Email Alert Action
description         = Send an email with Google!
param._cam          = {"category":["Utility"],"task":["create,modify,update,delete"],"subject":["site"],"technology":[{"vendor":"google_workspace_for_splunk","product":"google_workspace_for_splunk"}],"supports_adhoc":true}
param.recipients    = 
param.subject       = 
param.one_email     = NO
param.credential    = 
param.cc            = 
param.bcc           = 
param.body_template = 
param.use_google    = Yes
param.sender        = 