#
# Splunk app KV Store collection file
#

[kpi_search_collection]
field.ts = number
accelerated_fields.timestamp = {"ts": 1}

[request_search_collection]
field.ts = number
field.errors = number
field.requests = number
field.traffic = number
accelerated_fields.timestamp = {"ts": 1}

[edge_search_collection]
