[initial_stage_tk]
external_type = kvstore
collection = initial_stage_lookup
fields_list = detection_name , request_type, query, severity, detection_solution, stage,description, security_domain, action, alert_status, MITRE, days, modificationtype, modifiedcontent, reason, updatetime, assigned_to , id,updatedby ,comment



[approval_stage_trackuc]
external_type = kvstore
collection = approval_stage_lookup_trackuc
fields_list = detection_name , request_type, query, severity, detection_solution, stage,description, security_domain, action, alert_status, MITRE, days, modificationtype, modifiedcontent, reason, updatetime, assigned_to , id,updatedby ,comment, isapproved