[flashpoint_iocs]
enforceTypes = true
field.fpid = string
field.value = string
field.type = string
field.hashes_md5 = string
field.hashes_sha1 = string
field.hashes_sha256 = string
replicate = true

[flashpoint_hunts]
enforceTypes = true
field.name = string
field.value = string
field.description = string
replicate = true

[flashpoint_hunt_runs]
enforceTypes = true
field.hunt_id = string
field.status = string
field.created_at = string
field.updated_at = string
field.status_message = string
replicate = true

[checkpoints]
enforceTypes = true
field.checkpoint = string
replicate = true
