[searchByFilters(2)]
args = ip_token, user_token
definition = eval User=if (User == "", "N/A", User)\
             | search DstIp=$ip_token$ OR SrcIp=$ip_token$\
             | search User=$user_token$\
