#
# Splunk app configuration file
#

[id]
version = 1.2.1
name = securelink

[install]
is_configured = 0
build = 2
state_change_requires_restart = true
state = enabled

[ui]
is_visible = 1
label = SecureLink

[launcher]
author = TekStream Solutions
description = Visualizations and User Objects associated with SecureLink syslog data
version = 1.2.1

[package]
id = securelink
check_for_updates = true
