[cc_priv_users]
batch_index_query = 0
case_sensitive_match = 1
filename = cc_priv_users.csv

[cc_controls_lookup]
batch_index_query = 0
case_sensitive_match = 1
filename = cc_controls_lookup.csv

[cc_splunk_data_controls]
batch_index_query = 0
case_sensitive_match = 0
filename = cc_splunk_data_controls.csv
match_type = WILDCARD(index), WILDCARD(host), WILDCARD(sourcetype)
max_matches = 1

#####################
## Vulnerablity
#####################
[cc_vulnerability_tracker]
collection    = cc_vulnerability_tracker
external_type = kvstore
fields_list   = _key,firstTime,lastTime,signature,dest

####
## Simple User Tracker
####
[cc_user_tracker]
collection = cc_user_tracker
external_type = kvstore
fields_list = _key,firstTime,lastTime,user,is_privileged

[cc_allowed_ports]
batch_index_query = 0
case_sensitive_match = 0
default_match = false
filename = cc_allowed_ports.csv
match_type = WILDCARD(dvc)
min_matches = 1

[cc_allowed_processes]
batch_index_query = 0
case_sensitive_match = 0
default_match = false
filename = cc_allowed_processes.csv
match_type = WILDCARD(dest)
min_matches = 1
