
[expose:TA_AlibabaCloudSLS_account]
pattern = TA_AlibabaCloudSLS_account
methods = POST, GET

[expose:TA_AlibabaCloudSLS_account_specified]
pattern = TA_AlibabaCloudSLS_account/*
methods = POST, GET, DELETE

[expose:TA_AlibabaCloudSLS_settings]
pattern = TA_AlibabaCloudSLS_settings
methods = POST, GET

[expose:TA_AlibabaCloudSLS_settings_specified]
pattern = TA_AlibabaCloudSLS_settings/*
methods = POST, GET, DELETE

[expose:TA_AlibabaCloudSLS_sls_datainput]
pattern = TA_AlibabaCloudSLS_sls_datainput
methods = POST, GET

[expose:TA_AlibabaCloudSLS_sls_datainput_specified]
pattern = TA_AlibabaCloudSLS_sls_datainput/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
