[parse_ansible_results_queue://<name>]
queue_handler = Select which host that will handle events generated by this server

[parse_ansible_collection_queue://<name>]
batch_size = How many events to send to ansible pr collection interval
queue_handler = Select which host that will handle events generated by this server