#
# Splunk app configuration file
#

[install]
is_configured = 0
install_source_checksum = c12e6c9f4432d55d4d35a1290823a879bf869f9e


[ui]
is_visible = 1
label = SplunkStart app for Splunk
setup_view = app_setup

[launcher]
author = Nimish Doshi
description = This is used to jump start using Splunk with your own data with ready made reports and dashboards.
version = 1.4.0

[package]
id = SplunkStart

