[launcher]
version = 2.1.15
description = Mailchimp Add-On for Splunk

[id]
version = 2.1.15
name = TA-mailchimp-add-on-for-splunk

[install]
build = 1773770025
is_configured = false
state = enabled

[package]
id = TA-mailchimp-add-on-for-splunk
check_for_updates = true

[ui]
label = Mailchimp Add-On for Splunk
is_visible = true

[triggers]
reload.ta_mailchimp_add_on_for_splunk_settings = simple
reload.ta_mailchimp_add_on_for_splunk_account = simple
