[unifi]

category = Network & Security
description = UniFi Network Device Logs
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TIME_FORMAT = %b %d %H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 15

TRANSFORMS-unifi_fields = unifi_ip_device_extraction

# search-time extractions
EXTRACT-unifi_backup = (?:[^ ]+ ){3}(?P<IP>(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|(?![0-9])[^ ]*) (?:[^ ]+ ){3}(?P<Device>[^ ]+)(?:.*\](?P<Message> (?!.*=).+))?
