[cyphort:incident]
KV_MODE = json
SHOULD_LINEMERGE = false
TIME_PREFIX = timestamp
MAX_TIMESTAMP_LOOKAHEAD = 33
TIME_FORMAT = %Y-%m-%d %H:%M:%S%6N%z
TZ = UTC
FIELDALIAS-id = incident_id AS id
FIELDALIAS-dvc = collector_name AS dvc
FIELDALIAS-dest_ip = endpoint_ip AS dest_ip
FIELDALIAS-dest_name = endpoint_name AS dest_name
FIELDALIAS-dest = endpoint_name AS dest
FIELDALIAS-category = incident_category AS category
FIELDALIAS-signature = incident_name AS signature
FIELDALIAS-severity_id = incident_severity AS severity_id
FIELDALIAS-src_ip = source_ip AS src_ip
FIELDALIAS-src_name = source_name AS src_name
FIELDALIAS-src = source_name AS src
FIELDALIAS-event_src = host AS event_src
EVAL-vendor_product = "Cyphort"
EVAL-incident_key = incident_id . "::" . host
EVAL-severity = case(incident_severity=0.0,"Benign",incident_severity>0.0 AND incident_severity<0.5,"Low",incident_severity>=0.5 AND incident_severity<0.75,"Medium",incident_severity>=0.75 AND incident_severity<1.0,"High",incident_severity=1.0,"Max")
EVAL-risk_desc = case(incident_risk=0.0,"Benign",incident_risk>0.0 AND incident_risk<0.5,"Low",incident_risk>=0.5 AND incident_risk<0.75,"Medium",incident_risk>=0.75 AND incident_risk<1.0,"High",incident_risk=1.0,"Max")
EVAL-asset_value = case(endpoint_value<0.5,"Low",endpoint_value>=0.5 AND endpoint_value<0.75,"Medium",endpoint_value>=0.75 AND endpoint_value<1.0,"High",endpoint_value=1.0,"Max")
EVAL-relevance = case(incident_relevance<0.5,"Low",incident_relevance>=0.5 AND incident_relevance<0.75,"Medium",incident_relevance>=0.75 AND incident_relevance<1.0,"High",incident_relevance=1.0,"Max")

[cyphort:api]
KV_MODE = json

[CyphortForSplunk:error]
REPORT-error = cyphort_error

[cyphort:event]
KV_MODE = json
SHOULD_LINEMERGE = false
TIME_PREFIX = last_activity_time
MAX_TIMESTAMP_LOOKAHEAD = 50
FIELDALIAS-dvc = collector_name AS dvc
FIELDALIAS-dest_ip = endpoint_ip AS dest_ip
FIELDALIAS-dest_name = endpoint_name AS dest_name
FIELDALIAS-severity_id = event_detail.event__severity AS severity_id
FIELDALIAS-src_ip = source_ip AS src_ip
FIELDALIAS-src_name = event_detail.source_name AS src_name
EVAL-vendor_product = "Cyphort"