# Configuration spec for splunk_create.conf
# This file is auto-generated by @splunk/create and should not be manually edited

[base]
splunk_create_version = <string>
* Version of @splunk/create used to generate the app
* Auto-generated, do not edit

splunk_create_type = <string>
* Type of Splunk app created (e.g., ReactSplunkApp)
* Auto-generated, do not edit
