[eventtype=http]
proxy = enabled
storage = enabled
web = enabled

[eventtype=dns]
dns = enabled
network = enabled
resolution = enabled

[eventtype=dhcp]
certificate = enabled
dns = enabled
network = enabled
resolution = enabled
ssl = enabled

[eventtype=ssl]
certificate = enabled
communicate = enabled
network = enabled
ssl = enabled

[eventtype=tcp]
communicate = enabled
network = enabled
