[single_mode_indicator_search(3)]
args = operation,field,entity
definition = stats $operation$($field$) by $entity$
iseval = 0


[single_mode_indicator_search(4)]
args = operation,field,entity,timespan
definition = stats $operation$($field$) by $entity$
iseval = 0

[timechart_mode_indicator_search(4)]
args = operation,field,entity,timespan
definition = bin _time span=$timespan$ | stats $operation$($field$) by $entity$,_time
iseval = 0

[indicator_index]
iseval = 0

[scoring_index]
iseval = 0
