[package]
id = Cisco_WSA_Insight
check_for_updates = 1

[install]
state = enabled
build  = 11

[ui]
is_visible = 1
label = Cisco WSA Insight

[id]
version = 0.0.11
name = Cisco_WSA_Insight

[launcher]
author = Pavel Prostin
description = Cisco WSA Insight
version = 0.0.11

