[ucmdb]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-micro-focus-ucmdb-ci-witness*.log*]
sourcetype = tamicrofocusucmdbciwitness:log

[source::...ta_micro_focus_ucmdb_ci_witness*.log*]
sourcetype = tamicrofocusucmdbciwitness:log

