[appdynamics_status]
python.version = python3
sourcetype = appdynamics_status

[appdynamics_analytics_api]
python.version = python3
sourcetype = appdynamics_analytics

[appdynamics_security]
python.version = python3
sourcetype = appdynamics_security

[appdynamics_events_policy]
python.version = python3
sourcetype = appdynamics_events

[appdynamics_custom_metrics]
python.version = python3
sourcetype = appdynamics_custom_metrics

[appdynamics_database_metrics]
python.version = python3
sourcetype = appdynamics_databases

[appdynamics_hardware_metrics]
python.version = python3
sourcetype = appdynamics_hardware

[appdynamics_application_snapshots]
python.version = python3
sourcetype = appdynamics_snapshots

[appdynamics_audit]
python.version = python3
sourcetype = appdynamics_audit

[appdynamics_licenses]
python.version = python3
sourcetype = appdynamics_licenses