[admin:TA_clumio_audit_logs_ingester]
match = /
members = TA_clumio_audit_logs_ingester_settings, TA_clumio_audit_logs_ingester_clumio_audit_logs_input

[admin_external:TA_clumio_audit_logs_ingester_settings]
handlertype = python
handlerfile = TA_clumio_audit_logs_ingester_rh_settings.py
handleractions = edit, list
python.version = python3

[admin_external:TA_clumio_audit_logs_ingester_clumio_audit_logs_input]
handlertype = python
handlerfile = TA_clumio_audit_logs_ingester_rh_clumio_audit_logs_input.py
handleractions = edit, list, remove, create
python.version = python3

