[GTI Clean Lookups]
cron_schedule = 0,30 * * * *
description = Retire IoCs older than the expiration setting value every 30 minutes
display.general.type = statistics
display.page.search.tab = statistics
request.ui_dispatch_view = search
search = | makeresults | gtideleteiocs ttl=`gti_ttl`
enableSched = true

[GTI Keep Adversary Lookups Updated]
cron_schedule = 7,37 * * * *
description = Update Adversary lookup tables (campaigns, threat actors, ...) every 30 minutes
display.general.type = statistics
display.page.search.tab = statistics
request.ui_dispatch_view = search
search = | localop | gtiadversaryupdate
enableSched = true

[GTI Keep MITRE Lookup Updated]
cron_schedule = 7,37 * * * *
description = Update MITRE lookup table every 30 minutes
display.general.type = statistics
display.page.search.tab = statistics
request.ui_dispatch_view = search
search = | localop | gtimitreupdate
enableSched = true
