[azure_assets_coll]
field.bunit = string
field.category = string
field.dns = string
field.external_ip = string
field.ip = string
field.location = string
field.mac = string
field.nt_host = string
field.operatingSystem = string
field.operatingSystemVersion = string
field.priority = string
field.resource_group = string