#####################################################
#
# Splunk_TA_contentkeeper_Enosys 
#
# Enosys Solutions
#
#####################################################

[install]
is_configured = false
state = enabled

[ui]
is_visible = true
label = Enosys Add-on for ContentKeeper

[launcher]
author = Enosys Solutions
description = Splunk Add-on to assist ContentKepper and ContentKeeperweb syslog log ingestion into Splunk
version = 2.0.2

[package]
id = Splunk_TA_contentkeeper_Enosys
check_for_updates = true