###
#
# XD5 Extractions for the Desktop Delivery Controller
#
#####


[xd5sessions]
REGEX = (\S+)\=\"\s([^\"]+|\S+)\s\"
FORMAT = $1::$2
MV_ADD=true

[getVMname]
REGEX= \s+MachineName\=[^\\]+\\(\S+)\"\s+
FORMAT=vm_name::$1


[getVMname2]
REGEX= \s+vm_hostname\=\s[^\\]+\\(\S+)\"\s+
FORMAT=vm_name::$1

[getDesktopName]
REGEX = DesktopName=\"\S+\\([^"]+)
FORMAT = vm_name::$1


[getVMnameICA]
REGEX = \s+__SERVER\=\"(\S+)\"\s+
FORMAT = vm_name::$1



[getSessionStateChangeTime]
REGEX = StartTime=\"([^"]+)
FORMAT = SessionStateChangeTime::$1

[getSessionBrokeringTime]
REGEX = StartTime=\"([^"]+)
FORMAT = BrokeringTime::$1

[getUserSID]
REGEX = UserName=\"([^"]+)
FORMAT = UserSID::$1

[getClientAddress]
REGEX = LaunchedViaIP=\"([^"]+)
FORMAT = ClientAddress::$1

[getHardwareID]
REGEX = DeviceId=\"([^"]+)
FORMAT = HardwareId::$1

##
#
# Perfmon and WinEvent Field Extractor
#
####

[perfmon_extract]
REGEX =  ([^=]+)\="?([^"^\n]+)"?
FORMAT = $1::$2
MV_ADD=true

[process_name]
REGEX = instance="?([^#^"^\n]+)"?
FORMAT = process_name::$1

[getProcess]
REGEX = Path=.*\\(\S+[^\"^\.]+)\."?
FORMAT = process_name::$1

#[get_apps]
#REGEX =(.{26})(.{26})([^\n].*)
#FORMAT = application_name::$1 application_version::$2 application_vendor::$3

##
#
# XD5 User, VMName, Farm and Desktop Group Lookups
#
####

##LOOKUPS

[ica_devicetype]
filename = ica_devicetype.csv

[citrix_license_type]
filename = citrix_license_type.csv

[citrix_license_product]
filename = citrix_license_product.csv

[xd5_usrexp]
filename = xd5_usrexp.csv 

[xd5_desktops]
filename = xd5_desktops.csv
case_sensitive_match = false

[process_table]
filename = process_table.csv
case_sensitive_match = false