[WA - first 20 alerts]
action.email.sendresults = 0
cron_schedule = No value selected
dispatch.earliest_time = -7d@h
dispatch.latest_time = +0s
displayview = search
request.ui_dispatch_view = search
search = sourcetype="weather_alerts_entry"|head 20
vsid = g9x8bsd0

[WA - stats values of phenomena]
action.email.sendresults = 0
cron_schedule = No value selected
dispatch.earliest_time = -7d@h
dispatch.latest_time = +0s
displayview = search
request.ui_dispatch_view = search
search = sourcetype="weather_alerts_entry"|xmlkv|stats values(phenomena) by Place
vsid = g9x7l64t

[WA - stats values significance by Location]
action.email.sendresults = 0
cron_schedule = No value selected
dispatch.earliest_time = -7d@h
dispatch.latest_time = +0s
displayview = search
request.ui_dispatch_view = search
search = sourcetype="weather_alerts_entry"|xmlkv|lookup findLocation Place|stats values(significance) as Significance by Location
vsid = g9x88p8t

[WA - timechart count by type]
action.email.sendresults = 0
cron_schedule = No value selected
dispatch.earliest_time = -7d@h
dispatch.latest_time = +0s
displayview = charting
request.ui_dispatch_view = charting
search = sourcetype="weather_alerts_entry"|xmlkv|timechart count(_raw) by type
vsid = g9x76q3o

[WA - Top Descriptions]
action.email.sendresults = 0
cron_schedule = No value selected
dispatch.earliest_time = -7d@h
dispatch.latest_time = +0s
displayview = charting
request.ui_dispatch_view = charting
search = sourcetype="weather_alerts_entry"|xmlkv|top description
vsid = g9x7a3ii

[WA - stats list message by Place]
cron_schedule = No value selected
dispatch.earliest_time = -7d@h
dispatch.latest_time = +0s
displayview = search
request.ui_dispatch_view = search
search = sourcetype="weather_alerts_entry"|xmlkv|stats first(message) by Place
vsid = g9x7nudm

[WA - Scheduled Search by Zip Code]
action.email = 1
action.email.sendresults = 1
action.email.to = youremail@yourdomain.com
counttype = number of events
cron_schedule = 0 * * * *
dispatch.earliest_time = -60m@m
dispatch.latest_time = +0s
displayview = search
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_view = search
search = sourcetype=weather_alerts_entry Place="10001"
vsid = g9x8n9fk

[WA - Spreadsheet of Types by Location]
action.email.inline = 1
action.email.reportServerEnabled = 0
alert.suppress = 0
alert.suppress.period = h
alert.track = 1
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
displayview = search
request.ui_dispatch_view = search
search = sourcetype="weather_alerts_entry" | xmlkv | lookup findLocation Place|dedup epoch|stats count(type) as total_type by Location, type |xyseries Location type total_type|eval t=1|addcoltotals|sort t desc|eval Location = if(t>1,"Totals",Location)| fields - t | fillnull value=0 FIR WAT FLO HEA SPE| table Location *
vsid = gpeu2jei

