[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 9

[launcher]
author = Code42 Software
version = 2.0.8
description = "Code42's Splunk app that collects and visualizes data from Incydr."

[ui]
is_visible = 1
label = Code42 Insider Risk Add-On
docs_section_override = AddOns:released

[package]
id = TA-code42-insider-threats-add-on

[triggers]
reload.ta_code42_insider_threats_add_on_account = simple
reload.ta_code42_insider_threats_add_on_settings = simple
reload.passwords = simple

