[default]
[cisco_cybervision_index]
definition = index!=_*
iseval = 0

[deduplicate_device_fields]
definition = id,host
iseval = 0

[get_common_protocols]
definition = "ARP", "ICMP", "NETBIOS", "broadcast", "ping", "DNS", "NTP"
iseval = 0

