
[launcher]
version = 10.1.0
description = DEMO for robotron IPEA
author = Robotron Datenbank-Software GmbH

[package]
id = RDS_IPEA_DEMO
check_for_updates = 1

[install]
build = 100100
is_configured = false
install_source_checksum = 2117ac59eae5f4f61e254a8b1ed24598a36ef4be

[ui]
is_visible = 1
label = Robotron Industrial Process and Energy Analytics (IPEA) DEMO

