[eventtype=ftnt_fwbcld_attack]
malware = enabled
attack = enabled

[eventtype=ftnt_fwbcld_event]
change = enabled
endpoint = enabled

[eventtype=ftnt_fwbcld_traffic]
change = enabled
endpoint = enabled