
[expose:ta_proxmox_add_on_for_splunk_account]
pattern = ta_proxmox_add_on_for_splunk_account
methods = POST, GET

[expose:ta_proxmox_add_on_for_splunk_account_specified]
pattern = ta_proxmox_add_on_for_splunk_account/*
methods = POST, GET, DELETE

[expose:ta_proxmox_add_on_for_splunk_settings]
pattern = ta_proxmox_add_on_for_splunk_settings
methods = POST, GET

[expose:ta_proxmox_add_on_for_splunk_settings_specified]
pattern = ta_proxmox_add_on_for_splunk_settings/*
methods = POST, GET, DELETE

[expose:ta_proxmox_add_on_for_splunk_proxmox_resources]
pattern = ta_proxmox_add_on_for_splunk_proxmox_resources
methods = POST, GET

[expose:ta_proxmox_add_on_for_splunk_proxmox_resources_specified]
pattern = ta_proxmox_add_on_for_splunk_proxmox_resources/*
methods = POST, GET, DELETE

[expose:ta_proxmox_add_on_for_splunk_proxmox_cluster_log]
pattern = ta_proxmox_add_on_for_splunk_proxmox_cluster_log
methods = POST, GET

[expose:ta_proxmox_add_on_for_splunk_proxmox_cluster_log_specified]
pattern = ta_proxmox_add_on_for_splunk_proxmox_cluster_log/*
methods = POST, GET, DELETE

[expose:ta_proxmox_add_on_for_splunk_proxmox_tasks]
pattern = ta_proxmox_add_on_for_splunk_proxmox_tasks
methods = POST, GET

[expose:ta_proxmox_add_on_for_splunk_proxmox_tasks_specified]
pattern = ta_proxmox_add_on_for_splunk_proxmox_tasks/*
methods = POST, GET, DELETE
