# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 1
install_source_checksum = b9f62170a0f5bb03ba8302368693b30c36e5cba4

[launcher]
author = Martin Ohl
version = 1.0.0
description = The MVISION EDR Detections app provides the ability to pull newest threat detections from the MVISION EDR Monitoring Dashboard on a scheduled basis. This data includes details about the threat, MITRE techniques and system detections.

[ui]
is_visible = 1
label = Trellix EDR Detections
docs_section_override = AddOns:released

[package]
id = TA-trellix-edr-detections

[triggers]
reload.addon_builder = simple
reload.ta_trellix_edr_detections_account = simple
reload.ta_trellix_edr_detections_settings = simple
reload.passwords = simple

