#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 1
label = Hitachi VSP One Object App for Splunk

[launcher]
author = Karthik Raja Balasubramanian and Raghavi Manga
description = Hitachi VSP One Object App for Splunk, designed for use with Splunk Enterprise, works alongside the Hitachi VSP One Object Add-on to provide comprehensive visibility into operational and performance metrics. It offers insights into key areas such as S3 activity, ingest performance, system health, and HTTP/2 and HTTP/3 protocol behavior.
version = 1.0.0

[package]
id = Hitachi_App_VSP1O
