#
# Splunk app configuration file
#

[ui]
is_visible = 0
label = TA-NutanixApp

[launcher]
author = Nutanix Inc
description = Nutanix Prism App for Splunk.
version = 1.6.0

[package]
check_for_updates = 1
id = TA-NutanixApp

[install]
state = enabled
install_source_checksum = 1b2a38c87860abeac5aff526acc8bbf4c3feef58
