@Library("jenkins-libraries-v2@master")
import com.qualys.pipeline.*


def templateName = "generic-binaries-template"
def branch = "master"
def nodeLabel = "slave"

pipeline = loadPipelineTemplate(templateName, branch, nodeLabel)
pipeline.runPipeline("properties.yaml", nodeLabel)

