# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 3

[launcher]
author = Luke Monahan <luke.monahan@tesserent.com>
version = 2.1.0
description = Collects threat intelligence feeds published by AusCERT. These feeds can be loaded into the ES threat intelligence collections by enabling the included saved search.

[ui]
is_visible = 1
label = Add-on for AusCERT
docs_section_override = AddOns:released

[package]
id = TA-auscert

[triggers]
reload.addon_builder = simple
reload.ta_auscert_account = simple
reload.ta_auscert_settings = simple
reload.passwords = simple

