[cilium:hubble:flow]
LINE_BREAKER=([\r\n]+)
# Singleligne Log
SHOULD_LINEMERGE=false
# Field is    .., time: 2024-05-05T10:27:08.798661782Z 
TIME_PREFIX=\"time\":\"
# Example: time: 2024-05-05T10:27:08.798661782Z 
TIME_FORMAT=%Y-%m-%dT%H:%M:%SZ
# From documentation when taking StartUTC
TZ=UTC
# Json extract at search time
KV_MODE=json

# Cilium flow related fields
FIELDALIAS-flow = "flow.Type" ASNEW app "flow.IP.source" ASNEW src_ip "flow.IP.destination" ASNEW dest_ip "flow.ethernet.destination" ASNEW dest_mac "flow.ethernet.source" ASNEW src_mac "flow.l4.TCP.destination_port" ASNEW dest_port "flow.l4.TCP.source_port" ASNEW src_port 
# K8s flow related fields
FIELDALIAS-k8s = "flow.source.namespace" ASNEW src_zone "flow.destination.namespace" ASNEW dest_zone "flow.IP.source" ASNEW source "flow.IP.destination" ASNEW dest_ip 

# TODO
# flow.Summary ASNEW tcp_flag The TCP flag(s) specified in the event. prescribed values: SYN, ACK, FIN, RST, URG, or PSH. 
# transport The OSI layer 4 (transport) or internet layer protocol of the traffic observed, in lower case. prescribed values: icmp, tcp, udp
# Could be improved with DNS, HTTP parsing
# EVAL-app = if(flow.Type == "L3_L4", "L3_L4","L7") 
EVAL-vendor_product = "Cilium"
EVAL-action = if('flow.verdict' == "DROPPED", "blocked","allowed")


