[nav_discover]
filename = nav_discover.csv

[suggested_reports]
filename = suggested_reports.csv


[suggested_2d_reports]
filename = suggested_2d_reports.csv


[discover_fields_status]
filename = discover_fields_status.csv

[discover_eventtypes_status]
filename = discover_eventtypes_status.csv

[discover_reports_status]
filename = discover_reports_status.csv


[tune_eventtypes_status]
filename = tune_eventtypes_status.csv

[tune_eventtypes_ignored]
filename = tune_eventtypes_ignored.csv

[discover_fields_ignored]
filename = discover_fields_ignored.csv



