#
# Splunk app configuration file
#

[ui]
is_visible = 1
label = WikiApp

[launcher]
author = Roger Strom
description = What really goes down on wikipedia? This app will read all the recent changes so you can keep an eye on hot articles, suspicious users and more.
version = 1.0

[package]
id = WikiApp
