[mc_adm]
definition = index="omega_ca_nt"  AUDIT_TYPE="Administrative" \
| table \
_time,\
ACTION_CMD,\
ACTION_ID,\
ACTION_NAME,\
ADMIN_PRIV,\
AUDIT_TYPE,\
CLIENT_ADDRESS,\
DB_HOST,\
DB_NAME,\
DBID,\
IP_ADDRESS,\
NET_PORT,\
NET_PROTOCOL,\
NT_EVENT_ID,\
NT_MESSAGE,\
NT_RECORD_NO,\
NT_TYPE,\
OS_USER,\
RETURNCODE,\
SESSIONID,\
TERMINAL,\
TIMESTAMP_STS,\
USERHOST,\
USERNAME
iseval = 0

[mc_std]
definition = index="omega_ca_nt"  AUDIT_TYPE="Standard" \
| table \
_time,\
ACTION_ID,\
ACTION_NAME,\
AUDIT_OPTION,\
AUDIT_TYPE,\
COMMENT_TEXT,\
CURRENT_USER,\
DB_HOST,\
DB_NAME,\
DBID,\
ENTRYID,\
GRANTEE,\
IP_ADDRESS,\
LOGOFF_DEAD,\
LOGOFF_LREAD,\
LOGOFF_LWRITE,\
LOGOFF_PREAD,\
NET_PORT,\
NET_PROTOCOL,\
NT_EVENT_ID,\
NT_MESSAGE,\
NT_RECORD_NO,\
NT_TYPE,\
OBJ_PRIVILEGE,\
OBJECT_NAME,\
OBJECT_OWNER,\
OS_USER,\
PRIVILEGE_ID,\
RETURNCODE,\
SESSION_CPU,\
SESSIONID,\
STATEMENTID, \
SYS_OPTIONS,\
SYS_PRIVILEGE,\
SYSTEM_PRIVILEGE,\
TERMINAL,\
TIMESTAMP_STS,\
USERHOST,\
USERNAME\

iseval = 0

[mc_smr]
definition = index="omega_ca_nt" \
| table \
_time, \
ACTION_NAME, \
ADMIN_PRIV, \
AUDIT_TYPE, \
DB_HOST, \
DB_NAME, \
NT_TYPE,\
OBJECT_OWNER, \
OS_USER, \
RETURNCODE, \
TERMINAL, \
USERHOST, \
USERNAME \
| eval RETURN_STATUS = If (AUDIT_TYPE="Administrative" OR AUDIT_TYPE="Standard",\
If(RETURNCODE=0, "Success", "Error"),\
""\
)
iseval = 0

[mc_gen]
definition = index="omega_ca_nt"  AUDIT_TYPE="General" \
| table \
_time,\
DB_HOST,\
DB_NAME,\
NT_RECORD_NO,\
NT_EVENT_ID,\
NT_TYPE,\
NT_MESSAGE
iseval = 0
