[pbs]
Stanza for spark confs

spark_instance_id = <string>
* INTERNAL: Spark master running instance ID.

spark_local_dirs_root = <string>
* Root path of Spark master/worker local scratch data directories

spark_local_dirs_auto_clean_up_enabled = <string>
* Set to true to enable cleanup for the local scratch data, default is true

spark_local_dirs_auto_clean_up_interval = <string>
* INTERNAL: Interval (in second) between two cleanup runs, default is 1800

spark_local_dirs_ttl_sec = <string>
* Time To Live (in second) for the local scratch data, default is 1800

spark_master_host = <string>
* INTERNAL: Spark master IP address

spark_ui_port = <port>
* Spark Apllication UI port

spark_block_manager_port = <port>
* Spark block manager port

spark_driver_port = <port>
* Spark driver port

spark_master_port = <port>
* Spark master/worker port

spark_master_webui_port = <port>
* Spark master/worker web UI port

spark_history_webui_port = <port>
* Spark history server web UI port

spark_port_max_retries = <integer>
* Max number retries when binding a port for Spark

splunk_master_uri = <uri>
* INTERNAL: Splunk uri that is running spark master

history_server_enabled = <string>
* Whether to start history server on search heads or not, default is true

spark_custom_conf_enabled = <string>
* Whether to apply custom spark confs on each node SEPARATELY (spark-defaults.conf and spark-env.sh) or not, default is false

spark_worker_id = <string>
* INTERNAL: Spark Worker instance ID

role = <string>
* INTERNAL: Role of current node (indexer/active worker)

security = <string>
* If set to true, spark security will be enabled

spark_shared_secret_key = <String>
* INTERNAL: Spark shared secret key generated by app.

site_affinity = <String>
* Site in which the spark worker should run in a multi-site indexer cluster.

spark_home = <string>
* Spark installed location. This is the absolute path applicable to SHs. Indexers (workers) will adjust depending on the location of application.

active_list = <worker1>, <worker2>, ..
* Active worker list - list of indexers configured to run as spark workers.

poll_timeout= <integer>
* Polling wait time before looking for any conf changes.

replication_id= <integer>
* INTERNAL: Replication ID used for tracking the latest config replication within the current instance (spark_instance_id).