[install]
is_configured = 0

[ui]
is_visible = 0
label = IP Quality Score

[launcher]
author = Joe Miller
description = Add IP reputation data to events using the IP Quality Score API
version = 0.0.2

[package]
id=ipqs
