# #::HDR:: ;; # App: TA-vmware_app_for_splunk ;; # File: tags.conf ;; # Updated: 2024-01-10 14:27:56

[eventtype=vmware_cbc_inventory]
inventory = enabled

[eventtype=vmware_cbc_endpoints]
report  = enabled
process = enabled

[sourcetype=vmware%3Acbc%3Aauthentication_events]
authentication = enabled

[sourcetype=vmware%3Acbc%3Alivequery%3Aresult]
live_query = enabled

[eventtype=modvmware-ban-hash_results]
modaction_result = enabled

[eventtype=modvmware-process-guid-details_results]
modaction_result = enabled

[eventtype=modvmware-kill-process]
modaction_result = enabled

[eventtype=modvmware-enrich-events]
modaction_result = enabled

[eventtype=modvmware-list-process]
modaction_result = enabled

[eventtype=modvmware-quarantine-device]
modaction_result = enabled

[eventtype=modvmware-unquarantine-device]
modaction_result = enabled

[eventtype=modvmware-remove-ioc-watchlist]
modaction_result = enabled

[eventtype=modvmware-add-ioc-watchlist]
modaction_result = enabled

[eventtype=modvmware-get-file-metadata]
modaction_result = enabled

[eventtype=modvmware-run-livequery]
modaction_result = enabled

[eventtype=modvmware-close-alert]
modaction_result = enabled

[eventtype=modvmware-update-device-policy]
modaction_result = enabled

[eventtype=modvmware-process-guid-details]
modaction_result = enabled

[eventtype=modvmware-ban-hash]
modaction_result = enabled

[eventtype=modvmware-add-ioc-watchlist_results]
modaction_result = enabled

[eventtype=modvmware-close-alert_results]
modaction_result = enabled

[eventtype=modvmware-enrich-events_results]
modaction_result = enabled

[eventtype=modvmware-get-file-metadata_results]
modaction_result = enabled

[eventtype=modvmware-kill-process_results]
modaction_result = enabled

[eventtype=modvmware-list-process_results]
modaction_result = enabled

[eventtype=modvmware-quarantine-device_results]
modaction_result = enabled

[eventtype=modvmware-remove-ioc-watchlist_results]
modaction_result = enabled

[eventtype=modvmware-run-livequery_results]
modaction_result = enabled

[eventtype=modvmware-unquarantine-device_results]
modaction_result = enabled

[eventtype=modvmware-update-device-policy_results]
# ADAPTIVE RESPONSE TAGGING
# CIM TAGGING
modaction_result = enabled

[eventtype=vmware_cbc_events]
report    = enabled
# CIM TAGGING reviewed Feb 3, 2023: No Data loaded to check.
process   = enabled
endpoint  = enabled

[eventtype=vmware_cbc_endpoint_filemod]
# CIM TAGGING reviewed Feb 3, 2023
endpoint   = enabled
filesystem = enabled

[eventtype=vmware_cbc_endpoint_regmod]
# CIM TAGGING reviewed Feb 3, 2023: No Data loaded to check.
endpoint  = enabled
registry  = enabled

[eventtype=vmware_cbc_endpoint_moduleload]
# CIM TAGGING reviewed Feb 3, 2023: No Data loaded to check.
endpoint  = enabled
service   = enabled

[eventtype=vmware_cbc_alerts]
# CIM TAGGING reviewed Feb 3, 2023
alert     = enabled

[eventtype=vmware_cbc_malware]
# CIM TAGGING reviewed Feb 3, 2023
attack    = enabled
malware   = enabled

[eventtype=vmware_cbc_auditlogs]
# CIM TAGGING reviewed Feb 2, 2023
change    = enabled
audit     = enabled

[eventtype=vmware_cbc_vulnerability_os_list]
report        = enabled
vulnerability = enabled

[eventtype=modvmware-enrich-alert-obs]
modaction_result = enabled

[sourcetype=vmware:alert_action:vmware-enrich-alert-obs]
alert = enabled

[eventtype=vmware_cbc_authentication_events]
authentication = enabled

[eventtype=vmware_cbc_auth_evt_cleartext]
cleartext = enabled

[eventtype=vmware_cbc_auth_evt_privileged]
privileged = enabled

[sourcetype=vmware%3Aalert_action%3Avmware-enrich-alert-obs]
alert = enabled

[eventtype=modvmware-alert-history]
modaction_result = enabled

[sourcetype=vmware%3Aalert_action%3Avmware-alert-history]
alert = enabled