[event_collector]
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-radware-cwaap-event-collector*.log*]
sourcetype = taradwarecwaapeventcollector:log

[source::...ta_radware_cwaap_event_collector*.log*]
sourcetype = taradwarecwaapeventcollector:log

