[sendbetterslides_alert]
is_custom = 1
label = Send results as Powerpoint Slidedeck
description = Send results as Powerpoint Slidedeck
icon_path = appIcon.png
python.version = python3
payload_format = json
