
[capability::configure_mltk_container]
disabled = 0

[capability::list_mltk_container]
disabled = 0

[capability::control_mltk_container]
disabled = 0

[role_mltk_container_admin]
configure_mltk_container = enabled
importRoles = mltk_container_user

[role_mltk_container_user]
list_mltk_container = enabled
control_mltk_container = enabled
